import * as THREE from './three.module.js';
import {FAMILIES,recipe,normalize} from './core.mjs?v=20261006-assets2';
import {createViewport} from './scene.mjs?v=20261006-assets2';
import {list,save} from './storage.mjs?v=20261006-assets2';
const host=document.getElementById('feed'),filter=document.getElementById('filter'),status=document.getElementById('feed-status'),canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Live procedural asset');const particleCanvas=document.createElement('canvas'),particleRenderer=window.MoorEffects.renderer(particleCanvas);let compiledEffect=null;let viewport=null,records=[],sources=FAMILIES.map(f=>({id:f.id,label:f.label,recipe:recipe(f.id)})),ordinal=0,active=null,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,last=0,dead=false,frame=0;
for(const f of FAMILIES)filter.add(new Option(f.label,f.id));
const observer=new IntersectionObserver(entries=>{for(const e of entries){const r=records.find(r=>r.el===e.target);if(r)r.visible=e.isIntersecting;}choose();},{rootMargin:'0px',threshold:.05});
function poster(){if(active&&viewport){active.poster.style.backgroundImage='url('+(active.recipe.schema==='moor.effect-recipe'?particleCanvas:canvas).toDataURL('image/png')+')';}}
function choose(){const pool=records.filter(r=>r.visible),next=pool.sort((a,b)=>Math.abs(a.el.getBoundingClientRect().top+200-innerHeight/2)-Math.abs(b.el.getBoundingClientRect().top+200-innerHeight/2))[0];if(!next||next===active)return;poster();active=next;const effect=next.recipe.schema==='moor.effect-recipe';(effect?canvas:particleCanvas).remove();next.el.prepend(effect?particleCanvas:canvas);try{if(effect){compiledEffect=window.MoorEffects.compile(next.recipe,String(next.recipe.seed||next.seed));const rect=next.el.getBoundingClientRect(),size=window.MoorEffects.fit(rect.width,rect.height);particleCanvas.width=size.width;particleCanvas.height=size.height;particleRenderer.draw(compiledEffect,1.5,{transparent:true});status.textContent='One live preview · recipe-only saves';return;}if(!viewport)viewport=createViewport(THREE,canvas,next.recipe);else viewport.rig.setRecipe(next.recipe);viewport.draw(1.5,'low');status.textContent='One live 3D preview · '+records.length+' compact recipes in memory · no scrolling writes';}catch(e){status.textContent='3D preview unavailable: '+e.message;}}
function add(){const pool=filter.value==='saved'?sources.filter(s=>s.saved):filter.value==='all'?sources:sources.filter(s=>s.id===filter.value);if(!pool.length){status.textContent='Save a generator in Studio to explore it here.';return;}for(let k=0;k<8;k++){if(records.length>=48){status.textContent='48 previews is the memory limit. Choose a filter to start another batch.';break;}const src=pool[ordinal%pool.length],r=src.recipe.schema==='moor.effect-recipe'?window.MoorEffects.normalize(src.recipe):normalize(src.recipe);r.seed=1729+ordinal*7919;r.name=src.label;const el=document.createElement('article');el.className='asset-card';const image=document.createElement('div');image.className='poster';el.append(image);const caption=document.createElement('section');caption.className='caption';const title=document.createElement('h2');title.textContent=r.name;const small=document.createElement('small');small.textContent='Seed '+r.seed+' · '+r.layers.length+' layers';const actions=document.createElement('div');const edit=document.createElement('button');edit.textContent='Edit';edit.onclick=()=>{sessionStorage.setItem('moor.procedural.edit.v1',JSON.stringify(r));if(r.schema==='moor.effect-recipe'){sessionStorage.setItem('moor.effect.edit.v1',JSON.stringify(r));location.href='effects-studio.html?edit=1';}else location.href='index.html?edit=1';};const keep=document.createElement('button');keep.textContent='Keep generator';keep.onclick=async()=>{try{if(r.schema==='moor.effect-recipe')await window.EffectsLibrary.save('feed-'+r.seed,r.name+' '+r.seed,r);else await save(r.name+' '+r.seed,r);keep.textContent='Saved';status.textContent='Saved the math recipe on this device.';}catch(e){status.textContent=e.message;}};actions.append(small,edit,keep);caption.append(title,actions);el.append(caption);host.append(el);const record={el,poster:image,recipe:r,visible:false};records.push(record);observer.observe(el);ordinal++;}}
filter.onchange=()=>{poster();active=null;observer.disconnect();records=[];host.replaceChildren();ordinal=0;add();};document.getElementById('more').onclick=add;document.getElementById('motion').onclick=e=>{playing=!playing;e.target.textContent=playing?'Pause':'Play';};
async function refresh(){try{const presets=await(await fetch('effects/presets.json')).json();sources=FAMILIES.map(f=>({id:f.id,label:f.label,recipe:recipe(f.id)})).concat(presets.presets.map(p=>({id:'fx-'+p.id,label:p.label,recipe:p.recipe})),(await list()).map(r=>({id:r.id,label:r.recipe.name,recipe:r.recipe,saved:true})),(await window.EffectsLibrary.list()).map(r=>({id:'fx-'+r.id,label:r.name,recipe:r.recipe,saved:true})));}catch(e){status.textContent='Saved library unavailable: '+e.message;}}
function loop(now){if(dead)return;frame=requestAnimationFrame(loop);if(document.hidden||!active?.visible||!playing)return;if(now-last>=1000/24){last=now;if(active.recipe.schema==='moor.effect-recipe')particleRenderer.draw(compiledEffect,now/1000,{transparent:true});else viewport?.draw(now/1000,'low');}}
addEventListener('scroll',()=>choose(),{passive:true});addEventListener('focus',refresh);addEventListener('storage',e=>{if(e.key==='moor-procedural-catalog-changed')refresh();});addEventListener('pagehide',()=>{dead=true;cancelAnimationFrame(frame);observer.disconnect();viewport?.dispose();particleRenderer.dispose();});await refresh();add();frame=requestAnimationFrame(loop);
