import {sample,normalize,MAX_OBJECTS} from './core.mjs';
import {softwareViewport} from './software.mjs';
import {CAUSTIC_GLSL} from './aquarium-math.mjs';
/* Host owns THREE, scene, clock and lifetime. No private copy of the world. */
export function createAssetScene(THREE,input){
 let recipe=normalize(input),image=null;
 const root=new THREE.Group(),batches=new Map(),dummy=new THREE.Object3D(),color=new THREE.Color();root.name='MOOR procedural asset';
 const geometry={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,12,8),cylinder:new THREE.CylinderGeometry(.5,.5,1,12),segment:new THREE.CylinderGeometry(.5,.5,1,6),leaf:new THREE.SphereGeometry(.5,8,6),ring:new THREE.TorusGeometry(1,.018,5,40),water:new THREE.PlaneGeometry(1,1), 'image-strip':new THREE.BoxGeometry(1,1,.01)};
 // Original aquarium caustic field rendered on the fitted water surface.
 const waterMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{time:{value:0}},vertexShader:'varying vec2 uv0;void main(){uv0=uv;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.0);}',fragmentShader:'uniform float time;varying vec2 uv0;'+CAUSTIC_GLSL+'void main(){float c=caustic(uv0*5.0,time);gl_FragColor=vec4(vec3(.12,.7,.8)+c*vec3(.5,.3,.15),.22+c*.32);}'});
 function batch(o){const key=o.shape+'|'+Math.round(o.alpha*10)+'|'+(o.glow>.1?1:0);if(batches.has(key))return batches.get(key);let material=o.shape==='water'?waterMaterial:new THREE.MeshPhongMaterial({color:0xffffff,shininess:85,side:THREE.DoubleSide,transparent:o.alpha<1,opacity:o.alpha,depthWrite:o.alpha>.5,emissive:0xffffff,emissiveIntensity:o.glow>.1?.38:0});if(o.shape==='image-strip'&&image){material.map=image;material.color.set(0xffffff);material.emissiveIntensity=0;material.needsUpdate=true;}let geo=geometry[o.shape];
if(o.shape==='image-strip'&&image){geo=geo.clone();geo.setAttribute('imageRange',new THREE.InstancedBufferAttribute(new Float32Array(MAX_OBJECTS*2),2));material.onBeforeCompile=shader=>{shader.vertexShader='attribute vec2 imageRange;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\n#ifdef USE_MAP\nvMapUv.x=(vMapUv.x+imageRange.x)/imageRange.y;\n#endif');};}
const mesh=new THREE.InstancedMesh(geo,material,MAX_OBJECTS);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;mesh.count=0;root.add(mesh);const b={mesh,count:0,material};batches.set(key,b);return b;}
 function update(time,lod='medium'){const frame=sample(recipe,time,lod);for(const b of batches.values())b.count=0;for(const o of frame.objects){const b=batch(o),i=b.count++;dummy.position.fromArray(o.position);dummy.rotation.set(...o.rotation);if(o.shape==='water')dummy.rotation.x=-Math.PI/2;dummy.scale.fromArray(o.scale);dummy.updateMatrix();b.mesh.setMatrixAt(i,dummy.matrix);if(o.shape==='image-strip'&&image){const [part,count]=o.tag.split('/').map(Number);b.mesh.geometry.attributes.imageRange.setXY(i,part,count);b.mesh.geometry.attributes.imageRange.needsUpdate=true;}color.setHSL(((o.hue%360)+360)%360/360,.65,o.shape==='image-strip'&&image?1:.58);b.mesh.setColorAt(i,color);}for(const b of batches.values()){b.mesh.count=b.count;b.mesh.instanceMatrix.needsUpdate=true;if(b.mesh.instanceColor)b.mesh.instanceColor.needsUpdate=true;}waterMaterial.uniforms.time.value=time;return frame;}
 function clear(){for(const b of batches.values()){root.remove(b.mesh);b.mesh.dispose?.();if(b.material!==waterMaterial)b.material.dispose();if(b.mesh.geometry!==geometry[b.mesh.userData.shape]&&b.mesh.geometry.attributes.imageRange)b.mesh.geometry.dispose();}batches.clear();}
 return {root,update,setRecipe(value){recipe=normalize(value);},setImage(texture){clear();image?.dispose();image=texture;},dispose(){clear();for(const g of Object.values(geometry))g.dispose();waterMaterial.dispose();image?.dispose();},getRecipe:()=>normalize(recipe)};
}
export function createViewport(THREE,canvas,input){
 let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'low-power'});}catch{return softwareViewport(canvas,input);}renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x090f15,0);
 const scene=new THREE.Scene();const rig=createAssetScene(THREE,input);scene.add(rig.root);scene.add(new THREE.HemisphereLight(0xbceeff,0x1e1727,2));const key=new THREE.DirectionalLight(0xffefd7,2.2);key.position.set(4,6,8);scene.add(key);const fill=new THREE.DirectionalLight(0x84bcff,1.2);fill.position.set(-5,2,-4);scene.add(fill);
 const camera=new THREE.PerspectiveCamera(42,1,.01,1000),ortho=new THREE.OrthographicCamera(-3,3,3,-3,.01,1000);let view={yaw:.38,pitch:.2,zoom:1,projection:'perspective'},last=0;
 function draw(time,lod='medium'){last=time;const rect=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(rect.width)),h=Math.max(1,Math.round(rect.height)),ratio=Math.min(1,Math.sqrt(750000/(w*h)));renderer.setSize(Math.round(w*ratio),Math.round(h*ratio),false);const d=Math.max(...rig.getRecipe().dimensions),distance=d*2.1/view.zoom,active=view.projection==='orthographic'?ortho:camera;camera.aspect=w/h;ortho.left=-d*w/h/view.zoom*.68;ortho.right=-ortho.left;ortho.top=d/view.zoom*.68;ortho.bottom=-ortho.top;active.position.set(Math.sin(view.yaw)*Math.cos(view.pitch)*distance,Math.sin(view.pitch)*distance,Math.cos(view.yaw)*Math.cos(view.pitch)*distance);active.lookAt(0,0,0);active.updateProjectionMatrix();const frame=rig.update(time,lod);renderer.render(scene,active);return frame;}
 return {rig,draw,setView(patch){view={...view,...patch};},view:()=>({...view}),dispose(){rig.dispose();renderer.dispose();},png:()=>{draw(last);return canvas.toDataURL('image/png');},info:()=>renderer.info};
}
