import {sample,normalize} from './core.mjs';
/* Bounded software projection for devices without WebGL. Same 3D source math. */
export function softwareViewport(canvas,input){
 const ctx=canvas.getContext('2d',{alpha:true});if(!ctx)throw Error('No graphics context is available.');let recipe=normalize(input),view={yaw:.38,pitch:.2,zoom:1,projection:'perspective'},last=0,dead=false,texture=null,calls=0;
 const rotate=(v,r)=>{v=[...v];for(let i=0;i<3;i++){const j=(i+1)%3,k=(i+2)%3,c=Math.cos(r[i]||0),s=Math.sin(r[i]||0),x=v[j];v[j]=x*c-v[k]*s;v[k]=x*s+v[k]*c;}return v;};
 function draw(time,lod='medium'){last=time;if(dead)return{objects:[]};const rect=canvas.getBoundingClientRect(),factor=Math.min(1,Math.sqrt(500000/(Math.max(1,rect.width*rect.height))));canvas.width=Math.max(1,Math.round(rect.width*factor));canvas.height=Math.max(1,Math.round(rect.height*factor));ctx.clearRect(0,0,canvas.width,canvas.height);calls=0;const frame=sample(recipe,time,lod),d=Math.max(...recipe.dimensions),distance=d*2.1/view.zoom,base=Math.min(canvas.width,canvas.height)/d*.8*view.zoom;
 const project=p=>{const v=rotate(p,[0,-view.yaw,0]),q=rotate(v,[view.pitch,0,0]),scale=view.projection==='orthographic'?base:base*distance/Math.max(.05,distance-q[2]);return{x:canvas.width/2+q[0]*scale,y:canvas.height/2-q[1]*scale,z:q[2],scale};};
 const vertices=(o,points)=>points.map(p=>{const v=rotate(p.map((x,i)=>x*o.scale[i]),o.rotation).map((x,i)=>x+o.position[i]);return project(v);});
 const commands=[];
 for(const o of frame.objects){const center=project(o.position);if(o.shape==='box'||o.shape==='image-strip'||o.shape==='water'){const points=[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],vs=vertices(o,points),faces=[[0,1,2,3],[4,7,6,5],[0,4,5,1],[3,2,6,7],[1,5,6,2],[0,3,7,4]];if(o.shape==='water'){const v=vertices({...o,rotation:[Math.PI/2,0,0]},[[-.5,-.5,0],[.5,-.5,0],[.5,.5,0],[-.5,.5,0]]);commands.push({o,points:v,z:center.z,light:.8});}else for(let i=0;i<faces.length;i++){const p=faces[i].map(j=>vs[j]);commands.push({o,points:p,z:p.reduce((n,p)=>n+p.z,0)/4,light:.48+i*.06,face:i});}}else if(o.shape==='ring'){const p=vertices(o,Array.from({length:41},(_,i)=>[Math.cos(i*Math.PI*2/40),Math.sin(i*Math.PI*2/40),0]));commands.push({o,points:p,z:center.z,line:true,light:.75});}else if(o.shape==='segment'||o.shape==='cylinder'){const p=vertices(o,[[0,-.5,0],[0,.5,0]]);commands.push({o,points:p,z:center.z,line:true,width:o.scale[0]*center.scale,light:.72});}else{const vs=vertices(o,[[1,0,0],[0,1,0],[0,0,1]]),rx=Math.max(1,...vs.map(v=>Math.abs(v.x-center.x))),ry=Math.max(1,...vs.map(v=>Math.abs(v.y-center.y)));commands.push({o,center,rx,ry,z:center.z,light:.6});}}
 commands.sort((a,b)=>a.z-b.z);
 for(const c of commands){const {o}=c;ctx.globalAlpha=o.alpha;ctx.globalCompositeOperation=o.glow>.1?'lighter':'source-over';ctx.shadowBlur=o.glow>.1?o.glow*8:0;ctx.shadowColor=`hsl(${o.hue} 90% 65%)`;ctx.fillStyle=`hsl(${o.hue} 60% ${Math.round(c.light*70)}%)`;ctx.strokeStyle=`hsl(${o.hue} 70% 65%)`;calls++;if(c.points){ctx.beginPath();c.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(c.line){ctx.lineWidth=c.width||1.2;ctx.lineCap='round';ctx.stroke();}else{ctx.closePath();if(o.shape==='image-strip'&&texture?.image&&c.face===1){const[part,count]=o.tag.split('/').map(Number),p=c.points;ctx.save();ctx.clip();const img=texture.image,w=img.width/count,ax=p[1].x-p[0].x,ay=p[1].y-p[0].y,bx=p[3].x-p[0].x,by=p[3].y-p[0].y;ctx.transform(ax/w,ay/w,bx/img.height,by/img.height,p[0].x,p[0].y);ctx.drawImage(img,part*w,0,w,img.height,0,0,w,img.height);ctx.restore();}else ctx.fill();}}else{const gradient=ctx.createRadialGradient(c.center.x-c.rx*.3,c.center.y-c.ry*.35,0,c.center.x,c.center.y,Math.max(c.rx,c.ry));gradient.addColorStop(0,`hsl(${o.hue} 65% 77%)`);gradient.addColorStop(.55,`hsl(${o.hue} 65% 47%)`);gradient.addColorStop(1,`hsl(${o.hue} 60% 20%)`);ctx.fillStyle=gradient;ctx.beginPath();ctx.ellipse(c.center.x,c.center.y,c.rx,c.ry,0,0,Math.PI*2);ctx.fill();}}
 ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';return frame;
 }
 return {software:true,rig:{setRecipe(value){recipe=normalize(value);},getRecipe:()=>normalize(recipe),setImage(value){texture?.dispose?.();texture=value;}},draw,setView(p){view={...view,...p};},view:()=>({...view}),png:()=>{draw(last);return canvas.toDataURL('image/png');},info:()=>({render:{calls}}),dispose(){dead=true;texture?.dispose?.();}};
}
