import * as THREE from './three.module.js';
import {recipe,normalize,FAMILIES,PARAMS,svg} from './core.mjs';
import {createViewport} from './scene.mjs';
import * as Library from './storage.mjs';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),preview=query.get('preview')==='1';
let current=recipe(query.get('family')||'aquarium',Number(query.get('seed'))||1729),selected=0,time=1.2,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,visible=true,disposed=false,viewport=null,last=0,then=0,undo=[],redo=[];
if(query.has('edit')){try{const raw=sessionStorage.getItem('moor.procedural.edit.v1');if(raw)current=normalize(JSON.parse(raw));sessionStorage.removeItem('moor.procedural.edit.v1');}catch(e){note('Edit recipe could not be restored: '+e.message);}}
if(preview)document.body.classList.add('preview');
function note(s){$('status').textContent=s;}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function snapshot(){return JSON.stringify(current);}
function change(fn){const before=snapshot(),next=normalize(fn(normalize(current)));if(JSON.stringify(next)===before)return;undo.push(before);undo=undo.slice(-24);redo=[];current=next;selected=Math.min(selected,current.layers.length-1);renderUI();draw();}
function set(value){current=normalize(value);selected=0;renderUI();draw();}
function draw(){if(!viewport||disposed)return;viewport.rig.setRecipe(current);const frame=viewport.draw(time,$('lod').value);$('stats').textContent=frame.objects.length+' objects · '+(viewport.software?'software 3D · ':'')+viewport.info().render.calls+' draws\n'+new TextEncoder().encode(snapshot()).length+' recipe bytes';$('time').value=String(time);$('clock').textContent=time.toFixed(2)+' s';document.body.dataset.rendered=current.layers[selected].family;document.body.dataset.objects=String(frame.objects.length);}
function renderUI(){const layer=current.layers[selected],family=FAMILIES.find(f=>f.id===layer.family);$('name').value=current.name;$('title').textContent=family.label;$('category').textContent=family.category.toUpperCase();$('math').textContent=family.math;$('seed').value=String(current.seed);['width','height','depth'].forEach((id,i)=>$(id).value=current.dimensions[i]);$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;
 $('layers').replaceChildren();current.layers.forEach((l,i)=>{const b=document.createElement('button');b.className='layer';b.textContent=(i+1)+'. '+FAMILIES.find(f=>f.id===l.family).label;b.setAttribute('aria-pressed',String(i===selected));b.onclick=()=>{selected=i;renderUI();};$('layers').append(b);});if(current.layers.length>1){const b=document.createElement('button');b.textContent='Remove layer';b.onclick=()=>change(r=>{r.layers.splice(selected,1);return r;});$('layers').append(b);}
 $('controls').replaceChildren();for(const key of family.parameters){const label=document.createElement('label');label.textContent=key==='mouth'?'Mouth envelope':key==='opening'?'Opening / aperture':key;const input=document.createElement('input');if(key==='text'){input.value=layer.params.text;input.maxLength=32;input.onchange=()=>change(r=>{r.layers[selected].params.text=input.value;return r;});}else{const[,min,max]=PARAMS[key];input.type='range';input.min=min;input.max=max;input.step=key==='count'?'1':'.01';input.value=layer.params[key];const output=document.createElement('output');output.textContent=' · '+input.value;label.append(output);input.oninput=()=>{const v=Number(input.value);current.layers[selected].params[key]=v;output.textContent=' · '+v;draw();};input.onpointerdown=()=>{undo.push(snapshot());undo=undo.slice(-24);redo=[];};input.onchange=()=>{current=normalize(current);renderUI();};}input.setAttribute('aria-label',key);label.append(input);$('controls').append(label);}
 if(['face','mouth'].includes(layer.family)){const label=document.createElement('label');label.textContent='Speech shape';const s=document.createElement('select');for(const shape of['open','round','spread','closed'])s.add(new Option(shape,shape));s.value=layer.params.phoneme;s.onchange=()=>change(r=>{r.layers[selected].params.phoneme=s.value;return r;});label.append(s);$('controls').append(label);}
 const transforms=document.createElement('details');transforms.innerHTML='<summary>Layer transform</summary>';for(const k of['position','scale','rotation']){const label=document.createElement('label');label.textContent=k+' (x, y, z)';const input=document.createElement('input');input.value=layer[k].join(', ');input.onchange=()=>change(r=>{r.layers[selected][k]=parseVec(input.value);return r;});label.append(input);transforms.append(label);}$('controls').append(transforms);
 $('models').replaceChildren();current.models.forEach((m,i)=>{const div=document.createElement('div');div.className='model';const title=document.createElement('strong');title.textContent=m.shape+' '+(i+1);div.append(title);for(const k of['position','scale','rotation']){const input=document.createElement('input');input.setAttribute('aria-label',m.id+' '+k);input.value=m[k].join(', ');input.onchange=()=>change(r=>{r.models[i][k]=parseVec(input.value);return r;});div.append(input);}const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=()=>change(r=>{r.models.splice(i,1);return r;});div.append(remove);$('models').append(div);});
 document.querySelectorAll('#families button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.family===layer.family)));$('play').textContent=playing?'Pause':'Play';
}
function parseVec(text){const a=String(text).split(',').map(Number);if(a.length!==3||a.some(n=>!Number.isFinite(n)))throw Error('Use three finite numbers separated by commas.');return a;}
function families(){const search=$('search').value.toLowerCase();$('families').replaceChildren();for(const f of FAMILIES.filter(f=>(f.label+' '+f.category).toLowerCase().includes(search))){const b=document.createElement('button');b.dataset.family=f.id;const label=document.createElement('span');label.textContent=f.label;const small=document.createElement('small');small.textContent=f.category;b.append(label,small);b.onclick=()=>change(r=>{r.layers[selected].family=f.id;r.name=f.label;return r;});$('families').append(b);}}
async function saved(){try{const records=await Library.list();$('saved').replaceChildren();for(const rec of records){const row=document.createElement('div'),b=document.createElement('button');b.textContent=rec.recipe.name;b.onclick=()=>{undo.push(snapshot());set(rec.recipe);};const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','Delete '+rec.recipe.name);del.onclick=async()=>{await Library.remove(rec.id);await saved();};row.append(b,del);$('saved').append(row);}}catch(e){note('Saved generators unavailable: '+e.message);}}
$('search').oninput=families;$('name').onchange=()=>change(r=>({...r,name:$('name').value}));$('seed').onchange=()=>change(r=>({...r,seed:Number($('seed').value)}));$('vary').onclick=()=>change(r=>({...r,seed:Math.floor(Math.random()*2147483646)+1}));$('add').onclick=()=>{if(current.layers.length>=8){note('Eight layers is the live scene limit.');return;}change(r=>{r.layers.push(recipe(r.layers[selected].family,r.seed).layers[0]);r.layers.at(-1).scale=[.5,.5,.5];r.layers.at(-1).position=[.5,.1,.1];return r;});selected=current.layers.length-1;renderUI();};
['width','height','depth'].forEach((id,i)=>$(id).onchange=()=>change(r=>{r.dimensions[i]=Number($(id).value);return r;}));$('lod').onchange=draw;
$('undo').onclick=()=>{if(!undo.length)return;redo.push(snapshot());set(JSON.parse(undo.pop()));};$('redo').onclick=()=>{if(!redo.length)return;undo.push(snapshot());set(JSON.parse(redo.pop()));};
$('play').onclick=()=>{playing=!playing;renderUI();draw();};$('time').oninput=()=>{playing=false;time=Number($('time').value);renderUI();draw();};$('projection').onchange=()=>{viewport.setView({projection:$('projection').value});draw();};$('camera').onchange=()=>{viewport.setView($('camera').value==='front'?{yaw:0,pitch:0}:$('camera').value==='top'?{yaw:0,pitch:1.55}:{yaw:.38,pitch:.2});draw();};
let drag=null;$('canvas').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};$('canvas').setPointerCapture(e.pointerId);};$('canvas').onpointermove=e=>{if(!drag||!viewport)return;const v=viewport.view();viewport.setView({yaw:v.yaw+(e.clientX-drag.x)*.007,pitch:Math.max(-1.5,Math.min(1.5,v.pitch+(e.clientY-drag.y)*.007))});drag={x:e.clientX,y:e.clientY};draw();};$('canvas').onpointerup=$('canvas').onpointercancel=()=>drag=null;$('canvas').addEventListener('wheel',e=>{e.preventDefault();const v=viewport.view();viewport.setView({zoom:Math.max(.25,Math.min(4,v.zoom-e.deltaY*.002))});draw();},{passive:false});
$('save').onclick=async()=>{try{const rec=await Library.save(current.name,current);await saved();note('Saved '+rec.recipe.name+'. It joins Wonder Feed on this device.');}catch(e){note(e.message);}};
$('export').onclick=()=>download('moor-asset-recipe.json',JSON.stringify(current,null,2));$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>48000)throw Error('Recipe exceeds 48 KB.');const value=normalize(JSON.parse(await f.text()));undo.push(snapshot());set(value);note('Recipe imported.');}catch(e){note(e.message);}finally{$('file').value='';}};
$('png').onclick=()=>{draw();$('canvas').toBlob(blob=>{if(!blob){note('PNG export failed.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='moor-asset.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');};$('svg').onclick=()=>{try{download('moor-strokes.svg',svg(current),'image/svg+xml');}catch(e){note(e.message);}};
$('image').onchange=async()=>{const file=$('image').files[0];if(!file)return;if(file.size>8*1024*1024){note('Choose an image smaller than 8 MB.');return;}const url=URL.createObjectURL(file);try{const texture=await new THREE.TextureLoader().loadAsync(url);texture.colorSpace=THREE.SRGBColorSpace;viewport.rig.setImage(texture);draw();note('Local source image loaded. Export it alongside the recipe to reuse it elsewhere.');}catch(e){note('Image could not be loaded.');}finally{URL.revokeObjectURL(url);}};
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{if(current.models.length>=12){note('Twelve model primitives is the limit.');return;}change(r=>{r.models.push({shape:b.dataset.model,position:[0,-.85,0],scale:[1,.15,.8],rotation:[0,0,0],hue:210});return r;});});
$('world').onclick=()=>{try{const binding={schema:'moor.procedural-placement',version:1,recipe:normalize(current),position:parseVec($('world-pos').value)};const key='moor.procedural.placements.v1';const old=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(old)||old.length>=12)throw Error('World has twelve placements. Clear or export one in Morverse before adding another.');localStorage.setItem(key,JSON.stringify([...old,binding]));download('moor-world-placement.json',JSON.stringify(binding,null,2));note('Placed locally. Open Morverse on this same origin to see it; import the binding to transfer hosts.');}catch(e){note(e.message);}};
// Native MoorPack format, SHA-256 per file, works with existing package lifecycle.
const PACKAGE_FILES=['index.html','studio.css','studio.mjs','core.mjs','scene.mjs','storage.mjs','aquarium-math.mjs','software.mjs','three.module.js'];
$('pack').onclick=async()=>{try{note('Packaging the local app and current recipe…');const files=[];for(const path of PACKAGE_FILES){const response=await fetch(new URL(path,import.meta.url));if(!response.ok)throw Error('Cannot package '+path);let bytes=new Uint8Array(await response.arrayBuffer());if(path==='studio.mjs'){const text=new TextDecoder().decode(bytes).replace("let current=recipe(query.get('family')||'aquarium',Number(query.get('seed'))||1729)",'let current='+JSON.stringify(current));bytes=new TextEncoder().encode(text);}const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');let binary='';for(const b of bytes)binary+=String.fromCharCode(b);files.push({path,sha256:hash,contentBase64:btoa(binary)});}download('procedural-studio.moorpack.json',JSON.stringify({formatVersion:1,asset:{slug:'moor-procedural-studio',version:'1.0.0'},files}));note('Integrity-checked app package exported. Publish through MOOR Create or the launcher.');}catch(e){note(e.message);}};
function tick(now){if(disposed)return;requestAnimationFrame(tick);const dt=last?Math.min(.1,(now-last)/1000):0;last=now;if(playing&&visible&&!document.hidden){time=(time+dt)%12;if(now-then>=1000/(viewport.software?15:30)){draw();then=now;}}}
const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;});io.observe($('canvas'));window.addEventListener('resize',draw);window.addEventListener('pagehide',()=>{disposed=true;io.disconnect();viewport?.dispose();});
function take(){return{schema:'moor.procedural-take',version:1,recipe:normalize(current),time,camera:viewport?.view(),lod:$('lod').value};}
const API={describe:()=>({version:1,families:FAMILIES,limits:{layers:8,objects:900,recipeBytes:48000},space:'3D',lenses:false}),getTake:take,setRecipe(value){set(value);return take();},setTime(value){playing=false;time=Math.max(0,Math.min(12,Number(value)||0));draw();return take();},setView(value){viewport.setView(value);draw();return take();},saveGenerator:async name=>Library.save(name||current.name,current),listGenerators:Library.list};
window.ProceduralStudio=Object.freeze(API);window.WonderPreview={canvas:$('canvas'),setRecipe({seed,params}){const value=params?.proceduralRecipe||params?.recipe;if(value?.schema==='moor.procedural-recipe')current=normalize(value);if(seed)current.seed=Number(seed)||current.seed;renderUI();draw();},dispose(){disposed=true;io.disconnect();viewport?.dispose();}};
try{viewport=createViewport(THREE,$('canvas'),current);if(query.get('saved')){const rec=(await Library.list()).find(r=>r.id===query.get('saved'));if(rec)current=normalize(rec.recipe);}families();renderUI();draw();if(!preview)await saved();requestAnimationFrame(tick);}catch(e){note('3D preview unavailable: '+e.message);document.body.dataset.error=e.message;}
if(navigator.modelContext?.registerTool){for(const[name,description,properties,execute]of[
 ['describe','Inspect procedural generator families and limits',{},()=>API.describe()],['get_take','Read exact recipe, time and camera',{},()=>take()],['set_recipe','Apply a versioned procedural recipe',{recipe:{type:'object'}},args=>API.setRecipe(args.recipe)],['set_time','Seek absolute seconds',{time:{type:'number'}},args=>API.setTime(args.time)],['save_generator','Explicitly save recipe for automatic feed discovery',{name:{type:'string'}},args=>API.saveGenerator(args.name)]])try{navigator.modelContext.registerTool({name:'procedural_'+name,description,inputSchema:{type:'object',properties,additionalProperties:false},execute:async args=>({content:[{type:'text',text:JSON.stringify(await execute(args))}]})});}catch{}}
