import {createAssetScene} from './scene.mjs?v=20261006-assets2';
import {normalize,recipe} from './core.mjs?v=20261006-assets2';
export const PLACEMENT_KEY='moor.procedural.placements.v1';
export function normalizePlacement(value){if(!value||value.schema!=='moor.procedural-placement'||value.version!==1)throw Error('Expected a MOOR procedural placement v1.');if(!Array.isArray(value.position)||value.position.length!==3||value.position.some(n=>typeof n!=='number'||!Number.isFinite(n)||Math.abs(n)>10000))throw Error('Placement needs three finite coordinates within the world boundary.');return{schema:value.schema,version:1,recipe:normalize(value.recipe),position:[...value.position]};}
export const proceduralAssets={
 manifest:{id:'moor.city.procedural-assets',version:'1.0.0',cityApi:'1',permissions:['world.read','world.entities','events','ui.panels','storage.private']},
 setup(ctx){
  const {THREE,scene}=ctx.graphics;let rigs=[],placements=[],last=0,status='',panel;
  const read=()=>{try{const v=JSON.parse(localStorage.getItem(PLACEMENT_KEY)||'[]');return Array.isArray(v)?v.slice(0,12).map(normalizePlacement):[];}catch(e){status='Saved placements could not be read: '+e.message;return[];}};
  const dispose=()=>{for(const rig of rigs){scene.remove(rig.root);rig.dispose();}rigs=[];};
  const refresh=()=>{dispose();placements=read();for(const p of placements.slice(0,4)){const rig=createAssetScene(THREE,p.recipe);rig.root.position.fromArray(p.position);rig.update(0,'low');scene.add(rig.root);rigs.push(rig);}draw();};
  const save=()=>{localStorage.setItem(PLACEMENT_KEY,JSON.stringify(placements));refresh();};
  panel=document.createElement('details');panel.className='moor-procedural-world';panel.style.cssText='position:fixed;right:16px;top:100px;z-index:1200;background:#0d1927e8;color:#e4f4f3;border:1px solid #44706b;border-radius:12px;padding:12px;max-width:310px;font:12px/1.5 system-ui';panel.innerHTML='<summary style="cursor:pointer">Living assets · Procedural Studio</summary><p>Place compact seeded assets into this world. Four scenes are active at once.</p><a style="color:#a5e4d2" href="/procedural-studio/index.html" target="_blank" rel="noopener">Open Studio ↗</a><p><label>Position x, y, z <input data-position value="8, 2, 8" style="width:100%;padding:7px"></label></p><button data-aquarium>Add aquarium</button> <button data-garden>Add garden</button><p><label>Import world binding<input data-import type="file" accept=".json,application/json" style="width:100%"></label></p><div data-list></div><p data-status role="status"></p>';document.body.append(panel);
  const draw=()=>{const list=panel.querySelector('[data-list]');list.replaceChildren();placements.forEach((p,i)=>{const row=document.createElement('p'),b=document.createElement('button');row.textContent=p.recipe.name+' · '+p.position.join(', ')+' ';b.textContent='Remove';b.onclick=()=>{placements.splice(i,1);save();};row.append(b);list.append(row);});panel.querySelector('[data-status]').textContent=status||`${rigs.length} active · ${placements.length} saved locally`;};
  const pos=()=>{const v=panel.querySelector('[data-position]').value.split(',').map(Number);return normalizePlacement({schema:'moor.procedural-placement',version:1,recipe:recipe(),position:v}).position;};
  const insert=value=>{const p=normalizePlacement(value);if(placements.length>=12)throw Error('Remove a saved placement before adding another.');placements.push(p);save();ctx.events.emit('procedural:placed',{name:p.recipe.name,position:p.position});return p;};
  const add=family=>{try{const p=pos();p[1]=ctx.world.heightAt(p[0],p[2])+2;insert({schema:'moor.procedural-placement',version:1,recipe:recipe(family),position:p});}catch(e){status=e.message;draw();}};
  panel.querySelector('[data-aquarium]').onclick=()=>add('aquarium');panel.querySelector('[data-garden]').onclick=()=>add('foliage');panel.querySelector('[data-import]').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50000)throw Error('Binding exceeds 50 KB.');insert(JSON.parse(await f.text()));status='Placement imported into this world.';}catch(e){status=e.message;}finally{draw();}};
  this.update=(dt,now)=>{if(now-last<1000/15||document.hidden)return;last=now;for(const rig of rigs)rig.update(now/1000,'low');};this.cleanup=()=>{dispose();panel.remove();};ctx.world.proceduralAssets=Object.freeze({place:insert,refresh,snapshot:()=>placements.map(normalizePlacement),clear(){placements=[];save();},dispose:this.cleanup});refresh();
 },frame(dt,now){this.update?.(dt,now);},stop(){this.cleanup?.();}
};
