/* AWE intent corpus v1 — distilled from Sebastian's stated taste.
 * Sources: MEMORY.md aesthetics ("Realistic but mature", warm storybook realism,
 * craftsmanship, beauty persuades), 2026-10-04 Pulse-as-instrument (carved stone/glass,
 * deep shadow, moving light), Stream topics (glass art, architecture, interiors,
 * rainy days), HEARTH (warmth, coziness, golden light, nature kept by care).
 * RULE: every atom is implementation-free phenomenology. No tool names, no "how to
 * build this". Only what a person standing there would perceive. */
var AWE_INTENT = {
version: 1,
places: [
{t:"a narrow cove where the cliffs lean in like the walls of a chapel, black rock gone green with moss at the waterline", v:"the cliffs rise on both sides, dark and wetly green, and between them the sea lies flat and bright as a held mirror"},
{t:"the third terrace of an old hillside garden, where the stone steps have been worn into shallow bowls by a century of feet", v:"the terraces fall away below you in green steps, each one a different shade, down to the valley floor hazy with distance"},
{t:"a boathouse at the far end of a still lake, its doors swung open to the water and the evening coming in", v:"the lake stretches out unbroken to the far shore, holding the sky so perfectly the world looks folded in half"},
{t:"a clearing in a redwood grove where the light falls in columns and the ground is soft with a hundred years of needles", v:"the trunks rise like the pillars of a cathedral, going up and up until the green roof closes over the light itself"},
{t:"the window seat of a stone cottage during a rainstorm, the glass cold against your shoulder", v:"beyond the rain-streaked glass the hillside blurs green and grey, sheep moving through it like slow punctuation"},
{t:"a tidal rockpool at low tide, cut off from the sea and holding the whole sky", v:"all around, the exposed reef glistens dark and the sea waits beyond the rocks, patient as an animal"},
{t:"an old stone bridge with a single arch, the river moving under it the color of bottle glass", v:"the river runs away in both directions, green and glassy, fringed with willows that trail their fingers in the current"},
{t:"a walled courtyard garden an hour before sunset, the walls warm as bread from the day's sun", v:"the garden is a room with no ceiling: espaliered fruit trees against the walls, a fountain at the center, the sky going gold overhead"},
{t:"the top of a coastal stair cut into the cliff, 214 steps down to a beach no road reaches", v:"below, the beach curves away empty in both directions, white sand meeting white surf under the huge open sky"},
{t:"a greenhouse in late afternoon, humid air, the glass panes ticking as they cool", v:"through the glass the real garden glows beyond, rows of green going soft at the edges in the heat-haze"},
{t:"a mountain hut with one lit window, seen from the dark trail as the blue hour settles", v:"the peaks stand around in their evening blue, snow catching the last pink light, the valley already dark below"},
{t:"the shallow end of a hot spring in the woods, steam braiding up through the cedars", v:"the cedars close around in every direction, dark green and straight, steam rising between them like the forest breathing"},
{t:"a library with a ladder and a round window, dust moving in the light like slow snow", v:"through the round window: the sea, impossibly blue, framed like the only painting the room will ever need"},
{t:"an orchard at blossom time, the petals coming down so steadily it feels like weather", v:"the rows of trees run to the horizon in white and pink, and beyond them the hills are a soft blue-green haze"},
{t:"a desert canyon at dawn, the walls catching fire one layer at a time from the top down", v:"the canyon opens below you in bands of red and gold, the river a green thread at the bottom, the far rim already burning"},
{t:"a wooden footbridge over a marsh, the reeds hissing softly on both sides", v:"the marsh spreads flat to every horizon, water and reed and sky in equal thirds, birds stitching black lines across it"},
{t:"the courtyard of a bathhouse, steam rising off the water and the stone still warm underfoot", v:"beyond the courtyard wall, cypress trees stand dark against a sky going violet, and the first star is out"},
{t:"a lighthouse gallery at night, the lamp turning somewhere below you and the sea all around", v:"the sea is black glass to every horizon, the beam sweeping across it and catching the white manes of the waves"},
{t:"a valley overlook after the rain has passed, the clouds torn open and the fields steaming", v:"the whole valley lies below, patched green and gold, the river stitching silver through it, steam rising off the fields"},
{t:"a small chapel with the door left open, the sea visible through it like a painting that moves", v:"the doorway frames the sea perfectly — blue, white-maned, endless — with the altar's candles trembling in the foreground"},
{t:"a tea house at the edge of a bamboo grove, the floor cool under your knees", v:"the bamboo rises in green ranks, stalks clicking softly, light falling through in shifting bars of gold"},
{t:"the stern of a slow wooden boat at golden hour, the wake stitching itself closed behind you", v:"the water runs to the horizon in hammered gold, the far shore a dark line, gulls hanging motionless in the updraft"},
{t:"a hillside of lavender at dusk, the rows running down until they blur into purple haze", v:"the purple rows flow downhill like water frozen mid-pour, and beyond them the plain shimmers in the heat of the day's end"},
{t:"an ice cave at noon, the light coming through the ceiling blue as deep water", v:"the ice walls curve away in impossible blue, light moving through them the way it moves through deep sea"}
],
hours: [
{t:"forty minutes before sunset, after a rain that washed everything clean", p:"dusk"},
{t:"the blue hour, when the last light is the color of a held breath", p:"dusk"},
{t:"just after dawn, the sun still below the ridge but the sky already deciding on gold", p:"dawn"},
{t:"midnight in midsummer, the sky never fully dark, everything edged in silver", p:"night"},
{t:"the exact middle of a thunderstorm's pause, the air electric and green", p:"day"},
{t:"late morning in autumn, the light low and slanting and smelling of leaves", p:"day"},
{t:"an hour past sunrise on the first cold day of the year, your breath visible", p:"dawn"},
{t:"the long amber evening of high summer, when the sun takes hours to set", p:"dusk"},
{t:"first light after a night of snow, the world made new and silent", p:"dawn"},
{t:"the grey-gold hour before a storm, when the light goes strange and beautiful", p:"dusk"},
{t:"midday in a heatwave, everything shimmering, the shade feeling like water", p:"day"},
{t:"the violet minutes right after the sun drops below the sea", p:"dusk"},
{t:"a windless winter afternoon, the sun low and the shadows impossibly long", p:"day"},
{t:"the pale hour before dawn when the birds start one by one, like lights coming on", p:"dawn"},
{t:"golden hour in spring, pollen drifting through the light like tiny lanterns", p:"dusk"},
{t:"the deep of night during a meteor shower, the sky quietly falling", p:"night"}
],
light: [
{t:"the sun comes through the rain-washed air in visible shafts, and dust hangs in them like plankton", ps:["day"]},
{t:"light pools on the stone floor in the exact shape of the window, with the mullions drawn across it in shadow", ps:["day"]},
{t:"everything facing west is gilded; everything facing east is already dreaming in blue", ps:["dusk"]},
{t:"the light is low enough to rake across every surface, and suddenly you can see the texture of everything", ps:["dawn","dusk"]},
{t:"a single shaft finds the water and turns it into hammered gold, too bright to look at directly", ps:["day"]},
{t:"the clouds are lit from underneath, rose and amber, like coals under ash", ps:["dusk"]},
{t:"shadows stretch impossibly long and thin, calligraphy written across the ground", ps:["dawn","dusk"]},
{t:"the light filters through leaves and throws a thousand green coins onto the path", ps:["day"]},
{t:"the whole scene is lit as if from inside, the way things look in the last minute of sun", ps:["dusk"]},
{t:"moonlight lays a trembling road across the water, broken and mended with every wave", ps:["night"]},
{t:"the fog glows from within, opal-white, and every edge in the world has gone soft", ps:["dawn","day","dusk"]},
{t:"lantern light moves on the ceiling, water-reflected, restless as something alive", ps:["dusk","night"]}
],
materials: [
"old wood, silvered by weather, the grain raised like braille under your fingertips",
"stone worn smooth by water and hands, warm from the day even as the air cools",
"glass, thick and slightly wavy, that bends the world into something kinder",
"water so clear the stones on the bottom look close enough to touch, though they are fathoms down",
"moss like green velvet, springy underfoot, holding the day's rain in a million tiny cups",
"clay tiles, each one a slightly different red, overlapping like the scales of some patient animal",
"copper gone green at the edges, still bright where hands have polished it for years",
"bark peeling in scrolls, revealing the pale new wood underneath like a letter being opened",
"sand so fine it squeaks underfoot, white as paper in the moonlight",
"iron, black and cold, with rust blooming in the crevices like dried flowers",
"feathers, leaves, petals — the light debris of the living world, arranged by wind into drifts"
],
sounds: [
"rain on the roof, steady as breathing, with the occasional deeper note where it hits the skylight",
"water moving over stone — not a roar, a conversation, full of small words you almost understand",
"wind in the high leaves, a sound like the sea heard from very far away",
"a single bird, calling and calling, as if making sure the morning is really happening",
"the creak of old wood as the building settles, like a large animal shifting in sleep",
"distant thunder, too far to fear, just the sky clearing its throat",
"your own footsteps, suddenly loud in the quiet, then the quiet coming back larger than before",
"bees working the flowers, the whole air humming at the edge of hearing",
"a rope creaking, a sail shifting, the small honest sounds of things made by hand",
"silence — not empty, but full: the particular silence of a place that has nothing to prove",
"ice cracking somewhere deep, a clean blue sound like a glass being struck",
"the fire, talking to itself in pops and sighs, in a language older than words"
],
smells: [
"petrichor — rain on hot stone, the smell of the earth exhaling after holding its breath",
"woodsmoke, thin and sweet, from a fire you cannot see",
"cedar and damp bark, the deep green smell of the woods after rain",
"salt air, clean and sharp, with something green underneath",
"wet earth turned over, dark and rich as chocolate",
"jasmine on the night air, so sweet it feels like a hand on your chest",
"old books and beeswax, the smell of a room that has kept its promises",
"citrus blossom, bright as a struck bell",
"the mineral smell of cold water over stone",
"fresh bread from somewhere nearby, impossible and wonderful",
"bracken and leaf-mould, the autumn smell, faintly of smoke and sleep",
"the clean nothing-smell of snow air, cold enough to feel like a taste"
],
air: [
"the air is cool on your face and warm at your back, and you stand in the seam between them",
"the air moves just enough to remind you it is there, lifting the hairs on your arms",
"each breath feels like drinking something — the air has weight and taste here",
"the air is so still you can hear your own heartbeat, and it seems to belong to the place",
"warm air rises off the stone in visible waves, and walking through it feels like wading",
"the air smells of distance — of sea, of mountains, of weather coming",
"a breeze finds the back of your neck like a hand, and is gone",
"the air is cold enough to sharpen everything: colors brighter, sounds closer, you more awake"
],
micro: [
"a spider's web strung between two leaves, beaded with rain, holding a whole miniature rainbow",
"the way the water curls around a single stone, the same curl repeating endlessly, never the same twice",
"a beetle crossing the path, armored and deliberate, on business you will never understand",
"moss growing in the letters of a carved stone, slowly editing what someone wrote a hundred years ago",
"a single feather caught in a cobweb, turning slowly, white against the dark",
"the grain of the wood in the doorframe, flowing like water frozen mid-thought",
"a lizard doing push-ups on a warm rock, utterly committed to its morning",
"raindrops racing down the windowpane, merging, splitting, the tiny drama of it",
"the exact green of new leaves against the old dark ones — two greens that should clash and don't",
"a crack in the stone, and in the crack, a whole garden: moss, a fern, a flower no bigger than a nail",
"your own shadow, stretched long and strange, keeping you company",
"the way dust moves in a shaft of light — not falling, dancing, as if the light were water",
"a shell, perfect and empty, the sea's handwriting",
"frost on the window, ferns of ice growing while you watch",
"the worn dip in the stone step where ten thousand feet have landed, each one a small prayer of arrival",
"a candle flame leaning in a draft, then straightening, then leaning again — deciding",
"water beading on a leaf, each drop holding a tiny upside-down world",
"the sound of your own breath, and then, underneath it, the breathing of the place"
],
craft: [
"the joinery is so tight you cannot slip a fingernail between the boards — no nails, just wood understanding wood",
"someone planed this beam by hand; you can see the long shallow scallops of the plane in the raking light",
"the stone wall is dry-stacked, each stone chosen and turned until it found its neighbors — it has stood a hundred years without mortar",
"the door handle is worn bright where ten thousand hands have taken hold — the metal remembers them",
"a mended bowl, the crack filled with gold: someone loved this enough to make the wound beautiful",
"the thatch is layered thick as a mattress, each reed laid by a hand that knew the wind",
"the window was glazed with old glass, and the world through it ripples gently, like seen through water",
"the steps were cut from a single stone, and the mason left his chisel marks on the risers — signed in texture",
"the quilt on the bench is made of a hundred scraps, each one a story someone chose to keep",
"the gate hangs true on hinges forged by a blacksmith three generations gone, and still swings silent",
"the plaster wall was troweled in arcs; in low light you can read the plasterer's arm moving across it",
"someone swept this courtyard this morning — the broom lines curve like contour lines on a map of care"
],
feelings: [
"your chest feels too small for what is in it, in the best way",
"you laugh once, quietly, at nothing — the laugh of someone who has been given something",
"your shoulders drop an inch; you did not know they were up",
"time stops being a line and becomes a room you are sitting in",
"you feel, suddenly and completely, that you are exactly where you are supposed to be",
"it is the feeling of being forgiven for something you didn't know you carried",
"your eyes sting, and you are not sad — you are full",
"you want to tell someone, and you want to tell no one, both at once",
"the small loud worries of the morning seem to belong to a different person, far away",
"you feel briefly, blindingly, that the world is good — not perfect, good, which is better",
"your breathing slows without you asking it to, the way it does just before sleep, but you are wide awake",
"gratitude arrives uninvited and sits down next to you like an old friend"
],
sky: [
"the sky is washed clean, a blue so deep it feels like looking down instead of up",
"clouds move slowly overhead, lit from below in rose and amber, like coals under ash",
"the sky has gone the color of a pearl held up to lamplight — white, grey, and secretly pink",
"a few high clouds trail across the blue like brushstrokes someone forgot to blend",
"the sky is darkening from the east while the west still burns — you stand under two skies at once",
"stars are coming out one by one, shy at first, then all at once, like guests arriving",
"the clouds have torn open and a single shaft of sun falls through like something lowered on a rope",
"the sky is huge and empty and blue, the kind of blue that makes you feel both tiny and held"
],
ground: [
"the ground under you, springy with moss and old leaves, giving back each step a little",
"the stone underfoot, warm from the day, holding the heat like it intends to keep it",
"the earth under you, dark and soft, smelling faintly of rain that fell hours ago",
"the boards underfoot, worn smooth and silvered, creaking their small honest creak",
"the sand under you, cool now, holding the day's footprints like a guestbook",
"the grass underfoot, thick and cool, beaded with dew that wets your ankles",
"the gravel path under you, crunching softly, each stone placed by some patient hand",
"the bare rock underfoot, ancient and sure, the oldest floor you will ever stand on"
]
};
