/* Human controls and structured AI recipes share the same core and validator. */
(function(){
'use strict';
const E=MoorEffects,$=id=>document.getElementById(id),url=new URLSearchParams(location.search),preview=url.has('preview')||url.has('wonder-preview');if(preview)document.body.classList.add('preview');
const canvas=$('effect-canvas'),draw=E.renderer(canvas);let recipe,compiled,presets=[],selected=0,seed=url.get('seed')||'70429',time=1.3,playing=!matchMedia("(prefers-reduced-motion: reduce)").matches,grid=false,alpha=false,raf=0,last=0,lastPaint=0,lastStat=0,dead=false,pendingBridge=null,currentPreset='',savedId='';
const clone=x=>JSON.parse(JSON.stringify(x)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(text){$('status').textContent=text;}
function rebuild(){E.normalize(recipe);compiled=E.compile(recipe,seed);$('effect-name').textContent=recipe.name;$('time').max=recipe.duration;$('duration').value=recipe.duration;$('variation').value=recipe.variation;$('variation-value').textContent=Math.round(recipe.variation*100)+'%';$('projection').value=recipe.camera.projection;paint();if(!preview)window.dispatchEvent(new CustomEvent('moor:effect-changed'));}
function paint(){if(!compiled||dead)return;const count=draw.draw(compiled,time,{camera:recipe.camera,transparent:alpha&&!preview,grid:grid&&!preview});$('time').value=time%recipe.duration;$('time-label').textContent=(time%recipe.duration).toFixed(2)+' s';if(performance.now()-lastStat>500){$('render-stats').textContent=count+' visible / '+compiled.layers.reduce((n,l)=>n+l.count,0)+' capacity';lastStat=performance.now();}}
function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),size=E.fit(Math.max(1,box.width*dpr),Math.max(1,box.height*dpr));canvas.width=size.width;canvas.height=size.height;paint();}
function loop(now){if(dead)return;raf=requestAnimationFrame(loop);const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(document.hidden)return;if(playing)time=(time+dt)%recipe.duration;if(playing&&now-lastPaint>=1000/E.limits.fps){paint();lastPaint=now;}}
function applyRecipe(input,options={}){const r=E.normalize(typeof input==='string'?JSON.parse(input):input);recipe=r;seed=String(options.seed??seed);$('seed').value=seed;selected=Math.min(selected,r.layers.length-1);time=Number.isFinite(options.time)?Math.max(0,options.time):1.3;rebuild();if(!preview){renderLayers();renderInspector();}return {recipe:clone(recipe),seed,capacity:recipe.layers.reduce((n,l)=>n+l.count,0)};}
function renderLayers(){const list=$('layer-list');list.innerHTML='';recipe.layers.forEach((l,i)=>{const b=document.createElement('button');b.className='layer-card'+(i===selected?' active':'')+(l.enabled?'':' disabled');b.setAttribute('aria-label','Edit '+l.name);b.innerHTML='<b><span class="layer-dot" style="background:hsl('+l.hue+',90%,65%)"></span>'+esc(l.name)+'</b><small>'+esc(l.renderer)+' · '+l.count+'</small><small>'+esc(l.shape)+' → '+esc(l.motion)+'</small>';b.onclick=()=>{selected=i;renderLayers();renderInspector();};list.append(b);});$('layer-count').textContent=recipe.layers.length+' / 8';$('add-layer').disabled=recipe.layers.length>=8;}
function renderInspector(){const l=recipe.layers[selected];$('selected-index').textContent=String(selected+1).padStart(2,'0');const form=$('layer-inspector');
 const isPath=['beam','ribbon','ring'].includes(l.renderer);
 const choice=(key,label)=>'<label>'+label+'<select '+(isPath&&['shape','motion'].includes(key)?'disabled title="Analytic paths use radius, speed, twist and spread" ':'')+'data-field="'+key+'">'+E.enums[key].map(v=>'<option value="'+v+'" '+(l[key]===v?'selected':'')+'>'+v[0].toUpperCase()+v.slice(1)+'</option>').join('')+'</select></label>';
 const range=(key,label,lo,hi,step)=>'<label>'+label+'<output data-value="'+key+'">'+l[key]+'</output><input data-field="'+key+'" type="range" min="'+lo+'" max="'+hi+'" step="'+step+'" value="'+l[key]+'"></label>';
 form.innerHTML='<label>Name<input data-field="name" maxlength="48" value="'+esc(l.name)+'"></label><div class="pair">'+choice('renderer','Output')+choice('shape','Emit from')+'</div><div class="pair">'+choice('motion','Motion')+choice('emission','Emission')+'</div>'+range('count','Capacity',1,isPath?48:1200,1)+range('radius','Radius',0,4,.01)+range('speed','Speed',-4,4,.01)+range('size','Size',.002,.15,.002)+range('hue','Hue',0,360,1)+range('glow','Glow',0,1,.01)+'<details><summary>Timing, motion & transparency</summary>'+range('life','Lifetime',.2,12,.1)+range('delay','Burst delay',0,12,.1)+range('twist','Twist',-5,5,.05)+range('spread','Spread',0,3,.01)+(isPath?'':range('gravity','Gravity',-4,4,.05))+range('hueSpread','Color range',0,180,1)+range('opacity','Opacity',0,1,.01)+choice('blend','Blend')+'<label>Position X / Y / Z</label><div class="position">'+l.position.map((v,i)=>'<input data-position="'+i+'" type="number" aria-label="Position '+['X','Y','Z'][i]+'" min="-5" max="5" step=".1" value="'+v+'">').join('')+'</div></details><details><summary>PNG sprite</summary><p class="muted">Embedded in this recipe · PNG up to 256 KB. Points, sparks and shards can use a sprite.</p><input id="sprite-file" type="file" accept="image/png"><button id="clear-sprite">Clear sprite</button></details><div class="layer-actions"><button id="toggle-layer">'+(l.enabled?'Hide':'Show')+'</button><button id="duplicate-layer">Duplicate</button><button id="remove-layer" '+(recipe.layers.length===1?'disabled':'')+'>Remove</button></div>';
 form.querySelectorAll('[data-field]').forEach(input=>input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>{const key=input.dataset.field,previous=l[key],oldCount=l.count;l[key]=input.type==='range'?Number(input.value):input.value;if(key==='renderer'&&['beam','ribbon','ring'].includes(l.renderer))l.count=Math.min(l.count,48);try{rebuild();const output=form.querySelector('[data-value="'+key+'"]');if(output)output.textContent=l[key];renderLayers();if(key==='renderer')renderInspector();}catch(e){l[key]=previous;l.count=oldCount;input.value=previous;notice(e.message);}}));
 form.querySelectorAll('[data-position]').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.position),old=l.position[i];l.position[i]=Number(input.value);try{rebuild();}catch(e){l.position[i]=old;input.value=old;notice(e.message);}});
 $('toggle-layer').onclick=()=>{l.enabled=!l.enabled;rebuild();renderLayers();renderInspector();};
 $('duplicate-layer').onclick=()=>{try{const next=clone(recipe);const copy=clone(next.layers[selected]);copy.id='layer-'+crypto.randomUUID().slice(0,8);copy.name+=' copy';next.layers.push(copy);E.normalize(next);recipe=next;selected=next.layers.length-1;rebuild();renderLayers();renderInspector();}catch(e){notice(e.message);}};
 $('remove-layer').onclick=()=>{if(recipe.layers.length<2)return;recipe.layers.splice(selected,1);selected=Math.max(0,selected-1);rebuild();renderLayers();renderInspector();};
 $('sprite-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>256*1024||f.type!=='image/png')throw Error('Use a PNG under 256 KB');const bytes=new Uint8Array(await f.arrayBuffer());if(![137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))throw Error('Invalid PNG');let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const src='data:image/png;base64,'+btoa(binary);const probe=new Image();probe.src=src;await probe.decode();if(probe.width*probe.height>4194304)throw Error('Sprite exceeds 4 megapixels');l.sprite=src;rebuild();notice('PNG sprite embedded in recipe');}catch(e){notice(e.message);}};
 $('clear-sprite').onclick=()=>{l.sprite=null;rebuild();};
}
function download(name,blob){const link=document.createElement('a'),object=URL.createObjectURL(blob);link.href=object;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(object),10000);}
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,'').slice(0,44)||'effect';
async function png(){const cv=document.createElement('canvas'),size=E.fit(canvas.width*2,canvas.height*2,4194304);cv.width=size.width;cv.height=size.height;const r=E.renderer(cv);await r.prepare(compiled);r.draw(compiled,time,{transparent:true,camera:recipe.camera});const blob=await new Promise(resolve=>cv.toBlob(resolve,'image/png'));r.dispose();if(!blob)throw Error('PNG export failed');download(slug(recipe.name)+'-'+slug(seed)+'.png',blob);window.dispatchEvent(new CustomEvent('moor:effect-exported'));notice('Transparent PNG exported at '+cv.width+' × '+cv.height);return {width:cv.width,height:cv.height,seed,time};}
async function flipbook(){const n=24,cols=6,rows=4,cell=256,cv=document.createElement('canvas');cv.width=cell*cols;cv.height=cell*rows;const tile=document.createElement('canvas');tile.width=tile.height=cell;const r=E.renderer(tile),ctx=cv.getContext('2d');await r.prepare(compiled);for(let i=0;i<n;i++){r.draw(compiled,i/n*recipe.duration,{transparent:true,camera:recipe.camera});ctx.drawImage(tile,(i%cols)*cell,Math.floor(i/cols)*cell);}r.dispose();const blob=await new Promise(resolve=>cv.toBlob(resolve,'image/png'));if(!blob)throw Error('Flipbook export failed');download(slug(recipe.name)+'-flipbook.png',blob);download(slug(recipe.name)+'-flipbook.json',new Blob([JSON.stringify({schema:'moor.effect-flipbook',version:1,columns:cols,rows,frameWidth:cell,frameHeight:cell,frames:n,duration:recipe.duration,seed,recipe},null,2)],{type:'application/json'}));window.dispatchEvent(new CustomEvent('moor:effect-exported'));notice('24-frame transparent flipbook and replay metadata exported');return {frames:n,columns:cols,rows};}
async function saveGenerator(options){const rec=await EffectsLibrary.save(options.id,options.name,recipe);savedId=rec.id;await renderSaved();notice('Saved '+rec.name+' · joined Wonder Feed');return {id:rec.id,feedKind:'native-fx-'+rec.id,bytes:JSON.stringify(rec.recipe).length};}
async function renderSaved(){try{const items=await EffectsLibrary.list();$('saved-generators').replaceChildren();if(!items.length)$('saved-generators').innerHTML='<p class="muted">Saved on this device.</p>';for(const rec of items){const b=document.createElement('button');b.className='saved-generator';b.textContent=rec.name;b.onclick=()=>{savedId=rec.id;currentPreset='';applyRecipe(rec.recipe);setPresetState();notice('Editing '+rec.name);};$('saved-generators').append(b);}}catch(e){notice('Device storage unavailable · recipes can still be downloaded');}}
function setPresetState(){document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===currentPreset));}
function setTime(v){time=Number(v);if(!Number.isFinite(time)||time<0)throw Error('Invalid time');time%=recipe.duration;paint();return {time};}
function pause(){playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play animation');return {playing};}
window.EffectsStudio={version:1,pause,getRecipe:()=>({recipe:clone(recipe),seed,time}),applyRecipe,sample:(at=time)=>E.sample(compiled,at).map(g=>({layer:g.layer.id,elements:g.elements})),setTime,saveGenerator,exportPNG:png,exportFlipbook:flipbook,stats:()=>({capacity:recipe?.layers.reduce((n,l)=>n+l.count,0),canvasPixels:canvas.width*canvas.height,storagePolicy:'explicit generator saves only',...draw.stats()})};
window.WonderPreview={canvas:()=>canvas,setRecipe(args){pendingBridge=args;if(!recipe)return;applyRecipe(args.params?.recipe||recipe,{seed:args.seed,time:1.3});},dispose(){dispose();}};
function dispose(){if(dead)return;dead=true;cancelAnimationFrame(raf);ro.disconnect();draw.dispose();document.removeEventListener('visibilitychange',visibility);}
window.addEventListener('pagehide',dispose,{once:true});const ro=new ResizeObserver(resize);ro.observe(canvas);const visibility=()=>{last=0;if(!document.hidden)paint();};document.addEventListener('visibilitychange',visibility);
$('seed').value=seed;$('seed').onchange=e=>{seed=e.target.value;rebuild();};$('new-seed').onclick=()=>{seed=String(crypto.getRandomValues(new Uint32Array(1))[0]);$('seed').value=seed;rebuild();};
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'Pause animation':'Play animation');};$('restart').onclick=()=>{time=0;paint();};$('time').oninput=e=>{playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play animation');setTime(Number(e.target.value));};
$('duration').onchange=e=>{const old=recipe.duration;recipe.duration=Number(e.target.value);try{rebuild();}catch(err){recipe.duration=old;e.target.value=old;notice(err.message);}};$('variation').oninput=e=>{recipe.variation=Number(e.target.value);rebuild();};
$('grid').onclick=()=>{grid=!grid;$('grid').setAttribute('aria-pressed',String(grid));paint();};$('background').onclick=()=>{alpha=!alpha;$('background').setAttribute('aria-pressed',String(alpha));document.querySelector('.viewport').classList.toggle('alpha',alpha);paint();};
$('projection').onchange=e=>{recipe.camera.projection=e.target.value;paint();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{Object.assign(recipe.camera,b.dataset.view==='front'?{yaw:0,pitch:0}:b.dataset.view==='top'?{yaw:0,pitch:Math.PI/2}:{yaw:.65,pitch:-.35});document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));paint();});
let dragging=null;canvas.onpointerdown=e=>{dragging={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!dragging)return;recipe.camera.yaw=((recipe.camera.yaw+(e.clientX-dragging.x)*.008+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;recipe.camera.pitch=Math.max(-1.5,Math.min(1.5,recipe.camera.pitch+(e.clientY-dragging.y)*.008));dragging={x:e.clientX,y:e.clientY};paint();};canvas.onpointerup=canvas.onpointercancel=()=>dragging=null;canvas.addEventListener('wheel',e=>{e.preventDefault();recipe.camera.zoom=Math.max(.3,Math.min(3,recipe.camera.zoom*Math.exp(-e.deltaY*.001)));paint();},{passive:false});
$('add-layer').onclick=()=>{try{const next=clone(recipe);next.layers.push({...E.defaults,count:100,id:'layer-'+crypto.randomUUID().slice(0,8),name:'New emitter'});E.normalize(next);recipe=next;selected=next.layers.length-1;rebuild();renderLayers();renderInspector();}catch(e){notice(e.message);}};
$('recipe-open').onclick=()=>{$('recipe-json').value=JSON.stringify(recipe,null,2);$('recipe-dialog').showModal();};$('apply-recipe').onclick=()=>{try{applyRecipe($('recipe-json').value);$('recipe-dialog').close();notice('Recipe applied');}catch(e){notice(e.message);}};$('download-recipe').onclick=()=>download(slug(recipe.name)+'.effect.json',new Blob([JSON.stringify({recipe,seed,time},null,2)],{type:'application/json'}));$('import-recipe').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>400*1024)throw Error('File exceeds 400 KB');const obj=JSON.parse(await f.text());applyRecipe(obj.recipe||obj,{seed:obj.seed,time:obj.time});$('recipe-json').value=JSON.stringify(recipe,null,2);notice('Recipe imported');}catch(err){notice(err.message);}};
$('export-png').onclick=()=>png().catch(e=>notice(e.message));$('flipbook').onclick=()=>flipbook().catch(e=>notice(e.message));$('save-generator').onclick=()=>{$('generator-name').value=recipe.name;$('generator-id').value=savedId||slug(recipe.name)+'-custom';$('save-size').textContent=(JSON.stringify(recipe).length/1024).toFixed(1)+' KB recipe · no rendered frames stored';$('save-dialog').showModal();};$('close-save').onclick=()=>$('save-dialog').close();$('save-form').onsubmit=async e=>{e.preventDefault();try{await saveGenerator({id:$('generator-id').value,name:$('generator-name').value});$('save-dialog').close();}catch(err){notice(err.message);}};
function registerAITools(){
 const context=document.modelContext||navigator.modelContext;if(preview||!context?.registerTool)return;
 const result=x=>({content:[{type:'text',text:JSON.stringify(x)}]});
 const definitions=[
 {name:'effects_get_recipe',description:'Read the current Effects Studio recipe, seed and time.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:async()=>result(EffectsStudio.getRecipe())},
 {name:'effects_apply_recipe',description:'Apply a validated moor.effect-recipe v1. Edits the preview without saving.',inputSchema:{type:'object',properties:{recipe:{type:'object'},seed:{type:'string'},time:{type:'number',minimum:0}},required:['recipe']},execute:async args=>result(applyRecipe(args.recipe,{seed:args.seed,time:args.time}))},
 {name:'effects_sample',description:'Inspect deterministic 3D geometry at a given time. Returns at most 24 elements per layer.',inputSchema:{type:'object',properties:{time:{type:'number',minimum:0}}},annotations:{readOnlyHint:true},execute:async args=>result(EffectsStudio.sample(args.time??time).map(g=>({layer:g.layer,total:g.elements.length,elements:g.elements.slice(0,24)})))},
 {name:'effects_set_time',description:'Scrub the effects preview to a reproducible time and pause playback.',inputSchema:{type:'object',properties:{time:{type:'number',minimum:0}},required:['time']},execute:async args=>{playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play animation');return result(setTime(args.time));}},
 {name:'effects_save_generator',description:'Explicitly save the current recipe as a device-local generator and register it in Wonder Feed. Reusing the same ID replaces the generator recipe.',inputSchema:{type:'object',properties:{id:{type:'string',pattern:'^[a-z0-9-]+$'},name:{type:'string'}},required:['id','name']},execute:async args=>result(await saveGenerator(args))}
 ];for(const definition of definitions){try{Promise.resolve(context.registerTool(definition)).catch(()=>{});}catch(_){}}
}
(async()=>{try{const response=await fetch('effects/presets.json?v=20261006-fx1');if(!response.ok)throw Error('Example library unavailable');presets=(await response.json()).presets;let initial=presets.find(p=>p.id===url.get('preset'))||presets[0];currentPreset=initial.id;
 if(url.get('generator')){const rec=(await EffectsLibrary.list()).find(x=>x.id===url.get('generator'));if(rec){initial={id:rec.id,recipe:rec.recipe};savedId=rec.id;currentPreset='';}else if(!pendingBridge?.params?.recipe)throw Error('Generator is not on this device');}
 recipe=E.normalize(pendingBridge?.params?.recipe||initial.recipe);seed=String(pendingBridge?.seed??seed);$('seed').value=seed;rebuild();resize();
 if(!preview){for(const p of presets){const b=document.createElement('button');b.className='preset';b.dataset.preset=p.id;b.style.setProperty('--accent',p.accent);b.innerHTML='<span class="swatch">✦</span><span>'+esc(p.label)+'<small>'+p.recipe.layers.length+' emitter layers</small></span>';b.onclick=()=>{currentPreset=p.id;savedId='';selected=0;applyRecipe(p.recipe);setPresetState();};$('presets').append(b);}setPresetState();renderLayers();renderInspector();renderSaved();}
 registerAITools();if(!playing)pause();raf=requestAnimationFrame(loop);notice('Ready · '+recipe.name);
 }catch(e){notice(e.message);document.querySelector('.viewport').setAttribute('data-error',e.message);}})();
})();

