/* Wonder Logic v1: bounded, seeded idea recipes. Schematics are previews, not implemented integrations. */
(function(root){'use strict';
function hash(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(a){return function(){a|=0;a=a+0x6D2B79F5|0;var t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
var kits=[
 {name:'Living terrain',parts:['terrain-core','planet-vegetation'],view:'garden',input:'height, slope, moisture proxy',output:'seeded plant placement',step:'Add a habitat score before the vegetation scatter pass.',rules:[['Gardens follow water','moisture > {q}','Place plants only near the wet band.'],['Forests avoid cliffs','slope < {q}','Reject steep sites before generating any mesh.'],['A canopy with breathing room','nearestPlantDistance > {n}','Reserve a minimum radius around each plant.'],['A forest that reveals the route','distanceToPath > {n}','Keep the walking corridor clear; thicken the edges.']]},
 {name:'Trail signals',parts:['terrain-field','particle-pack'],view:'network',input:'height samples, path distance',output:'particle spawn intensity',step:'Sample one terrain/path signal and map it into a particle emitter.',rules:[['Ridges light up at dusk','ridgeScore > {q}','Emit small lights only along high ridges.'],['A trail that answers your steps','distanceToPlayer < {n}','Activate trail particles as the player approaches.'],['Hazards give you a warning','slope > {q}','Make steep areas spark before you walk into them.'],['A shoreline made of fireflies','abs(height-waterLevel) < {n}','Scatter glowing particles along the shoreline band.']]},
 {name:'Dungeon pacing',parts:['comp-maze','spawn-director'],view:'rooms',input:'maze cells, route progress',output:'encounter budget per cell',step:'Build a maze-cell adapter that gives the spawn director a local budget.',rules:[['Dead ends hide the reward','neighborCount = 1','Reserve dead ends for discoveries rather than routine fights.'],['Quiet rooms before a fight','encountersSinceRest > {n}','Insert a zero-spawn refuge after the encounter limit.'],['The maze pushes back','routeProgress > {q}','Raise the encounter budget deeper along the route.'],['A maze that changes the rhythm','cellIndex mod {n} = 0','Alternate combat pockets and empty traversal cells.']]},
 {name:'Habitat creatures',parts:['planet-vegetation','softbody-creatures'],view:'garden',input:'plant density, habitat samples',output:'creature spawn weights',step:'Create a habitat adapter; leave the existing creature genome builder intact.',rules:[['Foragers follow the canopy','plantDensity > {q}','Spawn foragers in dense vegetation pockets.'],['A creature that guards one grove','distanceToGrove < {n}','Tie its patrol radius to one seeded grove.'],['The food chain leaves a gap','plantDensity < {q}','Use sparse clearings for roaming predators.'],['The ecosystem has safe edges','distanceToHome < {n}','Lower hostile spawn weights around the home edge.']]},
 {name:'Motion becomes sound',parts:['vehicle-physics','ambience-engine'],view:'signal',input:'vehicle speed, acceleration',output:'audio gain and filter values',step:'Read physics telemetry through an adapter; smooth the mapped audio control.',rules:[['The world hums as you accelerate','speed/maxSpeed > {q}','Blend the ambient bed toward a brighter filter at speed.'],['A corner you can hear','abs(turnRate) > {q}','Bring up a soft layer during sharp turns.'],['Rain listens to the engine','acceleration > {q}','Modulate rain-layer gain with a bounded acceleration signal.'],['Silence when you stop','speed < {n}','Fade the motion layer out below the speed threshold.']]},
 {name:'Collectible grammar',parts:['mesh-builder','palettes'],view:'rooms',input:'item seed, rarity tier',output:'mesh parameters and palette',step:'Build one seeded item function returning geometry parameters and a palette ID.',rules:[['A collection with a family resemblance','rarityTier mod {n}','Keep the silhouette family; vary its palette by rarity.'],['You can read the loot from afar','rarity/maxRarity > {q}','Scale one outline feature with rarity.'],['Every district grows a different relic','hash(districtSeed) mod {n}','Use the district seed to choose a geometry family.'],['A relic keeps its ancestry','parentSeed xor variantSeed','Derive mutations from the original item seed.']]},
 {name:'Personal continuity',parts:['seed-codec','save-shape'],view:'network',input:'versioned recipe, seed',output:'portable saved state',step:'Pass the minimal recipe through the codec; restore it through the save-shape adapter.',rules:[['A place that fits in a code','decode(encode(recipe)) = recipe','Rebuild the same small space from a portable recipe.'],['Remix without losing the original','child.seed = hash(parentSeed, {n})','Store parent provenance before changing a recipe.'],['One room, several moods','presetIndex mod {n}','Save alternate scene recipes while keeping the room identity.'],['A pocket world that comes home','worldVersion = 1','Restore one room and its settings after closing the app.']]},
 {name:'World navigation',parts:['moorworld','comp-billboards'],view:'network',input:'world directory, distance',output:'destination display records',step:'Adapt directory entries into display records with explicit destination IDs.',rules:[['A sign that knows where you are','distanceToDestination < {n}','Show nearby destinations before distant ones.'],['The hub changes with your journey','visitedCount > {n}','Prioritize worlds you have not visited yet.'],['Doors reveal a world before you enter','previewSeed = hash(destinationId)','Give each destination a reproducible preview signature.'],['A quiet route through the universe','crowdProxy < {q}','Filter destinations by a supplied crowd estimate.']]}
];
var scenes=['a mossy courtyard','flooded ruins','a glass district','a sky island','a midnight workshop','a desert caravan','an abandoned station','a private pocket world'];
function index(v,n){return ((Math.floor(Number(v)||0)%n)+n)%n;}
function plan(g){var p=g.p||{},k=kits[index(p.kit,kits.length)],rule=k.rules[index(p.op,4)],r=rng(hash('wonder-logic-v1|'+g.seed+'|'+JSON.stringify(p))),n=2+Math.floor(r()*11),q=(.15+r()*.7).toFixed(2),scene=scenes[index(p.scene,scenes.length)],count=8+index(p.density,5)*6;
 var expression=rule[1].replace(/\{n\}/g,String(n)).replace(/\{q\}/g,q);
 var out={version:1,seed:g.seed>>>0,title:rule[0]+' / '+scene,rule:expression,behavior:rule[2],parts:k.parts.slice(),input:k.input,output:k.output,step:k.step,scene:scene,view:k.view,count:count,n:n,q:Number(q),hue:155+Math.floor(r()*140),nodes:[]};
 for(var i=0;i<count;i++)out.nodes.push({x:.06+r()*.88,y:.12+r()*.76,value:r(),size:2+r()*5});
 out.check='Same seed and settings must reproduce the same result. Test values immediately below and above the threshold; verify the output changes only where the rule allows.';
 if(expression.indexOf('decode(')===0)out.check='Round-trip the recipe through encode/decode, close and restore it, then compare every serialized field.';
 if(expression.indexOf('hash(')>=0||expression.indexOf('Seed')>=0||expression.indexOf('worldVersion')>=0)out.check='Reload the saved recipe twice and compare outputs. Change one seed or preset and confirm a distinct reproducible variant.';
 out.brief=['Implement a small MOOR component experiment: '+out.title,'Idea recipe v1; seed '+out.seed+'. This is a proposal, not an existing integration.','Parts: '+out.parts.join(' + '),'Input: '+out.input,'Rule: '+out.rule,'Output: '+out.output,'Behavior: '+out.behavior,'First change: '+out.step,'Check: '+out.check,'Preserve the original parts; add explicit adapters. Preview one result before expanding scope.'].join('\n');return out;
}
function draw(cv,p,elapsed){var c=cv.getContext('2d'),W=cv.width,H=cv.height,t=elapsed||0;c.clearRect(0,0,W,H);c.fillStyle='#09111e';c.fillRect(0,0,W,H);c.lineWidth=1;c.strokeStyle='hsla('+p.hue+',70%,65%,.14)';for(var x=0;x<W;x+=W/16){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke();}for(var y=0;y<H;y+=H/5){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke();}
 var threshold=p.q,phase=(t*.08)%1;
 if(p.view==='signal'){c.strokeStyle='hsla('+p.hue+',75%,70%,.3)';c.beginPath();c.moveTo(0,H*(1-threshold));c.lineTo(W,H*(1-threshold));c.stroke();c.lineWidth=3;c.strokeStyle='hsl('+p.hue+',85%,74%)';c.beginPath();for(var i=0;i<120;i++){var sx=i/119,signal=.5+.3*Math.sin(sx*p.n*2+t),yy=H*(.85-.65*signal);if(!i)c.moveTo(sx*W,yy);else c.lineTo(sx*W,yy);}c.stroke();}
 p.nodes.forEach(function(a,i){var px=a.x*W,py=a.y*H,active=a.value>=threshold;c.fillStyle=active?'hsl('+p.hue+',80%,72%)':'#324157';c.strokeStyle=active?'hsla('+p.hue+',75%,70%,.45)':'#243044';
 if(p.view==='network'){var b=p.nodes[(i+1)%p.nodes.length];c.beginPath();c.moveTo(px,py);c.lineTo(b.x*W,b.y*H);c.stroke();var travel=(phase+i/p.count)%1;c.fillRect(px+(b.x*W-px)*travel-2,py+(b.y*H-py)*travel-2,4,4);}
 if(p.view==='rooms'){var size=a.size*3;c.strokeRect(px-size,py-size,size*2,size*2);if(active)c.fillRect(px-3,py-3,6,6);}
 else if(p.view==='garden'){c.beginPath();c.moveTo(px,py+12);c.lineTo(px,py-3);c.stroke();c.beginPath();c.ellipse(px,py-6,a.size*2,a.size*3,Math.sin(t+i)*.15,0,Math.PI*2);c.fill();}
 else if(p.view==='network'){c.beginPath();c.arc(px,py,a.size,0,Math.PI*2);c.fill();}
 });c.fillStyle='#a3b2ca';c.font='14px monospace';c.fillText('SEEDED SCHEMATIC / '+p.view.toUpperCase(),14,H-15);
}
root.WonderLogic={version:1,kits:kits,scenes:scenes,plan:plan,draw:draw};
})(typeof window!=='undefined'?window:globalThis);
