// Molten Studio — application: state, presets, WebGL scene, controls, export hooks.
// Ported verbatim from molten.html (block 3); the x-shader <script> tags are now imports.
'use strict';
import { VERT_SRC, SCENE_SRC, POST_SRC } from './shaders.js';
const SHADER_SRC = { 'vertex-shader': VERT_SRC, 'scene-shader': SCENE_SRC, 'post-shader': POST_SRC };
const $=id=>document.getElementById(id),TAU=Math.PI*2;
const defaults={shape:0,view:0,wax:'#ff421d',hot:'#ffb13b',liquid:'#673545',back:'#15121a',metal:0,background:1,glow:.82,gloss:.75,iridescence:.16,marble:.18,lightAngle:-.64,lightHeight:3.2,translucence:.68,glass:1,exposure:1.1,halo:1,grain:.16,floor:true,zoom:1,yaw:.12,pitch:.02,count:13,size:1,merge:.25,warp:.45,softness:.65,spread:.88,speed:1,motion:0,seed:271828,loop:true,cycle:60,orbit:false,quality:1,adaptive:true,heat:.55,preset:0};
const presets=[
 {name:'Ember',title:'Ember & obsidian',sub:'Warm wax. Midnight glass.',wax:'#ff421d',hot:'#ffb13b',liquid:'#673545',back:'#15121a',metal:0,shape:0},
 {name:'Aurora',title:'Northern lights',sub:'Arctic jade in a violet night.',wax:'#18efb0',hot:'#d3ffe0',liquid:'#5744ac',back:'#091426',metal:1,shape:1},
 {name:'Ultraviolet',title:'After the afterglow',sub:'Electric violet. Soft pink heat.',wax:'#a247ff',hot:'#ff75dd',liquid:'#213b9a',back:'#120d20',metal:1,shape:0},
 {name:'Honey',title:'The golden hour',sub:'Liquid amber, held in warm light.',wax:'#e77a09',hot:'#ffe49c',liquid:'#67301b',back:'#231911',metal:2,shape:2},
 {name:'Lagoon',title:'Somewhere below',sub:'A slow tide of luminous blue.',wax:'#169bdc',hot:'#a2fff4',liquid:'#204867',back:'#0a1820',metal:1,shape:1},
 {name:'Rosewater',title:'Rose-colored time',sub:'Silk, blush, and a little daydream.',wax:'#f86092',hot:'#ffdcc2',liquid:'#613959',back:'#21161f',metal:3,shape:3},
 {name:'Acid',title:'Midnight greenhouse',sub:'Radioactive lime. Botanical darkness.',wax:'#a1e717',hot:'#edff96',liquid:'#26565a',back:'#101c16',metal:0,shape:1},
 {name:'Pearl',title:'A softer gravity',sub:'Moonlit ivory in a cool blue haze.',wax:'#b8cee4',hot:'#fff2df',liquid:'#354e7e',back:'#101723',metal:1,shape:2},
 {name:'Inferno',title:'Heart of the furnace',sub:'Crimson wax with a molten gold core.',wax:'#b60b26',hot:'#ff761a',liquid:'#432241',back:'#180d14',metal:3,shape:0},
 {name:'Deep space',title:'Dark matter',sub:'A weightless constellation of liquid.',wax:'#5268ff',hot:'#ed4fff',liquid:'#37297c',back:'#070b1c',metal:0,shape:2,motion:2,background:2},
 {name:'Tangerine',title:'Orange crush',sub:'A little piece of the seventies.',wax:'#ff851d',hot:'#fff1a6',liquid:'#36369a',back:'#171326',metal:2,shape:0},
 {name:'Black cherry',title:'Velvet underground',sub:'Black cherry wax. Copper reflections.',wax:'#ab214f',hot:'#fb8a76',liquid:'#533643',back:'#190f18',metal:3,shape:3}
];
const ranges={iridescence:[0,1,.01],marble:[0,1,.01],lightAngle:[-Math.PI,Math.PI,.01],lightHeight:[-3,6,.01],glow:[0,3,.01],gloss:[0,1,.01],translucence:[0,1,.01],glass:[0,2,.01],exposure:[.35,2.8,.01],halo:[0,3,.01],grain:[0,1,.01],zoom:[.5,2.6,.01],yaw:[-Math.PI,Math.PI,.01],pitch:[-.55,.75,.01],count:[4,24,1],size:[.5,1.65,.01],merge:[.06,.65,.01],warp:[0,1.5,.01],softness:[0,1.5,.01],spread:[.2,1,.01],speed:[.15,3,.01],heat:[0,1,.01],seed:[1,999999,1],cycle:[10,3600,1],shape:[0,3,1],view:[0,2,1],metal:[0,3,1],background:[0,3,1],quality:[0,3,1],motion:[0,2,1],preset:[-1,11,1]};
let state={...defaults};
function validate(obj){if(!obj||typeof obj!=='object'||Array.isArray(obj))throw Error('This recipe is not an object.');const out={...defaults};for(const k in defaults){if(!(k in obj))continue;const v=obj[k];if(ranges[k]){const[a,b,s]=ranges[k];if(typeof v!=='number'||!Number.isFinite(v)||v<a||v>b)throw Error('Invalid '+k+' in recipe.');out[k]=s===1?Math.round(v):v;}else if(typeof defaults[k]==='boolean'){if(typeof v!=='boolean')throw Error('Invalid '+k+' in recipe.');out[k]=v;}else if(typeof defaults[k]==='string'){if(typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid color in recipe.');out[k]=v;}}return out;}
try{const stored=localStorage.getItem('molten-studio-v1');if(stored)state=validate(JSON.parse(stored));}catch(e){}
let playing=true,elapsed=0,last=0,lastRender=0,frameCount=0,fpsStart=0,actualFPS=0,scale=.7,heatPulse=0,toastTimer,saveTimer,blobs=[],resizeNeeded=true,rmFboW=0,rmFboH=0;
const canvas=$('scene');const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
function fail(s){$('error-panel').style.display='grid';$('error-text').textContent=s;const lbl=$('engine-label');if(lbl)lbl.textContent='Renderer unavailable';}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('molten-studio-v1',JSON.stringify(state));}catch(e){}},400);}
function buildBlobs(){let a=state.seed>>>0;const rand=()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};blobs=Array.from({length:24},(_,i)=>({phase:rand()*TAU,phase2:rand()*TAU,rad:.145+rand()*.18,orbit:.22+rand()*.7,lane:rand()*TAU,harm:1+Math.floor(rand()*2),weight:rand()}));}
function sync(){const p=presets[state.preset];$('scene-title').textContent=p?p.title:'Your own atmosphere';$('scene-subtitle').textContent=p?p.sub:'A composition that only exists here.';$('scene-number').textContent=state.preset>=0?String(state.preset+1).padStart(2,'0'):'∞';}
function update(k,v,custom=true){if(ranges[k]){const[a,b,s]=ranges[k];v=Math.max(a,Math.min(b,+v));if(!Number.isFinite(v)){sync();return;}if(s===1)v=Math.round(v);}state[k]=v;if(custom&&['wax','hot','liquid','back','shape','metal','background'].includes(k))state.preset=-1;if(k==='seed')buildBlobs();if(k==='quality'){scale=[.5,.7,.9,1][state.quality];resizeNeeded=true;}sync();save();}
function applyPreset(i){const keep={quality:state.quality,adaptive:state.adaptive,view:state.view};state={...defaults,...presets[i],...keep,preset:i};for(const k of ['name','title','sub'])delete state[k];elapsed=0;heatPulse=0;buildBlobs();sync();save();}
let pointer=null;canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;state.yaw+=((e.clientX-pointer.x)*.007);state.yaw=((state.yaw+Math.PI)%TAU+TAU)%TAU-Math.PI;state.pitch=Math.max(-.55,Math.min(.75,state.pitch+(e.clientY-pointer.y)*.004));pointer.x=e.clientX;pointer.y=e.clientY;sync();save();});const release=()=>pointer=null;canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();update('zoom',state.zoom*Math.exp(-e.deltaY*.001),false);},{passive:false});canvas.addEventListener('dblclick',()=>{if(window.SeedConsole)window.SeedConsole.toggleChrome();});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
if(!gl){fail('This renderer needs WebGL 2. Open this file in an up-to-date Chrome or Edge browser with hardware acceleration enabled.');buildBlobs();sync();}
else boot:{ // (was: IIFE body; its early-returns are now `break boot;`)
let sceneProgram,postProgram,texture,framebuffer;const uniforms={};
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const info=gl.getShaderInfoLog(s);gl.deleteShader(s);throw Error(info);}return s;}
function program(fs){const p=gl.createProgram(),v=shader(gl.VERTEX_SHADER,SHADER_SRC['vertex-shader']),f=shader(gl.FRAGMENT_SHADER,SHADER_SRC[fs]);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
try{sceneProgram=program('scene-shader');postProgram=program('post-shader');for(const p of [sceneProgram,postProgram]){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);let a=gl.getAttribLocation(p,'aPosition');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);p.vao=vao;uniforms[p===sceneProgram?'scene':'post']={};const dict=uniforms[p===sceneProgram?'scene':'post'];for(let i=0;i<gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS);i++){const u=gl.getActiveUniform(p,i);dict[u.name.replace('[0]','')]=gl.getUniformLocation(p,u.name);}}texture=gl.createTexture();framebuffer=gl.createFramebuffer();}catch(e){console.error(e);fail('The graphics driver could not start the renderer. Try Chrome or Edge with hardware acceleration on.');buildBlobs();sync();break boot;}
const hex=c=>[1,3,5].map(i=>Math.pow(parseInt(c.slice(i,i+2),16)/255,2.2));
function resize(w,h){const RM0=window.__renderMode;if(RM0){w=RM0.W;h=RM0.H;}if(!w){const rect=canvas.getBoundingClientRect();let dpr=Math.min(devicePixelRatio||1,1.5);w=Math.max(2,Math.round(rect.width*dpr*scale));h=Math.max(2,Math.round(rect.height*dpr*scale));}const max=gl.getParameter(gl.MAX_TEXTURE_SIZE);if(w>max||h>max)throw Error('These dimensions exceed your graphics limit. Choose a smaller resolution.');if(canvas.width===w&&canvas.height===h){if(!RM0||(rmFboW===w&&rmFboH===h)){resizeNeeded=false;return;}}canvas.width=w;canvas.height=h;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Not enough graphics memory for this size. Choose a lower resolution.');gl.bindFramebuffer(gl.FRAMEBUFFER,null);rmFboW=w;rmFboH=h;resizeNeeded=false;}
const blobData=new Float32Array(24*4);
function motionAt(time){const phase=state.loop?((time*state.speed)%state.cycle)/state.cycle*TAU:time*.045*state.speed;const harmonic=1;const pulse=heatPulse;for(let i=0;i<24;i++){const b=blobs[i];const t=phase*(state.loop?b.harm*harmonic:1+b.weight*.9)+b.phase;const wave=Math.sin(t);const y=1.38*wave+Math.sin(t*2.+b.phase2)*.10;let r=b.rad*state.size*(1+pulse*.25);let width=state.shape===2?Math.sqrt(Math.max(.1,1-(y/1.95)**2))*1.39:state.shape===0?.86-(y+1.9)/3.8*.40:state.shape===1?.75:.52+.35*Math.pow(Math.abs(y)/1.9,1.25);width=Math.max(.05,width-r-.13);let x=Math.sin(t*.0+phase*(state.loop?harmonic:1.21)+b.lane)*width*b.orbit*state.spread;let z=Math.cos(phase*(state.loop?harmonic:1.07)+b.lane)*width*b.orbit*state.spread;
let yy=y*(.67+state.heat*.42)+pulse*.16*Math.cos(b.phase);if(state.motion===1){x=Math.cos(t)*width*.82;z=Math.sin(t)*width*.82;yy=Math.sin(t+b.phase2)*1.30;}else if(state.motion===2){x=Math.cos(t)*width;z=Math.sin(t*2.+b.phase2)*width;yy=Math.sin(t+b.lane)*1.35;}
if(state.view>0){x*=state.view===1?4.6:3.6;z*=2.1;yy*=state.view===1?1.8:1.6;r*=state.view===1?1.62:1.7;}
blobData[i*4]=x;blobData[i*4+1]=yy;blobData[i*4+2]=z;blobData[i*4+3]=r;
}return phase;}
function render(time){if(gl.isContextLost())return;const phase=motionAt(time);const breathe=state.glow*(1+.03*Math.sin(phase*3));gl.viewport(0,0,canvas.width,canvas.height);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.useProgram(sceneProgram);gl.bindVertexArray(sceneProgram.vao);const u=uniforms.scene;const f=(key,v)=>{if(u[key]!=null)gl.uniform1f(u[key],v);};const int=(key,v)=>{if(u[key]!=null)gl.uniform1i(u[key],v);};gl.uniform2f(u.uRes,canvas.width,canvas.height);gl.uniform4fv(u.uBlobs,blobData);int('uCount',state.count);int('uShape',state.shape);int('uView',state.view);int('uBackground',state.background);int('uMetal',state.metal);int('uSteps',[64,84,104,128][state.quality]);for(const[k,s]of [['uWax','wax'],['uHot','hot'],['uLiquid','liquid'],['uBack','back']])gl.uniform3fv(u[k],hex(state[s]));for(const[k,s]of [['uMerge','merge'],['uWarp','warp'],['uGloss','gloss'],['uTranslucence','translucence'],['uGlass','glass'],['uExposure','exposure'],['uHalo','halo'],['uZoom','zoom'],['uPitch','pitch'],['uGrain','grain'],['uSoftness','softness'],['uSpread','spread'],['uIridescence','iridescence'],['uMarble','marble'],['uLightAngle','lightAngle'],['uLightHeight','lightHeight']])f(k,state[s]);f('uGlow',breathe);f('uTime',phase);f('uYaw',state.yaw+(state.orbit?Math.sin(phase)*.28:0));f('uFloor',state.floor?1:0);f('uPulse',heatPulse);gl.drawArrays(gl.TRIANGLES,0,3);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.useProgram(postProgram);gl.bindVertexArray(postProgram.vao);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(uniforms.post.uImage,0);gl.uniform2f(uniforms.post.uRes,canvas.width,canvas.height);gl.uniform1f(uniforms.post.uGlow,breathe);gl.uniform1f(uniforms.post.uGrain,state.grain);gl.drawArrays(gl.TRIANGLES,0,3);}
async function snapshot(){try{render(elapsed);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Image capture failed.');download(blob,'molten-'+state.seed+'-'+canvas.width+'x'+canvas.height+'.png');toast('Still saved at '+canvas.width+' × '+canvas.height+'.');}catch(e){toast(e.message);}}
window.addEventListener('resize',()=>{resizeNeeded=true;});document.addEventListener('visibilitychange',()=>{last=0;});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('The graphics connection was interrupted. Reload to restore your saved look. Try Eco quality if this happens again.');});
buildBlobs();sync();save();scale=[.5,.7,.9,1][state.quality];
function frame(now){requestAnimationFrame(frame);
var RM=window.__renderMode;
if(RM){
 if(RM.paused||RM._bp||RM.phase==='done'||RM.phase==='cancelled'||RM.phase==='reset'){requestAnimationFrame(frame);return;}
 if(resizeNeeded)resize();
 var rdt=1/RM.fps,rt=RM.frame/RM.fps;
 render(rt);
 if(RM.phase==='warmup'){RM.frame++;if(RM.frame>=RM.warmup&&RM.onPhase){try{RM.onPhase('reset');}catch(e){}}}
 else if(RM.phase==='record'){if(RM.onFrame){try{RM.onFrame(RM.frame);}catch(e){}}RM.frame++;if(RM.frame>=RM.totalFrames&&RM.onPhase){try{RM.onPhase('done');}catch(e){}}}
 requestAnimationFrame(frame);return;
}
if(document.hidden){last=0;return;}if(!last)last=now;const rawDt=(now-last)/1000;const dt=Math.min(.12,rawDt);last=now;if(playing){elapsed+=dt;heatPulse*=Math.exp(-dt*.24);}const limit=30;if(now-lastRender<1000/limit-1)return;lastRender=now;try{if(resizeNeeded)resize();render(elapsed);}catch(e){fail(e.message);return;}frameCount++;if(!fpsStart)fpsStart=now;if(now-fpsStart>2000){actualFPS=Math.round(frameCount*1000/(now-fpsStart));if(state.adaptive&&playing){const maxScale=[.55,.8,1,1.2][state.quality];if(actualFPS<limit*.65&&scale>.36){scale=Math.max(.35,scale-.10);resizeNeeded=true;}else if(actualFPS>limit*.95&&scale<maxScale){scale=Math.min(maxScale,scale+.04);resizeNeeded=true;}}frameCount=0;fpsStart=now;}}
// Hooks for the Seed Console adapter (defined in a script block near the end of the document). The console is the only UI that mutates generation state now.
window.__moltenHooks={getState:function(){return state;},update:update,applyPreset:applyPreset,setSeed:function(n){update('seed',n,false);elapsed=0;heatPulse=0;},resetCamera:function(){state.zoom=1;state.yaw=.12;state.pitch=.02;sync();save();},snapshot:snapshot,canvas:function(){return canvas;}};
window.__renderCanvas=canvas;
window.__renderReset=function(){elapsed=0;heatPulse=0;last=0;lastRender=0;buildBlobs();resizeNeeded=true;};
requestAnimationFrame(frame);
// Optional agent controls share the exact state mutations used by the studio UI.
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}};register({name:'get_lava_composition',description:'Read the current lava studio settings and available preset names.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({settings:{...state},presets:presets.map(p=>p.name)})});register({name:'apply_lava_preset',description:'Apply one named visual preset to the live lava studio. Does not record or download files.',inputSchema:{type:'object',properties:{name:{type:'string',enum:presets.map(p=>p.name)}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const i=presets.findIndex(p=>p.name===input?.name);if(i<0)throw Error('Unknown preset.');applyPreset(i);return{preset:presets[i].name,settings:{...state}};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
} // end else{ — closes the former IIFE body
