/* Moor kit: world-3d — Little World. Fixed 3D ecosystem engine.
   build(config) -> complete HTML string. Three.js r160 via unpkg CDN.
   All models procedural. Seeded RNG. Touch-first. No localStorage. */
window.MoorKit = {
  build: function (config) {
    config = config || {};
    var terrain = config.terrain, life = config.life, sky = config.sky;
    if (["hills", "islands", "mountains"].indexOf(terrain) < 0) terrain = "hills";
    if (["sparse", "balanced", "teeming"].indexOf(life) < 0) life = "balanced";
    if (["day", "sunset", "alien"].indexOf(sky) < 0) sky = "day";
    var cfgJson = JSON.stringify({ terrain: terrain, life: life, sky: sky });
    var p = [];
    p.push('<!DOCTYPE html>');
    p.push('<html lang="en">');
    p.push('<head>');
    p.push('<meta charset="utf-8">');
    p.push('<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">');
    p.push('<title>Little World</title>');
    p.push('<style>');
    p.push('html,body{margin:0;padding:0;height:100%;overflow:hidden;background:#06070d;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#fff;-webkit-user-select:none;user-select:none;}');
    p.push('canvas{display:block;touch-action:none;}');
    p.push('#hud{position:fixed;top:calc(10px + env(safe-area-inset-top));left:12px;right:12px;display:flex;justify-content:space-between;align-items:flex-start;pointer-events:none;z-index:5;}');
    p.push('.card{pointer-events:auto;background:rgba(10,13,22,0.62);-webkit-backdrop-filter:blur(14px);backdrop-filter:blur(14px);border:1px solid rgba(255,255,255,0.10);border-radius:16px;padding:10px 14px;box-shadow:0 8px 30px rgba(0,0,0,0.35);}');
    p.push('.title{font-size:15px;font-weight:700;letter-spacing:0.2px;}');
    p.push('.title .seed{font-weight:400;opacity:0.55;font-size:12px;margin-left:6px;font-variant-numeric:tabular-nums;}');
    p.push('.stats{font-size:12px;opacity:0.85;margin-top:3px;font-variant-numeric:tabular-nums;}');
    p.push('.controls{display:flex;gap:8px;}');
    p.push('.controls button{pointer-events:auto;min-width:48px;min-height:48px;border-radius:14px;border:1px solid rgba(255,255,255,0.12);background:rgba(20,26,40,0.72);color:#fff;font-size:17px;font-weight:700;cursor:pointer;-webkit-backdrop-filter:blur(14px);backdrop-filter:blur(14px);font-family:inherit;}');
    p.push('.controls button:active{transform:scale(0.94);}');
    p.push('#hint{position:fixed;bottom:calc(14px + env(safe-area-inset-bottom));left:0;right:0;text-align:center;font-size:12px;opacity:0.5;pointer-events:none;z-index:5;}');
    p.push('#nogl{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;padding:32px;font-size:15px;line-height:1.6;z-index:10;background:#06070d;}');
    p.push('#nogl[hidden]{display:none !important;}');
    p.push('</style>');
    p.push('</head>');
    p.push('<body>');
    p.push('<div id="hud">');
    p.push('<div class="card"><div class="title">Little World<span class="seed" id="seed"></span></div><div class="stats"><span id="pop">0</span> creatures &middot; <span id="veg">0</span> plants</div></div>');
    p.push('<div class="card controls"><button id="bPlay" aria-label="Play or pause">&#10074;&#10074;</button><button id="bSpeed" aria-label="Simulation speed">1&times;</button><button id="bSeed" aria-label="New world">&#127922;</button></div>');
    p.push('</div>');
    p.push('<div id="hint">drag to orbit &middot; pinch to zoom</div>');
    p.push('<div id="nogl" hidden>WebGL is not available on this device, so the world cannot start.</div>');
    p.push('<script src="https://unpkg.com/three@0.160.0/build/three.min.js"></scr' + 'ipt>');
    p.push('<script>');
    p.push('"use strict";');
    p.push('var CONFIG = ' + cfgJson + ';');
    p.push('function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;var t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}');
    p.push('function makeSimplex(rand){');
    p.push('var G2=(3-Math.sqrt(3))/6,F2=0.5*(Math.sqrt(3)-1);');
    p.push('var grad=[[1,1],[-1,1],[1,-1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];');
    p.push('var p8=new Uint8Array(256);for(var i=0;i<256;i++)p8[i]=i;');
    p.push('for(var i=255;i>0;i--){var j=(rand()*(i+1))|0;var t=p8[i];p8[i]=p8[j];p8[j]=t;}');
    p.push('var perm=new Uint8Array(512),pm=new Uint8Array(512);');
    p.push('for(var i=0;i<512;i++){perm[i]=p8[i&255];pm[i]=perm[i]%8;}');
    p.push('return function(x,y){');
    p.push('var n0=0,n1=0,n2=0;var s=(x+y)*F2,i=Math.floor(x+s),j=Math.floor(y+s);');
    p.push('var t=(i+j)*G2,x0=x-(i-t),y0=y-(j-t);');
    p.push('var i1,j1;if(x0>y0){i1=1;j1=0;}else{i1=0;j1=1;}');
    p.push('var x1=x0-i1+G2,y1=y0-j1+G2,x2=x0-1+2*G2,y2=y0-1+2*G2;');
    p.push('var ii=i&255,jj=j&255;');
    p.push('var t0=0.5-x0*x0-y0*y0;if(t0>0){t0*=t0;var g=grad[pm[ii+perm[jj]]];n0=t0*t0*(g[0]*x0+g[1]*y0);}');
    p.push('var t1=0.5-x1*x1-y1*y1;if(t1>0){t1*=t1;var g=grad[pm[ii+i1+perm[jj+j1]]];n1=t1*t1*(g[0]*x1+g[1]*y1);}');
    p.push('var t2=0.5-x2*x2-y2*y2;if(t2>0){t2*=t2;var g=grad[pm[ii+1+perm[jj+1]]];n2=t2*t2*(g[0]*x2+g[1]*y2);}');
    p.push('return 70*(n0+n1+n2);};}');
    p.push('function main(){');
    p.push('var cfg=CONFIG;');
    p.push('var seed=7;');
    p.push('try{var m=String(location.hash).match(/seed=(\\d+)/);if(m){seed=parseInt(m[1],10)>>>0;}else{seed=(Math.random()*1e9)>>>0;}}catch(e){seed=(Math.random()*1e9)>>>0;}');
    p.push('if(!seed)seed=7;');
    p.push('var rand=mulberry32(seed);');
    p.push('var noise2=makeSimplex(mulberry32((seed^0x9e3779b9)>>>0));');
    p.push('var SIZE=120,SEG=84;');
    p.push('var TER={hills:{amp:7,freq:0.028,base:4,water:0.8,oct:0,island:false},islands:{amp:8,freq:0.034,base:5,water:1.6,oct:0,island:true},mountains:{amp:16,freq:0.02,base:8,water:0.8,oct:0.45,island:false}}[cfg.terrain];');
    p.push('var LIFE={sparse:{c:12,p:45},balanced:{c:24,p:80},teeming:{c:40,p:120}}[cfg.life];');
    p.push('var SKY={day:{bg:0x8ab8e6,fog:0x9fc6ee,fn:70,ff:230,sun:0xfff1d6,sunI:1.1,amb:0xbdd4ff,ambI:0.8,water:0x2f6fc2,sp:[70,95,35],stars:false},sunset:{bg:0x35203f,fog:0x5c3a52,fn:55,ff:205,sun:0xff9448,sunI:1.0,amb:0x8a5f8f,ambI:0.65,water:0x6e3a5c,sp:[85,20,-45],stars:false},alien:{bg:0x0a0a26,fog:0x161638,fn:50,ff:195,sun:0x53f2ff,sunI:0.85,amb:0x9a5fff,ambI:0.7,water:0x1b4a6e,sp:[-55,75,65],stars:true}}[cfg.sky];');
    p.push('var CAP_C=60,CAP_P=120;');
    p.push('var renderer=null;');
    p.push('try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){renderer=null;}');
    p.push('if(!renderer||!window.WebGLRenderingContext){document.getElementById("nogl").hidden=false;return;}');
    p.push('renderer.setPixelRatio(Math.min(2,window.devicePixelRatio||1));');
    p.push('renderer.setSize(window.innerWidth,window.innerHeight);');
    p.push('document.body.appendChild(renderer.domElement);');
    p.push('var scene=new THREE.Scene();');
    p.push('scene.background=new THREE.Color(SKY.bg);');
    p.push('scene.fog=new THREE.Fog(SKY.fog,SKY.fn,SKY.ff);');
    p.push('var camera=new THREE.PerspectiveCamera(55,window.innerWidth/window.innerHeight,0.5,700);');
    p.push('var sun=new THREE.DirectionalLight(SKY.sun,SKY.sunI);sun.position.set(SKY.sp[0],SKY.sp[1],SKY.sp[2]);scene.add(sun);');
    p.push('scene.add(new THREE.AmbientLight(SKY.amb,SKY.ambI));');
    p.push('if(SKY.stars){var sg=new THREE.BufferGeometry(),sp2=[];for(var si=0;si<500;si++){var a=rand()*Math.PI*2,e2=rand()*Math.PI*0.45+0.08,r=420;sp2.push(r*Math.cos(e2)*Math.cos(a),r*Math.sin(e2),r*Math.cos(e2)*Math.sin(a));}sg.setAttribute("position",new THREE.Float32BufferAttribute(sp2,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xcfe8ff,size:1.6,sizeAttenuation:false,fog:false})));}');
    p.push('function smooth(a,b,x){var t=Math.min(1,Math.max(0,(x-a)/(b-a)));return t*t*(3-2*t);}');
    p.push('function terrainH(x,z){var n=noise2(x*TER.freq,z*TER.freq);var h=TER.base+n*TER.amp;if(TER.oct)h+=noise2(x*TER.freq*2.7+13.7,z*TER.freq*2.7+7.1)*TER.amp*TER.oct;if(TER.island){var d=Math.sqrt(x*x+z*z)/(SIZE*0.5);h-=smooth(0.45,0.95,d)*18;}return h;}');
    p.push('var terrainMesh=null,waterMesh=null;');
    p.push('var cSand=new THREE.Color(0xd9c184),cG1=new THREE.Color(0x3f9e4d),cG2=new THREE.Color(0x86a844),cRock=new THREE.Color(0x8a8d94),cSnow=new THREE.Color(0xf2f5fa);');
    p.push('function buildTerrain(){');
    p.push('if(terrainMesh){scene.remove(terrainMesh);terrainMesh.geometry.dispose();terrainMesh.material.dispose();}');
    p.push('var geo=new THREE.PlaneGeometry(SIZE,SIZE,SEG,SEG);geo.rotateX(-Math.PI/2);');
    p.push('var pos=geo.attributes.position,cols=[],tmp=new THREE.Color();');
    p.push('var maxH=TER.base+TER.amp*(1+TER.oct);');
    p.push('for(var i=0;i<pos.count;i++){var x=pos.getX(i),z=pos.getZ(i),h=terrainH(x,z);pos.setY(i,h);');
    p.push('if(h<TER.water+0.45){tmp.copy(cSand);}else{tmp.copy(cG1).lerp(cG2,smooth(TER.water+0.5,TER.base+TER.amp*0.55,h));tmp.lerp(cRock,smooth(TER.base+TER.amp*0.55,maxH*0.88,h));tmp.lerp(cSnow,smooth(maxH*0.82,maxH*1.02,h));}');
    p.push('var v=0.94+noise2(x*0.11,z*0.11)*0.06;cols.push(tmp.r*v,tmp.g*v,tmp.b*v);}');
    p.push('geo.setAttribute("color",new THREE.Float32BufferAttribute(cols,3));');
    p.push('geo.computeVertexNormals();');
    p.push('terrainMesh=new THREE.Mesh(geo,new THREE.MeshLambertMaterial({vertexColors:true}));');
    p.push('scene.add(terrainMesh);');
    p.push('if(!waterMesh){var wg=new THREE.PlaneGeometry(SIZE*2,SIZE*2);wg.rotateX(-Math.PI/2);waterMesh=new THREE.Mesh(wg,new THREE.MeshLambertMaterial({color:SKY.water,transparent:true,opacity:0.8}));waterMesh.position.y=TER.water;scene.add(waterMesh);}}');
    p.push('var creatures=[],plants=[];');
    p.push('var bodyGeo=new THREE.SphereGeometry(1,14,12);');
    p.push('var eyeGeo=new THREE.SphereGeometry(0.24,8,8);');
    p.push('var pupGeo=new THREE.SphereGeometry(0.11,8,8);');
    p.push('var eyeMat=new THREE.MeshBasicMaterial({color:0xffffff});');
    p.push('var pupMat=new THREE.MeshBasicMaterial({color:0x14141c});');
    p.push('function randTraits(){return{hue:Math.floor(rand()*360),size:0.75+rand()*0.65,speed:2.4+rand()*3.4,vision:10+rand()*12,maxAge:80+rand()*100,metab:0.85+rand()*0.7};}');
    p.push('function mutate(t){function mm(v,a){return v*(1+(rand()*2-1)*a);}return{hue:(t.hue+Math.floor((rand()*2-1)*30)+360)%360,size:Math.min(1.6,Math.max(0.55,mm(t.size,0.14))),speed:Math.min(7.5,Math.max(1.4,mm(t.speed,0.14))),vision:Math.min(26,Math.max(6,mm(t.vision,0.16))),maxAge:Math.min(220,Math.max(45,mm(t.maxAge,0.16))),metab:Math.min(2.0,Math.max(0.5,mm(t.metab,0.14)))};}');
    p.push('function landXYZ(){for(var k=0;k<40;k++){var x=(rand()*2-1)*(SIZE/2-6),z=(rand()*2-1)*(SIZE/2-6);if(terrainH(x,z)>TER.water+0.6)return{x:x,z:z};}return{x:0,z:0};}');
    p.push('function spawnCreature(x,z,traits){');
    p.push('traits=traits||randTraits();');
    p.push('var g=new THREE.Group();');
    p.push('var col=new THREE.Color("hsl("+traits.hue+",62%,55%)");');
    p.push('var body=new THREE.Mesh(bodyGeo,new THREE.MeshLambertMaterial({color:col}));');
    p.push('body.scale.set(traits.size,traits.size*0.82,traits.size*1.12);g.add(body);');
    p.push('var s=traits.size;');
    p.push('[-1,1].forEach(function(sg2){var e=new THREE.Mesh(eyeGeo,eyeMat);e.position.set(0.34*sg2*s,0.36*s,0.92*s);g.add(e);var pu=new THREE.Mesh(pupGeo,pupMat);pu.position.set(0.34*sg2*s,0.36*s,1.04*s);g.add(pu);});');
    p.push('var c={g:g,tr:traits,x:x,z:z,heading:rand()*Math.PI*2,energy:55+rand()*35,age:rand()*6,reproT:6+rand()*8,wt:0,bob:rand()*6,dying:0};');
    p.push('g.position.set(x,terrainH(x,z)+s*0.8,z);');
    p.push('scene.add(g);creatures.push(c);return c;}');
    p.push('function updateCreature(c,dt){');
    p.push('var tr=c.tr;');
    p.push('if(c.dying>0){c.dying-=dt;var k=Math.max(0.001,c.dying/0.6);c.g.scale.setScalar(k);if(c.dying<=0){scene.remove(c.g);var ix=creatures.indexOf(c);if(ix>=0)creatures.splice(ix,1);}return;}');
    p.push('c.age+=dt;c.energy-=(1.5+tr.speed*0.55+tr.size*0.4)*tr.metab*dt;');
    p.push('if(c.energy<=0||c.age>tr.maxAge){c.dying=0.6;c.energy=0;return;}');
    p.push('var hunger=1-c.energy/100,target=null,best=Infinity;');
    p.push('if(hunger>0.28){for(var i=0;i<plants.length;i++){var pl=plants[i];if(pl.amount<0.25)continue;var dx=pl.x-c.x,dz=pl.z-c.z,d2=dx*dx+dz*dz;if(d2<tr.vision*tr.vision&&d2<best){best=d2;target=pl;}}}');
    p.push('var desired=c.heading;');
    p.push('if(target){desired=Math.atan2(target.x-c.x,target.z-c.z);var rr2=1.4*tr.size+0.9;if(best<rr2*rr2){var bite=Math.min(target.amount,0.6*dt);target.amount-=bite;c.energy=Math.min(100,c.energy+bite*60);}}');
    p.push('else{c.wt-=dt;if(c.wt<=0){c.wt=0.8+rand()*2.6;c.heading+=(rand()-0.5)*2.4;desired=c.heading;}}');
    p.push('var diff=((desired-c.heading+Math.PI*3)%(Math.PI*2))-Math.PI;');
    p.push('c.heading+=Math.max(-3.2*dt,Math.min(3.2*dt,diff));');
    p.push('var nx=c.x+Math.sin(c.heading)*tr.speed*dt,nz=c.z+Math.cos(c.heading)*tr.speed*dt;');
    p.push('var half=SIZE/2-4;');
    p.push('var ok=Math.abs(nx)<half&&Math.abs(nz)<half&&terrainH(nx,nz)>TER.water+0.35;');
    p.push('if(ok){c.x=nx;c.z=nz;}else{c.heading+=7.5*dt;c.wt=0.2;}');
    p.push('c.bob+=dt*(4+tr.speed);');
    p.push('c.g.position.set(c.x,terrainH(c.x,c.z)+tr.size*0.8+Math.abs(Math.sin(c.bob))*0.14*tr.size,c.z);');
    p.push('c.g.rotation.y=c.heading;');
    p.push('if(c.energy>70&&c.age>9&&c.reproT<=0&&creatures.length<CAP_C){c.reproT=8+rand()*7;c.energy*=0.55;var cx=c.x+(rand()-0.5)*4,cz=c.z+(rand()-0.5)*4;if(terrainH(cx,cz)<=TER.water+0.35){var l2=landXYZ();cx=l2.x;cz=l2.z;}spawnCreature(cx,cz,mutate(tr));}else{c.reproT-=dt;}}');
    p.push('function separate(){for(var i=0;i<creatures.length;i++){var a=creatures[i];if(a.dying>0)continue;for(var j=i+1;j<creatures.length;j++){var b=creatures[j];if(b.dying>0)continue;var dx=b.x-a.x,dz=b.z-a.z,rr=(a.tr.size+b.tr.size)*0.9,d2=dx*dx+dz*dz;if(d2<rr*rr&&d2>0.0001){var d=Math.sqrt(d2),push=(rr-d)*0.5/d;a.x-=dx*push;a.z-=dz*push;b.x+=dx*push;b.z+=dz*push;}}}}');
    p.push('var plantGeo=new THREE.IcosahedronGeometry(1,0);');
    p.push('function spawnPlant(x,z){var s=0.9+rand()*1.2;var col=new THREE.Color().setHSL(0.30+rand()*0.09,0.62,0.30+rand()*0.12);var mesh=new THREE.Mesh(plantGeo,new THREE.MeshLambertMaterial({color:col}));var p2={x:x,z:z,amount:0.55+rand()*0.45,s0:s,mesh:mesh};mesh.position.set(x,terrainH(x,z)+s*0.55,z);mesh.scale.set(s,s*0.8,s);scene.add(mesh);plants.push(p2);}');
    p.push('function updatePlants(dt){for(var i=0;i<plants.length;i++){var p2=plants[i];if(p2.amount<1){p2.amount=Math.min(1,p2.amount+0.055*dt*(0.4+p2.amount));var k=Math.max(0.12,p2.amount);p2.mesh.scale.set(p2.s0*k,p2.s0*0.8*k,p2.s0*k);}}}');
    p.push('var camT=0.9,camP=1.02,camR=100;');
    p.push('function applyCam(){var sp=Math.sin(camP);camera.position.set(camR*sp*Math.sin(camT),Math.max(10,camR*Math.cos(camP)),camR*sp*Math.cos(camT));camera.lookAt(0,5,0);}');
    p.push('var cv=renderer.domElement,ptrs={},pinchD=0;');
    p.push('cv.style.touchAction="none";');
    p.push('cv.addEventListener("pointerdown",function(e){ptrs[e.pointerId]={x:e.clientX,y:e.clientY};var ks=Object.keys(ptrs);if(ks.length===2){var a=ptrs[ks[0]],b=ptrs[ks[1]];pinchD=Math.hypot(a.x-b.x,a.y-b.y);}try{cv.setPointerCapture(e.pointerId);}catch(err){}});');
    p.push('cv.addEventListener("pointermove",function(e){var pr=ptrs[e.pointerId];if(!pr)return;var dx=e.clientX-pr.x,dy=e.clientY-pr.y;pr.x=e.clientX;pr.y=e.clientY;var ks=Object.keys(ptrs);if(ks.length===1){camT-=dx*0.0052;camP=Math.min(1.35,Math.max(0.28,camP-dy*0.004));}else if(ks.length===2){var a=ptrs[ks[0]],b=ptrs[ks[1]],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinchD>0)camR=Math.min(180,Math.max(38,camR*pinchD/Math.max(1,d)));pinchD=d;}});');
    p.push('function endP(e){delete ptrs[e.pointerId];pinchD=0;}');
    p.push('cv.addEventListener("pointerup",endP);cv.addEventListener("pointercancel",endP);');
    p.push('cv.addEventListener("wheel",function(e){e.preventDefault();camR=Math.min(180,Math.max(38,camR*(1+e.deltaY*0.001)));},{passive:false});');
    p.push('var running=true,speed=1,speeds=[1,2,4];');
    p.push('var popEl=document.getElementById("pop"),vegEl=document.getElementById("veg"),seedEl=document.getElementById("seed");');
    p.push('var bPlay=document.getElementById("bPlay"),bSpeed=document.getElementById("bSpeed"),bSeed=document.getElementById("bSeed");');
    p.push('bPlay.addEventListener("pointerup",function(){running=!running;bPlay.textContent=running?"\\u275A\\u275A":"\\u25B6";});');
    p.push('bSpeed.addEventListener("pointerup",function(){speed=speeds[(speeds.indexOf(speed)+1)%speeds.length];bSpeed.textContent=speed+"\\u00D7";});');
    p.push('bSeed.addEventListener("pointerup",function(){seed=(Math.random()*1e9)>>>0;if(!seed)seed=7;try{location.hash="seed="+seed;}catch(e){}initWorld();});');
    p.push('function clearWorld(){for(var i=0;i<creatures.length;i++)scene.remove(creatures[i].g);creatures.length=0;for(var j=0;j<plants.length;j++)scene.remove(plants[j].mesh);plants.length=0;}');
    p.push('function initWorld(){clearWorld();rand=mulberry32(seed);noise2=makeSimplex(mulberry32((seed^0x9e3779b9)>>>0));buildTerrain();');
    p.push('var np=Math.min(CAP_P,LIFE.p);for(var i=0;i<np;i++){var l=landXYZ();spawnPlant(l.x,l.z);}');
    p.push('for(var k=0;k<LIFE.c;k++){var l2=landXYZ();spawnCreature(l2.x,l2.z);}');
    p.push('seedEl.textContent="seed "+seed;running=true;bPlay.textContent="\\u275A\\u275A";}');
    p.push('function simStep(dt){for(var i=creatures.length-1;i>=0;i--)updateCreature(creatures[i],dt);separate();updatePlants(dt);}');
    p.push('var last=performance.now(),hudT=0;');
    p.push('function tick(now){requestAnimationFrame(tick);var dt=Math.min(0.05,(now-last)/1000);last=now;if(running&&dt>0){for(var s=0;s<speed;s++)simStep(dt);}applyCam();renderer.render(scene,camera);hudT-=dt;if(hudT<=0){hudT=0.5;popEl.textContent=String(creatures.length);vegEl.textContent=String(plants.length);}}');
    p.push('window.addEventListener("resize",function(){camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight);});');
    p.push('window.addEventListener("orientationchange",function(){setTimeout(function(){camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight);},250);});');
    p.push('initWorld();');
    p.push('requestAnimationFrame(tick);');
    p.push('}');
    p.push('if(!window.THREE){var n=document.getElementById("nogl");n.hidden=false;n.textContent="Could not load the 3D library. Check your connection and reopen.";}');
    p.push('else{try{main();}catch(err){var n2=document.getElementById("nogl");n2.hidden=false;n2.textContent="Something went wrong starting the world.";}}');
    p.push('</scr' + 'ipt>');
    p.push('</body>');
    p.push('</html>');
    return p.join("\n");
  }
};
