const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),G=require('../blueprint/graph-core.js'),data=JSON.parse(read('blueprint/moor-blueprint-data.json'));
G.validate(data);const levels=G.order(data).levels;for(const e of data.edges.filter(e=>e.type==='build'))assert(levels.get(e.fromId)<levels.get(e.toId));
assert.equal(data.nodes.filter(n=>n.kind==='atom').length,20);assert.equal(data.nodes.filter(n=>n.kind==='kit').length,20);assert.equal(data.nodes.filter(n=>n.kind==='app-contract').length,11);assert.equal(data.nodes.filter(n=>n.kind==='catalog').length,data.audit.catalogCoverage);
const n=id=>({id,title:id,overview:id,ports:{in:['record'],out:['record']}}),e=(a,b,c='order')=>({id:a+'>'+b,fromId:a,toId:b,type:'build',contract:c});
const simple=()=>({schema:'moor.whole-product-blueprint',version:1,revision:1,nodes:['a','b','c','d'].map(n),edges:[e('a','b'),e('b','c'),e('a','c'),e('b','d')],tombstones:[]});
const original=simple(),removed=G.transact(original,g=>G.remove(g,'b'),'Remove b');assert(original.nodes.some(n=>n.id==='b'));assert(!removed.nodes.some(n=>n.id==='b'));assert.equal(removed.edges.filter(e=>e.fromId==='a'&&e.toId==='c').length,1);assert(removed.edges.find(e=>e.toId==='c').review);assert(removed.edges.some(e=>e.fromId==='a'&&e.toId==='d'));assert.equal(removed.tombstones[0].edges.length,3);assert.equal(removed.revision,2);
const typed=simple();typed.edges=[e('a','b','record'),e('b','c','record')];typed.nodes.find(n=>n.id==='c').ports.in=['mesh'];typed.edges[1].contract='order';G.remove(typed,'b');assert.equal(typed.tombstones[0].unresolved.length,1);assert(!typed.edges.length);
const inserted=G.transact(original,g=>G.insert(g,n('x'),[G.key(e('a','b'))]),'Insert');assert(inserted.edges.some(e=>e.fromId==='a'&&e.toId==='x'));assert(inserted.edges.some(e=>e.fromId==='x'&&e.toId==='b'));assert(!inserted.edges.some(e=>e.fromId==='a'&&e.toId==='b'));
assert.throws(()=>G.transact(original,g=>G.addEdge(g,'c','a'),'Cycle'),/cycle/);assert.throws(()=>G.transact(original,g=>G.addEdge(g,'a','absent'),'Missing'),/missing|ports/);assert.throws(()=>G.transact(original,g=>G.addEdge(g,'a','d','build','mesh'),'Contract'),/ports/);assert.throws(()=>G.validate({...original,nodes:[...original.nodes,n('a')]}),/unique/);assert.throws(()=>G.validate({...original,nodes:original.nodes.map(n=>({...n,reference:{bad:true}}))}),/text/);
// Color annotations round-trip without changing dependency order; legacy drafts stay valid.
assert.equal(G.cardColors.length,16);assert.equal(new Set(G.cardColors.map(c=>c.id)).size,16);
for(const c of G.cardColors){const colored=G.transact(original,g=>{G.setCardColor(g,'b',c.id);G.renameColor(g,c.id,'Ready to build');},'Color annotation');const restored=G.validate(JSON.parse(JSON.stringify(colored)));assert.equal(restored.nodes.find(n=>n.id==='b').colorId,c.id);assert.equal(G.colorLabel(restored,c.id),'Ready to build');assert.deepEqual(G.order(restored).ids,G.order(original).ids);assert.equal(original.nodes.find(n=>n.id==='b').colorId,undefined);G.setCardColor(restored,'b',null);assert.equal(restored.nodes.find(n=>n.id==='b').colorId,undefined);}
assert.throws(()=>G.transact(original,g=>G.setCardColor(g,'b','red;display:none'),'Unsafe color'),/Unknown/);
assert.throws(()=>G.validate({...original,colorKey:{ruby:[]}}),/color key/);
assert.throws(()=>G.transact(original,g=>G.renameColor(g,'ruby',''),'Empty key'),/characters/);
const summary=G.visibleEdges(original,['a','c','d']);assert(summary.some(e=>e.fromId==='a'&&e.toId==='d'&&e.via.includes('b')));
const context={};vm.runInNewContext(read('blueprint/reference-code.js'),context);const R=context.BlueprintReference;
for(const n of data.nodes){const html=R.generate(n);assert(html.includes('<!doctype html>'));for(const s of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(s[1],{filename:n.id});}
const structured=R.compile(JSON.stringify({schema:'moor.reference-ui',version:1,title:'Actual state',state:{count:1},blocks:[{type:'text',text:'{{count}}'},{type:'button',label:'Count',action:{type:'increment',key:'count'}}]}));assert(structured.includes('/\\{\\{([\\w-]+)\\}\\}/g'));for(const s of structured.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);
assert.throws(()=>R.compile('{bad'),/malformed/);assert.throws(()=>R.compile('{"schema":"wrong","version":1,"blocks":[]}'),/schema/);assert.throws(()=>R.compile('{"schema":"moor.reference-ui","version":1,"blocks":[{"type":"unknown"}]}'),/Unsupported/);
const isolated=R.isolate('<html><head></head><body><h1>My exact outcome</h1></body></html>','test');assert(isolated.includes("connect-src 'none'"));assert(isolated.includes('My exact outcome'));assert(isolated.indexOf('Content-Security-Policy')<isolated.indexOf('My exact outcome'));
const html=read('moor-blueprint.html');const embedded=JSON.parse(html.match(/<script id="blueprint-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);assert.equal(embedded.nodes.length,data.nodes.length);assert(embedded.rawIntent);for(const s of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!s[1].includes('application/json'))new vm.Script(s[2]);assert(html.includes('sandbox="allow-scripts allow-downloads"'));assert(!html.includes('allow-same-origin'));assert(html.includes('id="export"'));
for(const n of data.nodes)for(const id of n.sources||[])assert(data.sources.some(s=>s.id===id),'Missing source '+id);
// Exercise generated mechanisms, rather than claiming that compilation proves behavior.
function runReference(id){const elements=new Map(),element=()=>({value:'',textContent:'',children:[],append(...xs){this.children.push(...xs)},replaceChildren(){this.children=[]},before(){},style:{},getContext(){return {fillRect(){},clearRect(){},fillStyle:''}}});const get=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)};const ctx={document:{getElementById:get,createElement:element},crypto:{randomUUID:()=>Math.random().toString()},Blob,URL,console};const html=R.generate(data.nodes.find(n=>n.id===id));vm.runInNewContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);return get;}
const records=runReference('operations');records('input').value='Persistent contract example';records('add').onclick();assert.equal(JSON.parse(records('receipt').textContent).records[0].title,'Persistent contract example');records('records').children[0].children[1].onclick();assert.equal(JSON.parse(records('receipt').textContent).records.length,0);
const permissions=runReference('permissions');permissions('actor').value='viewer';permissions('edit').onclick();assert.equal(JSON.parse(permissions('receipt').textContent).allowed,false);permissions('actor').value='owner';permissions('edit').onclick();assert.equal(JSON.parse(permissions('receipt').textContent).allowed,true);
const terrain=runReference('spatial');terrain('seed').value='same-seed';terrain('reroll').onclick();const first=terrain('result').textContent;terrain('reroll').onclick();assert.equal(terrain('result').textContent,first);terrain('seed').value='another-seed';terrain('reroll').onclick();assert.notEqual(terrain('result').textContent,first);
// Registering from the normal dashboard path must preserve existing independent components.
const registered=[],tools={},fake={style:{},append(){},appendChild(){},classList:{add(){},remove(){}}};const mountContext={COMPS:registered,TOOLS:tools,document:{getElementById:()=>fake,createElement:()=>({...fake}),head:fake},window:{addEventListener(){}},location:{search:'',href:'https://example.test/pulse-dashboard.html'},URLSearchParams,URL,renderStage(){}};vm.runInNewContext(read('pulse-component-extensions.js'),mountContext);for(const id of ['moor-blueprint','moor-atlas','wall-mirror','living-garden','planet-workshop','server-harness','app-compiler-harness'])assert(registered.some(c=>c.id===id));assert.equal(typeof tools.moorBlueprint.mount,'function');
const manifest=JSON.parse(read('pulse-manifest.json'));assert(manifest.items['moor-blueprint']);assert(manifest.tools.some(t=>t.id==='moor-blueprint'));assert(manifest.index['cat:creation'].includes('moor-blueprint'));assert(read('pulse-workspace.js').includes("seedProject('moor-whole-blueprint'"));assert(JSON.parse(read('moor-bin/projects/moor-whole-blueprint.json')).funnel_project_id==='moor-whole-blueprint');
console.log('PASS: complete baseline, build DAG, reversible typed editing, import rejection, every reference script, actual record/permission/seed behavior, structured UI compiler, sandbox, standalone bundle and additive Bin/Funnel registration');
