import fs from 'node:fs';
import path from 'node:path';
import {T} from '../../vita-verde/assets.mjs';
import {buildWorld} from '../../vita-verde/worlds.mjs';
import {direct} from '../../vita-verde/director.mjs';
import {settings,SHOTS,shotAt} from '../../vita-verde/timeline.mjs';
import {FRAGMENT} from '../../vita-verde/post.mjs';
import {wav} from '../../vita-verde/sound.mjs';
const out=process.argv[2]||'/tmp/vita-frames';fs.mkdirSync(out,{recursive:true});
const cfg=settings({seed:process.env.VV_SEED,format:process.env.VV_FORMAT,store:process.env.VV_STORE,house:process.env.VV_HOUSE});
const times=process.env.VV_TIMES?process.env.VV_TIMES.split(',').map(Number):process.env.VV_FPS?Array.from({length:90*+process.env.VV_FPS},(_,i)=>i/+process.env.VV_FPS):SHOTS.map(s=>(s.start+s.end)/2);
const camera=new T.PerspectiveCamera(44,cfg.format==='portrait'?9/16:16/9,.008,140),worlds=new Map(),geos=new Map(),mats=new Map(),textures=new Map(),catalog={config:cfg,geometries:[],materials:[],textures:[],frames:[]};
function geometry(g){if(geos.has(g.uuid))return geos.get(g.uuid);const id=geos.size;geos.set(g.uuid,id);const geo=g.index?g.toNonIndexed():g,pa=geo.attributes.position,na=geo.attributes.normal,uv=geo.attributes.uv,data=new Float32Array(pa.count*8);for(let i=0;i<pa.count;i++)data.set([pa.getX(i),pa.getY(i),pa.getZ(i),na.getX(i),na.getY(i),na.getZ(i),uv?.getX(i)||0,uv?.getY(i)||0],i*8);fs.writeFileSync(path.join(out,`g${id}.bin`),Buffer.from(data.buffer));catalog.geometries.push({id,count:pa.count});if(geo!==g)geo.dispose();return id;}
function tex(t){if(!t?.image?.data)return -1;if(textures.has(t.uuid))return textures.get(t.uuid);const id=textures.size;textures.set(t.uuid,id);fs.writeFileSync(path.join(out,`t${id}.bin`),t.image.data);catalog.textures.push({id,width:t.image.width,height:t.image.height});return id;}
function material(m){if(mats.has(m.uuid))return mats.get(m.uuid);const id=mats.size;mats.set(m.uuid,id);catalog.materials.push({id,color:m.color.toArray(),roughness:m.roughness,metalness:m.metalness,emissive:m.emissive?.toArray().map(x=>x*m.emissiveIntensity)||[0,0,0],opacity:m.opacity,transparent:m.transparent,double:m.side===2,map:tex(m.map)});return id;}
for(let j=0;j<times.length;j++){const t=times[j],kind=shotAt(t).world;if(!worlds.has(kind))worlds.set(kind,buildWorld(kind,cfg));const world=worlds.get(kind),state=direct(world,camera,t,cfg),objects=[];world.scene.traverseVisible(o=>{if(!o.isMesh||Array.isArray(o.material))return;objects.push({id:o.uuid,g:geometry(o.geometry),m:material(o.material),matrix:o.matrixWorld.toArray(),shadow:o.castShadow,name:o.name});});world.key.shadow.updateMatrices(world.key);catalog.frames.push({time:t,world:kind,shot:state.shot.id,objects,camera:{view:camera.matrixWorldInverse.toArray(),projection:camera.projectionMatrix.toArray(),inverseProjection:camera.projectionMatrixInverse.toArray(),position:camera.position.toArray(),focus:world.focus},light:{matrix:world.key.shadow.camera.projectionMatrix.clone().multiply(world.key.shadow.camera.matrixWorldInverse).toArray(),direction:world.key.position.clone().sub(world.key.target.position).normalize().toArray(),color:world.key.color.toArray(),power:world.key.intensity,sky:world.fill.color.toArray(),ground:world.fill.groundColor.toArray(),fill:world.fill.intensity},background:world.scene.background.toArray(),fog:{color:world.scene.fog.color.toArray(),near:world.scene.fog.near,far:world.scene.fog.far}});if(j%100===0)console.log(`Captured ${j+1}/${times.length}`);}
fs.writeFileSync(path.join(out,'scene.json'),JSON.stringify(catalog));fs.writeFileSync(path.join(out,'post.glsl'),FRAGMENT);fs.writeFileSync(path.join(out,'score.wav'),Buffer.from(wav()));console.log(`Saved ${times.length} scene snapshots, ${geos.size} geometries, ${mats.size} materials to ${out}`);
