const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(__dirname,file),'utf8');
const data=JSON.parse(read('moor-blueprint-data.json'));
data.rawIntent='Audit all available MOOR information and recover lost progress. Understand the whole end state for the owner, assistant/builders, creators and consumers, with a transparent offer, gains and losses. Map every feature and dependency in build order. Make it beautiful, clean and readable. Initial cards show only titles, with expandable simple overviews, reasoning, alternatives, failures and evidence. Add, remove, connect or insert between rows; preserve connections on expansion and consolidate them on removal. Generate reference code, accept reference code and actually render its outcome. Put full-context export at bottom left for the next version/mockup. Register the blueprint in Bin and Funnel. Preserve unresolved facts instead of inventing them.';
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="An editable whole-product MOOR blueprint: source audit, product offer, dependency map, executable reference previews and complete version export."><title>MOOR · The Whole Blueprint</title><style>${read('blueprint.css')}</style></head><body>
<header class="top"><div class="brand"><span class="eyebrow">MOOR / architecture that stays editable</span><h1>The whole blueprint.</h1><p>One place. Every piece. A visible reason for the next step.</p></div><nav class="top-actions" aria-label="Blueprint context"><button id="offer">The offer</button><button id="execution">Execution</button><button id="audit">Source audit</button><button id="import">Import version</button><button id="hearth-toggle" title="More’s game blueprint — second page">♥ HEARTH — More’s blueprint</button></nav></header>
<div class="toolbar"><div class="tools"><div class="seg" aria-label="Map scope"><button id="overview" aria-pressed="true">Overview</button><button id="full" aria-pressed="false">Everything</button></div><input id="search" type="search" placeholder="Find any piece…" aria-label="Search every card"><select id="domain" aria-label="Filter domain"></select><label><input type="checkbox" id="failures"> Failures</label><label><input type="checkbox" id="relations"> Other links</label></div><div class="tools"><button id="undo" title="Undo edit" disabled>↶</button><button id="redo" title="Redo edit" disabled>↷</button><button id="add">+ Add piece</button></div></div>
<div class="meta-bar"><span><strong id="counts"></strong><br><span id="view-note"></span> <span id="connect-note"></span></span><div class="legend"><span>Prerequisite</span><span class="gold">Reconnection needs review</span><span class="violet">Flow / related / risk</span></div></div>
<main class="map-scroll" id="map-scroll" aria-label="Editable product dependency map"><div class="map" id="map"></div></main>
<div class="footer"><details class="color-key" id="color-key"><summary>Color key <span id="key-dots" aria-hidden="true"></span></summary><div id="key-fields" class="key-fields"></div></details><div class="funnel-entry"><button class="primary" id="answer-questions">Answer questions</button><small id="funnel-progress"></small></div><div class="inline answer-ledger-actions"><button id="save-answers">Save answers</button><button id="export-answers">Export answers</button><button id="answer-history">History</button><button id="refresh-questions">Refresh questions</button></div><div class="footer-actions"><button class="primary" id="export">↗ Export full context</button><small id="save-state">Audited baseline</small></div></div><div class="color-menu" id="color-menu" role="dialog" aria-label="Recolor card" hidden></div><div class="toast" id="toast" role="status" hidden></div>
<details id="review-dock" class="review-dock"><summary>Model review <small id="review-status"></small></summary><div class="review-body"><label>Reviewer<select id="review-model"><option>GPT</option><option>MUSE</option><option>COPI</option><option>LOCAL</option><option>NONE</option><option>OTHER</option></select></label><label>Target components<select id="review-scope"><option value="all">All components</option><option value="answered">Components with answers</option><option value="focused">Focused card (if selected)</option></select></label><button id="model-copy" class="primary">Export answers to GPT</button><label id="model-result-label" for="model-result">Paste GPT result</label><textarea id="model-result" placeholder="Paste the model’s JSON opinion results…" spellcheck="false"></textarea><button id="model-import">Compile pasted opinions</button><label>Review cadence<select id="review-cadence"><option value="off">Manual</option><option value="answers">After answers change</option><option value="5">Every 5 minutes</option><option value="15">Every 15 minutes</option><option value="60">Hourly</option><option value="1440">Daily</option></select></label><small id="cadence-note"></small></div></details><dialog id="dialog"><div class="dialog-head"><div><div class="eyebrow" id="dialog-eyebrow"></div><h2 id="dialog-title"></h2></div><button id="dialog-close" aria-label="Close dialog">×</button></div><div class="dialog-content" id="dialog-content"></div></dialog><datalist id="domain-list"></datalist><datalist id="port-list"></datalist>
<script id="blueprint-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script>
<script>${read('graph-core.js')}</script><script>${read('funnel-core.js')}</script><script>${read('reference-code.js')}</script><script>${read('funnel-ui.js')}</script><script>${read('editor.js')}</script><script>document.getElementById('hearth-toggle').addEventListener('click',function(){location.href='hearth-blueprint.html';});</script></body></html>`;
// Source modules must never contain a literal closing-script sequence.
for(const file of ['graph-core.js','funnel-core.js','reference-code.js','funnel-ui.js','editor.js'])if(/<\/script/i.test(read(file)))throw Error('Unsafe inline source '+file);
fs.writeFileSync(path.join(root,'moor-blueprint.html'),html);
console.log('Built self-contained blueprint: '+data.nodes.length+' cards / '+data.edges.length+' links / '+Buffer.byteLength(html)+' bytes');

