const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(__dirname,file),'utf8');
const data=JSON.parse(read('moor-blueprint-data.json'));
data.rawIntent='Audit all available MOOR information and recover lost progress. Understand the whole end state for the owner, assistant/builders, creators and consumers, with a transparent offer, gains and losses. Map every feature and dependency in build order. Make it beautiful, clean and readable. Initial cards show only titles, with expandable simple overviews, reasoning, alternatives, failures and evidence. Add, remove, connect or insert between rows; preserve connections on expansion and consolidate them on removal. Generate reference code, accept reference code and actually render its outcome. Put full-context export at bottom left for the next version/mockup. Register the blueprint in Bin and Funnel. Preserve unresolved facts instead of inventing them.';
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="An editable whole-product MOOR blueprint: source audit, product offer, dependency map, executable reference previews and complete version export."><title>MOOR · The Whole Blueprint</title><style>${read('blueprint.css')}</style></head><body>
<header class="top"><div class="brand"><span class="eyebrow">MOOR / architecture that stays editable</span><h1>The whole blueprint.</h1><p>One place. Every piece. A visible reason for the next step.</p></div><nav class="top-actions" aria-label="Blueprint context"><button id="offer">The offer</button><button id="execution">Execution</button><button id="audit">Source audit</button><button id="import">Import version</button></nav></header>
<div class="toolbar"><div class="tools"><div class="seg" aria-label="Map scope"><button id="overview" aria-pressed="true">Overview</button><button id="full" aria-pressed="false">Everything</button></div><input id="search" type="search" placeholder="Find any piece…" aria-label="Search every card"><select id="domain" aria-label="Filter domain"></select><label><input type="checkbox" id="failures"> Failures</label><label><input type="checkbox" id="relations"> Other links</label></div><div class="tools"><button id="undo" title="Undo edit" disabled>↶</button><button id="redo" title="Redo edit" disabled>↷</button><button id="add">+ Add piece</button></div></div>
<div class="meta-bar"><span><strong id="counts"></strong><br><span id="view-note"></span> <span id="connect-note"></span></span><div class="legend"><span>Prerequisite</span><span class="gold">Reconnection needs review</span><span class="violet">Flow / related / risk</span></div></div>
<main class="map-scroll" id="map-scroll" aria-label="Editable product dependency map"><div class="map" id="map"></div></main>
<div class="footer"><details class="color-key" id="color-key"><summary>Color key <span id="key-dots" aria-hidden="true"></span></summary><div id="key-fields" class="key-fields"></div></details><div class="footer-actions"><button class="primary" id="export">↗ Export full context</button><small id="save-state">Audited baseline</small></div></div><div class="color-menu" id="color-menu" role="dialog" aria-label="Recolor card" hidden></div><div class="toast" id="toast" role="status" hidden></div>
<dialog id="dialog"><div class="dialog-head"><div><div class="eyebrow" id="dialog-eyebrow"></div><h2 id="dialog-title"></h2></div><button id="dialog-close" aria-label="Close dialog">×</button></div><div class="dialog-content" id="dialog-content"></div></dialog><datalist id="domain-list"></datalist><datalist id="port-list"></datalist>
<script id="blueprint-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script>
<script>${read('graph-core.js')}</script><script>${read('reference-code.js')}</script><script>${read('editor.js')}</script></body></html>`;
// Source modules must never contain a literal closing-script sequence.
for(const file of ['graph-core.js','reference-code.js','editor.js'])if(/<\/script/i.test(read(file)))throw Error('Unsafe inline source '+file);
fs.writeFileSync(path.join(root,'moor-blueprint.html'),html);
console.log('Built self-contained blueprint: '+data.nodes.length+' cards / '+data.edges.length+' links / '+Buffer.byteLength(html)+' bytes');
