(function(){
 'use strict';
 const G=BlueprintGraph,R=BlueprintReference,seed=JSON.parse(document.getElementById('blueprint-data').textContent),STORE='moor-whole-blueprint-v1';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let graph=G.clone(seed),mode='overview',filter='',domain='',selected=null,expanded=new Set(),showFailures=false,showRelations=false,undo=[],redo=[],toastTimer,drawFrame,wireStart=null,previewToken=null,previewFrame=null,previewTimer;
 let recoveryNotice='';try{const saved=localStorage.getItem(STORE);if(saved){try{graph=G.validate(JSON.parse(saved));}catch(e){try{localStorage.setItem(STORE+'-damaged-'+Date.now(),saved)}catch(ignored){}recoveryNotice='Saved draft could not be read. The audited baseline is open; export it before replacing the damaged draft. '+e.message;}}}catch(e){recoveryNotice='Device storage is unavailable. Editing and downloads still work; this session is in memory.';}
 function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
 function save(){try{localStorage.setItem(STORE,JSON.stringify(graph));$('save-state').textContent='Saved on this device · revision '+graph.revision;}catch(e){$('save-state').textContent='In memory · export to keep this revision';toast('Device save failed. Export context to keep your edits.',true);}}
 function update(fn,description){try{const next=G.transact(graph,fn,description);undo.push(G.clone(graph));if(undo.length>40)undo.shift();redo=[];graph=next;save();render();return true;}catch(e){toast(e.message,true);return false;}}
 function dialog(title,content,eyebrow='MOOR / BLUEPRINT'){const d=$('dialog');if(d.open)d.close();$('dialog-title').textContent=title;$('dialog-eyebrow').textContent=eyebrow;$('dialog-content').innerHTML=content;d.showModal();}
 function list(items){return '<ul>'+(items||[]).map(x=>'<li>'+esc(typeof x==='object'?JSON.stringify(x):x)+'</li>').join('')+'</ul>';}
 function options(nodes,choose=[]){return nodes.map(n=>'<option value="'+esc(n.id)+'" '+(choose.includes(n.id)?'selected':'')+'>'+esc(n.title)+' · '+esc(n.id)+'</option>').join('');}
 function node(id){return graph.nodes.find(n=>n.id===id);}
 function visible(){const q=filter.toLowerCase().trim();return graph.nodes.filter(n=>(showFailures||n.kind!=='failure')&&(!domain||n.domain===domain)&&(!q||[n.title,n.id,n.overview,n.sourcePath,n.status].join(' ').toLowerCase().includes(q))&&(q||domain||mode==='full'||n.overviewVisible||n.kind==='failure'&&showFailures));}
 function card(n){const open=expanded.has(n.id);return '<article class="card'+(selected===n.id?' selected':'')+'" data-node="'+esc(n.id)+'" data-domain="'+esc(n.domain)+'"><button class="title" data-expand="'+esc(n.id)+'" aria-expanded="'+open+'"><span>'+esc(n.title)+'</span><span aria-hidden="true">'+(open?'−':'+')+'</span></button>'+(open?'<div class="card-body"><div class="status">'+esc(n.domain)+' · '+esc(n.status)+'</div><p>'+esc(n.overview)+'</p><div class="actions"><button data-inspect="'+esc(n.id)+'">Reason & evidence</button><button data-code="'+esc(n.id)+'">Reference code</button><button data-edit="'+esc(n.id)+'">Edit</button><button data-wire="'+esc(n.id)+'">Connect</button></div><details><summary>Why this piece?</summary><p>'+esc(n.why||'No reason recorded. Keep that gap visible until a decision is made.')+'</p>'+list(n.questions)+'</details></div>':'')+'</article>';}
 function render(){
  const ordered=G.order(graph),nodes=visible(),groups=new Map();for(const n of nodes){const level=ordered.levels.get(n.id);if(!groups.has(level))groups.set(level,[]);groups.get(level).push(n);}
  const levels=[...groups.keys()].sort((a,b)=>a-b);$('map').innerHTML='<svg class="wires" id="wires" aria-label="Dependency connections"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10" fill="#8aa99e"/></marker></defs></svg>'+(nodes.length?levels.map(level=>'<section class="level" data-level="'+level+'"><div class="row-head"><span>Build '+String(level+1).padStart(2,'0')+' · '+groups.get(level).length+' piece'+(groups.get(level).length===1?'':'s')+'</span><button data-insert-level="'+level+'">+ Insert before this row</button></div><div class="cards">'+groups.get(level).map(card).join('')+'</div></section>').join(''):'<div class="empty">No cards match. Clear your search or change the domain.</div>');
  $('counts').textContent=nodes.length+' / '+graph.nodes.length+' cards · '+graph.edges.length+' connections · '+graph.sources.length+' sources';
  $('view-note').textContent=mode==='overview'&&!filter&&!domain?'Overview. Expand a title, then inspect its detail.':'Build order calculated from prerequisites. Scroll down through later layers.';
  $('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('overview').setAttribute('aria-pressed',mode==='overview');$('full').setAttribute('aria-pressed',mode==='full');
  $('connect-note').textContent=wireStart?'Choose the destination card for '+node(wireStart)?.title+'. Esc cancels.':'';
  resize.disconnect();for(const el of document.querySelectorAll('.card,.level'))resize.observe(el);scheduleDraw();
 }
 function scheduleDraw(){cancelAnimationFrame(drawFrame);drawFrame=requestAnimationFrame(draw);}
 const resize=new ResizeObserver(scheduleDraw);
 function draw(){
  const map=$('map'),svg=$('wires');if(!svg)return;const rect=map.getBoundingClientRect(),bounds=new Map();for(const el of map.querySelectorAll('[data-node]')){const r=el.getBoundingClientRect();bounds.set(el.dataset.node,{x:r.left-rect.left,y:r.top-rect.top,w:r.width,h:r.height});}
  const edges=G.visibleEdges(graph,[...bounds.keys()]);if(showRelations)edges.push(...graph.edges.filter(e=>e.type!=='build'&&bounds.has(e.fromId)&&bounds.has(e.toId)));
  svg.setAttribute('width',map.scrollWidth);svg.setAttribute('height',map.scrollHeight);svg.setAttribute('viewBox','0 0 '+map.scrollWidth+' '+map.scrollHeight);
  svg.querySelectorAll('.wire').forEach(e=>e.remove());
  for(const e of edges){const a=bounds.get(e.fromId),b=bounds.get(e.toId);if(!a||!b)continue;const x1=a.x+a.w/2,y1=a.y+a.h,x2=b.x+b.w/2,y2=b.y,gap=Math.max(20,Math.abs(y2-y1)/2),d='M'+x1+','+y1+' C'+x1+','+(y1+gap)+' '+x2+','+(y2-gap)+' '+x2+','+y2;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class','wire'+(e.review?' review':'')+(e.type!=='build'?' other':'')+(selected===e.fromId||selected===e.toId?' highlight':''));p.setAttribute('marker-end','url(#arrow)');const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=node(e.fromId).title+' → '+node(e.toId).title+': '+e.reason;p.append(title);svg.append(p);const hit=p.cloneNode(true);hit.setAttribute('class','wire hit');hit.removeAttribute('marker-end');hit.addEventListener('click',()=>edgeDialog(e));svg.append(hit);}
 }
 function edgeDialog(e){const actual=graph.edges.find(x=>G.key(x)===G.key(e)),via=(e.via||[]).map(id=>node(id)?.title||id);dialog('Connection', '<p><strong>'+esc(node(e.fromId)?.title)+' → '+esc(node(e.toId)?.title)+'</strong></p><p>'+esc(e.reason)+'</p><p class="muted">'+esc(e.type)+' · '+esc(e.contract)+' · '+esc(e.basis)+(e.review?' · Review required':'')+'</p>'+(via.length?'<h4>Hidden prerequisites in this overview</h4>'+list(via)+'<button id="edge-reveal">Reveal full map</button>':'')+(actual?'<button id="unlink" class="danger">Remove this connection</button>':''));$('edge-reveal')?.addEventListener('click',()=>{$('dialog').close();mode='full';domain='';filter='';$('search').value='';$('domain').value='';render();});$('unlink')?.addEventListener('click',()=>{if(update(g=>g.edges=g.edges.filter(x=>G.key(x)!==G.key(actual)),'Removed connection '+G.key(actual)))$('dialog').close();});}
 function inspect(id){const n=node(id);selected=id;scheduleDraw();const sourceIds=n.sources||[],sources=sourceIds.map(id=>graph.sources.find(s=>s.id===id)).filter(Boolean),incoming=graph.edges.filter(e=>e.toId===id),outgoing=graph.edges.filter(e=>e.fromId===id);
  dialog(n.title,'<p>'+esc(n.overview)+'</p><span class="chip">'+esc(n.status)+'</span><span class="chip">'+esc(n.kind)+'</span><span class="chip">'+esc(n.id)+'</span><section><h4>Reason for this design</h4><p class="muted">'+esc(n.reasoningBasis||'Owner or source rationale; assess against evidence.')+'</p><p>'+esc(n.why||'No reason is recorded. This is an unresolved gap.')+'</p><h4>Why these alternatives were not chosen</h4>'+(n.alternatives?.length?n.alternatives.map(a=>'<p><strong>'+esc(a.choice)+'</strong> — '+esc(a.reason)+'</p>').join(''):'<p class="muted">No comparison is recorded. Do not invent one.</p>')+'<h4>Costs / limitations</h4>'+list(n.tradeoffs)+'<h4>Done means</h4>'+list(n.acceptance)+'<h4>Open questions & risks</h4>'+list([...(n.questions||[]),...(n.risks||[])])+'</section><section><h4>Contracts</h4><p>Inputs: '+esc((n.ports?.in||[]).join(', '))+'<br>Outputs: '+esc((n.ports?.out||[]).join(', '))+'</p><p class="muted">“order” connections assert sequence only. A shared port contract is a proposal until real integration proves it.</p></section><section class="columns"><div><h4>Upstream</h4>'+incoming.map(e=>connection(e,e.fromId)).join('')+'</div><div><h4>Downstream</h4>'+outgoing.map(e=>connection(e,e.toId)).join('')+'</div></section><section><h4>Evidence & attribution</h4><p class="muted">'+esc(n.provenance)+'</p>'+sources.map(s=>'<div class="list-item"><strong>'+esc(s.title)+'</strong><br><small>'+esc(s.path)+' · '+esc(s.date)+' · '+esc(s.basis)+'</small></div>').join('')+(safeSource(n)?'<p><a href="'+esc(safeSource(n))+'" target="_blank" rel="noopener">Open the existing source / implementation ↗</a></p>':'')+'</section>'+(n.specification?'<details><summary>Full recovered specification</summary><pre class="code">'+esc(JSON.stringify(n.specification,null,2))+'</pre></details>':'')+'<div class="actions"><button id="inspect-edit">Edit this card</button><button id="inspect-code" class="primary">Reference code & preview</button><button id="inspect-remove" class="danger">Remove & reconnect</button></div>');
  for(const el of $('dialog-content').querySelectorAll('[data-jump]'))el.onclick=()=>inspect(el.dataset.jump);$('inspect-edit').onclick=()=>edit(id);$('inspect-code').onclick=()=>codeDialog(id);$('inspect-remove').onclick=()=>removeDialog(id);
 }
 function connection(e,id){return '<button class="connector" data-jump="'+esc(id)+'">'+esc(node(id)?.title)+' · '+esc(e.type)+(e.review?' · review':'')+'</button>';}
 function safeSource(n){if(n.sourcePath&&/^[a-zA-Z0-9_.\/-]+$/.test(n.sourcePath)&&!n.sourcePath.startsWith('.')&&!n.sourcePath.includes('..'))return 'https://bassseamoor.github.io/render-queue/'+n.sourcePath;if(n.sourceUrl&&/^https:\/\//.test(n.sourceUrl))return n.sourceUrl;return '';}
 function edit(id=null,insertKeys=[]){const n=id?node(id):null;dialog(n?'Edit '+n.title:insertKeys.length?'Insert a responsibility':'Add a piece','<form id="card-form"><div class="columns"><label>Title<input id="edit-title" required maxlength="180" value="'+esc(n?.title||'')+'"></label><label>Domain<input id="edit-domain" required value="'+esc(n?.domain||domain||'Core')+'" list="domain-list"></label></div><label>Simple overview<textarea id="edit-overview" required>'+esc(n?.overview||'')+'</textarea></label><label>Why this choice<textarea id="edit-why">'+esc(n?.why||'')+'</textarea></label><label>Acceptance criteria · one per line<textarea id="edit-acceptance">'+esc((n?.acceptance||[]).join('\n'))+'</textarea></label><div class="columns"><label>Alternatives and reasons · one per line<textarea id="edit-alternatives">'+esc((n?.alternatives||[]).map(a=>a.choice+' :: '+a.reason).join('\n'))+'</textarea></label><label>Costs / limitations · one per line<textarea id="edit-tradeoffs">'+esc((n?.tradeoffs||[]).join('\n'))+'</textarea></label></div><label>Open questions · one per line<textarea id="edit-questions">'+esc((n?.questions||[]).join('\n'))+'</textarea></label><div class="columns"><label>Input contracts · comma separated<input id="edit-in" value="'+esc((n?.ports?.in||['contract']).join(', '))+'"></label><label>Output contracts · comma separated<input id="edit-out" value="'+esc((n?.ports?.out||['contract']).join(', '))+'"></label></div><label><input style="display:inline;width:auto" type="checkbox" id="edit-overview-visible" '+(n?.overviewVisible?'checked':'')+'> Show this card in the overview</label>'+(!n&&!insertKeys.length?'<div class="columns"><label>Build prerequisites · optional, select multiple<select id="edit-upstream" multiple>'+options(graph.nodes)+'</select></label><label>Required before · optional, select multiple<select id="edit-downstream" multiple>'+options(graph.nodes)+'</select></label></div>':'')+'<div class="actions"><button type="submit" class="primary">'+(n?'Save card':insertKeys.length?'Insert & reconnect':'Add card')+'</button><button type="button" id="cancel-edit">Cancel</button></div></form>');
  $('cancel-edit').onclick=()=>$('dialog').close();$('card-form').onsubmit=e=>{e.preventDefault();const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean),ports=id=>$(id).value.split(',').map(x=>x.trim()).filter(Boolean);const v={...(n||{}),id:n?.id||'custom:'+crypto.randomUUID(),title:$('edit-title').value.trim(),overview:$('edit-overview').value.trim(),domain:$('edit-domain').value.trim(),why:$('edit-why').value.trim(),acceptance:lines('edit-acceptance'),questions:lines('edit-questions'),tradeoffs:lines('edit-tradeoffs'),alternatives:lines('edit-alternatives').map(x=>{const at=x.indexOf(' :: ');return at<0?{choice:x,reason:'No reason recorded.'}:{choice:x.slice(0,at),reason:x.slice(at+4)}}),ports:{in:ports('edit-in'),out:ports('edit-out')},overviewVisible:$('edit-overview-visible').checked,status:n?.status||'Owner proposal',kind:n?.kind||'feature',sources:n?.sources||['user'],provenance:n?.provenance||'owner addition',reference:n?.reference||null};if(!v.title||!v.overview)return toast('Title and overview are required.',true);const up=$('edit-upstream')?[...$('edit-upstream').selectedOptions].map(o=>o.value):[],down=$('edit-downstream')?[...$('edit-downstream').selectedOptions].map(o=>o.value):[];if(update(g=>{if(n)g.nodes[g.nodes.findIndex(x=>x.id===id)]=v;else if(insertKeys.length)G.insert(g,v,insertKeys);else{g.nodes.push(v);for(const p of up)G.addEdge(g,p,v.id);for(const c of down)G.addEdge(g,v.id,c);}},(n?'Edited ':insertKeys.length?'Inserted ':'Added ')+v.title)){$('dialog').close();expanded.add(v.id);selected=v.id;if(!v.overviewVisible)mode='full';filter='';domain='';$('search').value='';$('domain').value='';refreshDomains();render();}}
 }
 function insertRow(level){const visibleIds=new Set(visible().map(n=>n.id)),levels=G.order(graph).levels,edges=graph.edges.filter(e=>e.type==='build'&&levels.get(e.fromId)<level&&levels.get(e.toId)>=level&&(visibleIds.has(e.fromId)||visibleIds.has(e.toId)));if(!edges.length){toast('This row has no incoming build connections. Add a card and choose its prerequisites.');return edit();}dialog('Insert between build rows','<p>Choose the actual prerequisite connections to split. Other branches retain their own order.</p><form id="insert-form">'+edges.map((e,i)=>'<label><input type="checkbox" name="split" value="'+esc(G.key(e))+'" style="width:auto;display:inline" '+(edges.length===1?'checked':'')+'> '+esc(node(e.fromId).title)+' → '+esc(node(e.toId).title)+' <small>('+esc(e.contract)+')</small></label>').join('')+'<button class="primary">Continue to new card</button></form>');$('insert-form').onsubmit=e=>{e.preventDefault();const keys=[...$('insert-form').querySelectorAll('input:checked')].map(x=>x.value);if(!keys.length)return toast('Select a connection to insert between.',true);edit(null,keys);};}
 function removeDialog(id){const n=node(id),a=graph.edges.filter(e=>e.toId===id&&e.type==='build'),b=graph.edges.filter(e=>e.fromId===id&&e.type==='build');dialog('Remove '+n.title,'<p>The map will consolidate '+a.length+' upstream × '+b.length+' downstream build connections. Compatible order links reconnect; incompatible ports remain unresolved.</p><p>Its code, specification and connections remain in the export’s tombstones. Any replacement responsibilities are marked for review. You can undo this.</p><button id="confirm-remove" class="danger">Remove & reconnect</button>');$('confirm-remove').onclick=()=>{if(update(g=>G.remove(g,id),'Removed '+n.title+'; reconnected compatible order links')){$('dialog').close();expanded.delete(id);selected=null;toast('Removed. Replacement obligations are flagged in amber; the original remains in history.');}};}
 function connectDialog(fromId,toId){if(fromId===toId)return toast('Choose a different destination.',true);dialog('Connect pieces','<p>'+esc(node(fromId).title)+' → '+esc(node(toId).title)+'</p><form id="connection-form"><label>Relationship<select id="connection-type">'+G.types.map(t=>'<option>'+t+'</option>').join('')+'</select></label><label>Contract<input id="connection-contract" value="order" list="port-list"></label><label>Why is this link needed?<textarea id="connection-reason" required></textarea></label><p class="muted">Build edges change execution order and must be acyclic. Flow, containment, related and risk edges describe other relationships. Typed build contracts must exist on both ports.</p><button class="primary">Connect</button></form>');$('connection-form').onsubmit=e=>{e.preventDefault();if(update(g=>G.addEdge(g,fromId,toId,$('connection-type').value,$('connection-contract').value.trim(),$('connection-reason').value.trim()),'Connected '+fromId+' → '+toId))$('dialog').close();};}
 function codeDialog(id){const n=node(id);dialog(n.title+' · reference','<p class="muted">Generate an executable mechanism example, or paste the exact HTML/CSS/JavaScript you want rendered. This preview runs independently of the blueprint. It cannot read host state or fetch external libraries. Keep secrets out of exported code.</p><div class="actions"><button id="generate-code">Generate reference</button><button id="json-example">Structured UI example</button><button id="run-code" class="primary">Save & render</button><button id="download-code">Download code</button></div><label style="margin-top:15px">HTML or moor.reference-ui JSON<textarea id="reference-code" class="code" spellcheck="false"></textarea></label><div id="reference-status" class="preview-status" role="status">No code has run yet.</div><iframe id="reference-preview" class="preview" title="Isolated reference preview" sandbox="allow-scripts allow-downloads" referrerpolicy="no-referrer"></iframe><details><summary>What a reference proves</summary><p>The code below is actually executed. A clean render proves it loaded, while behavior still needs assessment. Generated examples demonstrate one mechanism; they do not implement the entire feature or production integrations.</p></details>');$('reference-code').value=n.reference||R.generate(n);
  $('generate-code').onclick=()=>{$('reference-code').value=R.generate(n);toast('Generated an editable executable example. Save & render to run it.');};$('json-example').onclick=()=>{$('reference-code').value=JSON.stringify({schema:'moor.reference-ui',version:1,title:n.title,description:n.overview,state:{count:0,items:[]},blocks:[{type:'text',text:'Counter: {{count}}'},{type:'input',key:'new',label:'New item'},{type:'button',label:'Add item',action:{type:'append',key:'items',from:'new'}},{type:'button',label:'Count',action:{type:'increment',key:'count'}},{type:'list',key:'items'}]},null,2);};$('run-code').onclick=()=>{const code=$('reference-code').value;try{R.compile(code);if(!update(g=>g.nodes.find(n=>n.id===id).reference=code,'Saved reference code for '+n.title))return;previewFrame=$('reference-preview');previewToken=crypto.randomUUID();$('reference-status').textContent='Rendering…';delete $('reference-status').dataset.failed;previewFrame.srcdoc=R.isolate(code,previewToken);clearTimeout(previewTimer);previewTimer=setTimeout(()=>{if($('reference-status')?.textContent==='Rendering…')$('reference-status').textContent='No ready receipt. The preview may be blocked or code may be stalled.';},4000);}catch(e){$('reference-status').textContent=e.message;toast(e.message,true);}};$('download-code').onclick=()=>download(n.id.replace(/[^\w-]/g,'-')+'-reference.'+($('reference-code').value.trim().startsWith('{')?'json':'html'),$('reference-code').value,'text/plain');
 }
 window.addEventListener('message',e=>{if(e.source!==previewFrame?.contentWindow||e.data?.type!=='moor:reference'||e.data.token!==previewToken)return;const status=$('reference-status');if(!status)return;clearTimeout(previewTimer);if(e.data.kind==='error'){status.dataset.failed='true';status.textContent='Runtime error: '+String(e.data.message).slice(0,1200);}else if(!status.dataset.failed)status.textContent=String(e.data.message).slice(0,1200);});
 function offer(){dialog('A place that stays yours','<section><h4>The transparent offer</h4><p>'+esc(graph.offer.consumer)+'</p><p>'+esc(graph.offer.owner)+'</p><p>'+esc(graph.offer.creator)+'</p><p class="muted">'+esc(graph.offer.assistant)+'</p></section><table><thead><tr><th>Party</th><th>What they gain</th><th>What they give / risk</th></tr></thead><tbody>'+graph.offer.parties.map(p=>'<tr><td><strong>'+esc(p.party)+'</strong></td><td>'+list(p.gains)+'</td><td>'+list(p.costs)+'</td></tr>').join('')+'</tbody></table><section style="margin-top:24px"><h4>Promises this blueprint does not make</h4>'+list(graph.offer.notPromises)+'</section><h4>Decisions you can assess</h4>'+graph.decisions.map(d=>'<div class="decision"><strong>'+esc(d.title)+'</strong><p class="muted">'+esc(d.reason)+'</p><span class="chip">'+esc(d.state)+'</span>'+(d.options?'<label>Your decision<select data-decision="'+esc(d.id)+'"><option value="">Keep open</option>'+d.options.map(o=>'<option '+(d.resolution===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select></label>':'<label>Your resolution<input data-resolution="'+esc(d.id)+'" value="'+esc(d.resolution||'')+'" placeholder="Record a decision or keep it open"></label>')+'</div>').join('')+'<button id="save-decisions" class="primary">Save decisions</button>');$('save-decisions').onclick=()=>{const choices=[...$('dialog-content').querySelectorAll('[data-decision],[data-resolution]')].map(el=>({id:el.dataset.decision||el.dataset.resolution,value:el.value}));if(update(g=>{for(const c of choices){const d=g.decisions.find(d=>d.id===c.id);d.resolution=c.value;d.state=c.value?'owner-resolved':d.state==='owner-resolved'?'open':d.state;}},'Recorded owner product decisions'))toast('Decisions saved and included in the next context export.');};}
 function audit(){dialog('What was audited','<p>'+esc(graph.audit.statement)+'</p><div class="inline">'+Object.entries(graph.audit).filter(([k,v])=>typeof v==='number').map(([k,v])=>'<span class="chip">'+esc(k)+': '+v+'</span>').join('')+'</div><h4 style="margin-top:20px">Limits and contradictions</h4>'+list(graph.audit.limits)+'<h4>Audit process</h4>'+list(graph.audit.process)+'<p class="muted">'+esc(graph.audit.meaningOfEverything)+'</p><h4>Source ledger</h4>'+graph.sources.map(s=>'<div class="list-item"><strong>'+esc(s.title)+'</strong><br><small>'+esc(s.path)+' · '+esc(s.date)+'<br>'+esc(s.basis)+'</small></div>').join('')+'<details><summary>All '+graph.inventory.length+' repository paths, including unmapped support files</summary><input id="inventory-search" type="search" placeholder="Search file paths"><div id="inventory-results"></div></details>');const show=()=>{const q=$('inventory-search').value.toLowerCase();$('inventory-results').innerHTML=graph.inventory.filter(i=>i.path.toLowerCase().includes(q)).map(i=>'<div class="list-item"><strong>'+esc(i.path)+'</strong><br><small>'+esc(i.mappedTo.length?'Mapped to '+i.mappedTo.join(', '):'Support/source asset; no independent feature card inferred.')+'</small></div>').join('')};$('inventory-search').oninput=show;show();}
 function execution(){const order=G.order(graph);dialog('Execution blueprint','<p>Order is calculated from build prerequisites. A later layer may contain parallel work. Source presence, successful preview and production verification are different states.</p>'+graph.execution.map((s,i)=>'<section><h3>'+String(i+1).padStart(2,'0')+' · '+esc(s.step)+'</h3><p>'+esc(s.proof)+'</p></section>').join('')+'<h4>Current build layers</h4>'+[...new Set(order.levels.values())].sort((a,b)=>a-b).map(l=>'<details><summary>Build '+(l+1)+' · '+graph.nodes.filter(n=>order.levels.get(n.id)===l&&n.kind!=='failure').length+' cards</summary>'+list(graph.nodes.filter(n=>order.levels.get(n.id)===l&&n.kind!=='failure').map(n=>n.title+' ['+n.status+']'))+'</details>').join('')+'<h4>Removed responsibilities</h4>'+(graph.tombstones?.length?graph.tombstones.map(t=>'<details><summary>'+esc(t.node.title)+' · '+esc(t.removedAt)+'</summary><p>'+esc(t.node.overview)+'</p>'+list(t.unresolved.map(e=>e.fromId+' → '+e.toId+': incompatible '+e.contract))+'</details>').join(''):'<p class="muted">Nothing removed.</p>'));}
 function packageContext(){const out=G.clone(graph);out.exportedAt=new Date().toISOString();out.handoff={instruction:'Build the next version from this exact state. Preserve IDs, typed connections, edits, reference code, provenance, unresolved decisions, failures and tombstones. First verify the selected output against rawIntent. Do not replace the active production JS compiler with the Rust reference compiler. Do not claim untested integrations as complete.',rawIntent:seed.rawIntent||'Whole-product editable MOOR blueprint. Everything in the audited corpus, title-only cards, expandable overviews/reasons/failures, add/remove/insert with correct dependency rewiring, executable reference code, complete context export, Bin and Funnel registration.',buildOrder:G.order(graph).ids.filter(id=>node(id)?.kind!=='failure'),removedObligations:(graph.tombstones||[]).map(t=>({id:t.node.id,title:t.node.title,unresolved:t.unresolved})),sourceScope:graph.audit.statement,referencePolicy:'Every reference runs independently in an isolated sandbox. Generated examples are mechanism prototypes; production scope still requires all acceptance criteria.'};for(const n of out.nodes){if(!n.reference)n.reference=R.generate(n);n.referenceOrigin=graph.nodes.find(x=>x.id===n.id)?.reference?'owner-stored':'generated mechanism example';}return out;}
 function exportDialog(){const context=packageContext(),text=JSON.stringify(context,null,2);dialog('Full context → next version','<p>The export includes every card and connection, generated/stored executable references, decisions, source ledger, audit scope, full recovered app specifications, failures, tombstones and build order. Filters do not remove content.</p><div class="actions"><button id="copy-context" class="primary">Copy full context</button><button id="download-context">Download JSON</button><button id="download-brief">Download build brief</button></div><label style="margin-top:17px">Complete pasteable context<textarea id="context-text" class="code" readonly></textarea></label><small>'+context.nodes.length+' cards · '+context.edges.length+' links · '+(text.length/1024/1024).toFixed(2)+' MB. If your next builder cannot accept the whole paste, attach the JSON file.</small>');$('context-text').value=text;$('copy-context').onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('Full context copied.');}catch(e){$('context-text').focus();$('context-text').select();toast('Clipboard unavailable. The complete context is selected for manual copy.');}};$('download-context').onclick=()=>download('moor-whole-blueprint-r'+graph.revision+'.json',text,'application/json');$('download-brief').onclick=()=>download('moor-next-build-r'+graph.revision+'.md','# MOOR — next version\n\n'+context.handoff.instruction+'\n\n## Offer\n\n'+graph.offer.consumer+'\n\n## Owner decisions\n\n'+graph.decisions.map(d=>'- '+d.title+': '+(d.resolution||d.state)+'. '+d.reason).join('\n')+'\n\n## Full context\n\n```json\n'+text+'\n```\n','text/markdown');}
 function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function importDialog(){dialog('Import a version','<p>Paste a full exported blueprint or choose its JSON file. A valid import becomes a new editable draft; undo restores the prior one. Cycles, missing IDs and incompatible build ports are rejected before replacement.</p><input id="import-file" type="file" accept=".json,application/json"><label style="margin-top:15px">Blueprint JSON<textarea id="import-text" class="code" spellcheck="false"></textarea></label><button id="import-apply" class="primary">Validate & import</button>');$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(file){if(file.size>40*1024*1024)return toast('File exceeds 40 MB.',true);$('import-text').value=await file.text();}};$('import-apply').onclick=()=>{try{const next=G.validate(JSON.parse($('import-text').value));for(const k of ['audit','offer','decisions','sources','inventory','execution'])if(!next[k])throw Error('This is not a full context export: missing '+k);undo.push(G.clone(graph));redo=[];graph=G.clone(next);graph.revision=(graph.revision||0)+1;expanded.clear();selected=null;save();refreshDomains();render();$('dialog').close();toast('Version imported. Your prior draft is available through Undo.');}catch(e){toast('Import rejected: '+e.message,true);}};}
 function refreshDomains(){const previous=$('domain').value;const domains=[...new Set(graph.nodes.map(n=>n.domain))].sort();$('domain').innerHTML='<option value="">All domains</option>'+domains.map(d=>'<option>'+esc(d)+'</option>').join('');$('domain').value=domains.includes(previous)?previous:'';$('domain-list').innerHTML=domains.map(d=>'<option>'+esc(d)+'</option>').join('');$('port-list').innerHTML=[...new Set(['order',...graph.nodes.flatMap(n=>[...(n.ports?.in||[]),...(n.ports?.out||[])])])].map(p=>'<option>'+esc(p)+'</option>').join('');}
 $('map').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const id=button.dataset.expand||button.dataset.inspect||button.dataset.code||button.dataset.edit||button.dataset.wire;if(wireStart&&id){const from=wireStart;wireStart=null;render();return connectDialog(from,id);}if(button.dataset.expand){selected=id;if(expanded.has(id))expanded.delete(id);else expanded.add(id);render();}else if(button.dataset.inspect)inspect(id);else if(button.dataset.code)codeDialog(id);else if(button.dataset.edit)edit(id);else if(button.dataset.wire){wireStart=id;render();toast('Select the destination card.');}else if(button.dataset.insertLevel!=null)insertRow(Number(button.dataset.insertLevel));});
 $('overview').onclick=()=>{mode='overview';render();};$('full').onclick=()=>{mode='full';render();};$('search').oninput=()=>{filter=$('search').value;render();};$('domain').onchange=()=>{domain=$('domain').value;render();};$('failures').onchange=()=>{showFailures=$('failures').checked;render();};$('relations').onchange=()=>{showRelations=$('relations').checked;render();};$('add').onclick=()=>edit();$('offer').onclick=offer;$('audit').onclick=audit;$('execution').onclick=execution;$('export').onclick=exportDialog;$('import').onclick=importDialog;
 $('undo').onclick=()=>{if(!undo.length)return;redo.push(G.clone(graph));graph=undo.pop();save();refreshDomains();render();toast('Edit undone.');};$('redo').onclick=()=>{if(!redo.length)return;undo.push(G.clone(graph));graph=redo.pop();save();refreshDomains();render();toast('Edit restored.');};
 $('dialog-close').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>{clearTimeout(previewTimer);previewToken=null;if(previewFrame){previewFrame.srcdoc='';previewFrame=null;}});window.addEventListener('resize',scheduleDraw);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&wireStart){wireStart=null;render();toast('Connection cancelled.');}});
 refreshDomains();G.validate(graph);render();if(recoveryNotice){$('save-state').textContent='Recovery / in-memory draft';toast(recoveryNotice,true);}else $('save-state').textContent='Device draft · revision '+graph.revision;
 // Read-only diagnostics. No host execution of imported code.
 window.MoorBlueprint={snapshot:()=>G.clone(graph),context:packageContext,version:1};
})();
