/* Shared pipeline: evidence -> answers -> constraints -> opinions -> next question.
   NONE is a transparent rules compiler, not a language model or implementation test. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BlueprintFunnel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const models=['GPT','MUSE','COPI','LOCAL','NONE','OTHER'],lanes=models.slice(0,5),grades={
 ruby:{label:'Blocked',meaning:'A required condition prevents progress.'},coral:{label:'Rejected',meaning:'The owner has explicitly excluded this direction.'},copper:{label:'Needs evidence',meaning:'A claim needs supporting evidence.'},amber:{label:'Conflict',meaning:'Current decisions or obligations disagree.'},olive:{label:'Partly clear',meaning:'Some required decisions remain unanswered.'},lime:{label:'Ready to try',meaning:'The direction is clear enough for an experiment.'},emerald:{label:'Aligned',meaning:'Submitted answers are consistent under this reviewer’s checks; never means built.'},teal:{label:'Accepted tradeoff',meaning:'A limitation is understood and explicitly accepted.'},cyan:{label:'Exploring',meaning:'Several options remain in consideration.'},sky:{label:'Clarifying',meaning:'Answers are accumulating.'},blue:{label:'Specified',meaning:'A concrete contract is recorded.'},indigo:{label:'Needs review',meaning:'An owner decision or peer review is requested.'},violet:{label:'Stale',meaning:'The reviewed snapshot changed; compile again.'},purple:{label:'Deferred',meaning:'The owner chose to revisit this later.'},magenta:{label:'Reviewer disagreement',meaning:'Reviewers differ on alignment.'},slate:{label:'Unreviewed',meaning:'No current opinion has been submitted.'}};
const clone=x=>JSON.parse(JSON.stringify(x));const hash=s=>{let a=2166136261,b=5381;for(let i=0;i<s.length;i++){a=Math.imul(a^s.charCodeAt(i),16777619);b=Math.imul(b,33)^s.charCodeAt(i);}return (a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0');};
const qid=(id,key)=>id+'::'+key;
function ensure(g){if(!g.funnel)g.funnel={version:1,answers:{},answerHistory:[],opinions:{},customQuestions:[],resolutions:[],learnedRules:[],requests:{},receipts:[],cadence:{},cursor:null,questionEpoch:0,questionLog:[]};return g.funnel;}
function questions(g,id){const n=g.nodes.find(n=>n.id===id);if(!n)return [];const make=(key,prompt,field,options=[],required=true,factKey=null)=>({id:qid(id,key),nodeId:id,key,prompt,field,options,required,factKey});
const qs=[make('outcome','What should “'+n.title+'” actually do for someone?','overview'),make('reason','Why should this piece exist, and what would you choose instead?','why'),make('proof','What visible behavior would convince you this works?','acceptance'),make('scope','When does this belong in MOOR OS?',null,['Core now','Optional now','Later','Exclude']),make('runtime','What does this piece need to run?',null,['Offline','Cloud required','Either'],true,id+'.runtime'),make('visibility','Who should be able to access it by default?',null,['Private','Public','Explicit choice'],true,id+'.visibility'),make('ai','Does this piece require a language model?',null,['No LLM required','LLM required','Optional LLM'],true,id+'.ai'),make('risk','What cost, limitation, or failure are you willing to accept?','tradeoffs')];
if(id==='offer'||id==='boundaries'){qs.push(make('offline-policy','Must the core remain usable without cloud services?',null,['Core offline','Cloud allowed'],true,'policy.offline'));qs.push(make('privacy-policy','What is the default visibility across MOOR OS?',null,['Private','Public','Explicit choice'],true,'policy.privacy'));qs.push(make('ai-policy','Must core operation work without a language model?',null,['No LLM required','LLM required'],true,'policy.ai'));}
for(const prompt of n.questions||[])qs.push(make('open-'+hash(String(prompt)),String(prompt),null,[],false));
for(const q of g.funnel?.customQuestions||[])if(q.nodeId===id)qs.push({...q,options:[],required:false,field:null});const epoch=(g.funnel?.questionEpoch||0)%3,up=g.edges.filter(e=>e.toId===id).map(e=>g.nodes.find(n=>n.id===e.fromId)?.title).filter(Boolean).slice(0,3).join(', ')||'the product intent';const variations={outcome:['What is the first useful action someone takes with '+n.title+'?','What should '+n.title+' change or produce, and for whom?'],reason:['Why does '+n.title+' belong after '+up+'?','Which alternative to '+n.title+' would you reject, and why?'],proof:['What test would expose a false success in '+n.title+'?','What observable result must '+n.title+' produce from '+(n.ports?.in||[]).join(', ')+'?'],risk:['What should happen when '+n.title+' fails or loses access to a dependency?','Which limitation of '+n.title+' should be visible to its user?']};for(const q of qs){const a=g.funnel?.answers?.[q.id];if(a)q.prompt=a.prompt;else if(epoch&&variations[q.key])q.prompt=variations[q.key][epoch-1];else if(epoch)q.prompt='For the current '+n.title+' design: '+q.prompt;}return qs;
}
function catalog(g){return g.nodes.flatMap(n=>questions(g,n.id));}
function answer(g,q,value){const f=ensure(g);if(!q||!questions(g,q.nodeId).some(x=>x.id===q.id))throw Error('Question no longer exists.');const text=String(value.text||'').trim(),choice=value.choice||null;if(text.length>20000)throw Error('Keep an answer under 20,000 characters.');if(value.state!=='deferred'&&!text&&!choice)throw Error('Choose an option or write an answer.');if(choice&&!q.options.includes(choice))throw Error('Unknown answer choice.');const prior=f.answers[q.id];if(prior)f.answerHistory.push(clone(prior));const a={questionId:q.id,nodeId:q.nodeId,prompt:q.prompt,text,choice,state:value.state==='deferred'?'deferred':'answered',factKey:q.factKey||null,sequence:(f.sequence||0)+1,at:new Date().toISOString()};f.sequence=a.sequence;f.answers[q.id]=a;f.cursor=q.id;return a;}
function applyAnswer(g,q){const a=g.funnel?.answers[q.id],n=g.nodes.find(n=>n.id===q.nodeId);if(!a||!n||!q.field||!a.text)throw Error('This answer cannot be applied to a card field.');if(['acceptance','tradeoffs'].includes(q.field))n[q.field]=a.text.split('\n').map(x=>x.trim()).filter(Boolean);else n[q.field]=a.text;}
function snapshot(g){const f=g.funnel||{};return hash(JSON.stringify({nodes:g.nodes.map(n=>({id:n.id,title:n.title,overview:n.overview,why:n.why,acceptance:n.acceptance,tradeoffs:n.tradeoffs,questions:n.questions,ports:n.ports,parent:n.parent,status:n.status,reference:n.reference})),edges:g.edges,offer:g.offer,decisions:g.decisions,answers:Object.values(f.answers||{}).sort((a,b)=>a.questionId.localeCompare(b.questionId)),resolutions:f.resolutions||[],learnedRules:f.learnedRules||[],customQuestions:f.customQuestions||[],questionEpoch:f.questionEpoch||0}));}
function clashes(g){const f=g.funnel||{},alive=new Set(g.nodes.map(n=>n.id)),as=Object.values(f.answers||{}).filter(a=>a.state==='answered'&&alive.has(a.nodeId)),byFact=new Map(),out=[];
const add=(key,items,reason)=>{const id='conflict:'+hash(key+items.map(a=>a.questionId+':'+a.sequence).sort().join('|'));const resolution=(f.resolutions||[]).find(r=>r.conflictId===id);if(!resolution)out.push({id,key,nodeIds:[...new Set(items.map(a=>a.nodeId))],questionIds:items.map(a=>a.questionId),reason,values:items.map(a=>({questionId:a.questionId,choice:a.choice,text:a.text}))});};
for(const a of as)if(a.factKey&&a.choice){if(!byFact.has(a.factKey))byFact.set(a.factKey,[]);byFact.get(a.factKey).push(a);}for(const [key,items] of byFact)if(key.startsWith('policy.')&&new Set(items.map(a=>a.choice)).size>1)add(key,items,'Different answers set different global values for '+key+'.');
const offline=as.filter(a=>a.factKey==='policy.offline'&&a.choice==='Core offline');for(const a of as.filter(a=>a.choice==='Cloud required')){const scope=f.answers[qid(a.nodeId,'scope')];if(scope?.choice==='Core now'&&offline.length)add('core-cloud:'+a.nodeId,[...offline,a,scope],'A core component requires cloud services while core operation is required offline.');}
const noAI=as.filter(a=>a.factKey==='policy.ai'&&a.choice==='No LLM required');for(const a of as.filter(a=>a.factKey===a.nodeId+'.ai'&&a.choice==='LLM required')){const scope=f.answers[qid(a.nodeId,'scope')];if(scope?.choice==='Core now'&&noAI.length)add('core-ai:'+a.nodeId,[...noAI,a,scope],'A core component requires an LLM while the core must work without one.');}
const priv=as.filter(a=>a.factKey==='policy.privacy'&&a.choice==='Private');for(const a of as.filter(a=>a.factKey===a.nodeId+'.visibility'&&a.choice==='Public'))if(priv.length){const scope=f.answers[qid(a.nodeId,'scope')];if(scope?.choice==='Core now')add('private-public:'+a.nodeId,[...priv,a,scope],'This core component defaults public while the product default is private. An explicit exception is needed.');}
for(const rule of f.learnedRules||[]){const a=f.answers[rule.questionId];if(a?.state==='answered'&&a.choice&&a.choice!==rule.choice)add('learned:'+rule.questionId,[a],'A new answer differs from the owner’s learned resolution: '+rule.choice+'.');}
return out;
}
function resolve(g,conflictId,action,note){const f=ensure(g),c=clashes(g).find(c=>c.id===conflictId);if(!c)throw Error('Conflict is no longer current.');if(!String(note||'').trim())throw Error('Record why this resolution is valid.');if(action==='exception')f.resolutions.push({conflictId,action,note:note.trim(),at:new Date().toISOString()});else if(action==='prefer-latest'){const items=c.questionIds.map(id=>f.answers[id]).filter(Boolean).sort((a,b)=>b.sequence-a.sequence),chosen=items[0];if(!c.key.startsWith('policy.'))throw Error('For component conflicts, edit the implicated answers or record an explicit exception.');for(const a of items){if(a.choice!==chosen.choice){f.answerHistory.push(clone(a));a.choice=chosen.choice;a.sequence=++f.sequence;a.at=new Date().toISOString();}f.learnedRules=f.learnedRules.filter(r=>r.questionId!==a.questionId);f.learnedRules.push({questionId:a.questionId,choice:chosen.choice,note:note.trim()});}f.resolutions.push({conflictId,action,note:note.trim(),at:new Date().toISOString()});}else throw Error('Unknown resolution.');}
function compileNone(g){const f=ensure(g),snap=snapshot(g),conflicts=clashes(g);for(const n of g.nodes){const qs=questions(g,n.id),required=qs.filter(q=>q.required),answered=required.filter(q=>f.answers[q.id]?.state==='answered'),deferred=required.filter(q=>f.answers[q.id]?.state==='deferred'),cs=conflicts.filter(c=>c.nodeIds.includes(n.id)),scope=f.answers[qid(n.id,'scope')];let colorId=cs.length?'amber':scope?.choice==='Exclude'?'coral':answered.length===required.length?'emerald':answered.length?'olive':deferred.length?'purple':'slate';if(!f.opinions[n.id])f.opinions[n.id]={};f.opinions[n.id].NONE={model:'NONE',nodeId:n.id,colorId,reason:cs.length?cs.map(c=>c.reason).join(' '):answered.length+'/'+required.length+' essential questions answered. '+(colorId==='emerald'?'No explicit rule conflict detected; prose has not been semantically verified.':'This is a clarity opinion, not implementation status.'),answerIds:qs.filter(q=>f.answers[q.id]?.state==='answered').map(q=>q.id),conflicts:cs,snapshotId:snap,at:new Date().toISOString()};}f.lastNone={snapshotId:snap,at:new Date().toISOString()};return conflicts;}
function view(g){const snap=snapshot(g),f=g.funnel||{},result={},counts={answered:0,deferred:0,total:0,clear:0,conflicts:0};const cs=clashes(g);counts.conflicts=cs.length;for(const n of g.nodes){const qs=questions(g,n.id),answered=qs.filter(q=>f.answers?.[q.id]?.state==='answered').length,deferred=qs.filter(q=>f.answers?.[q.id]?.state==='deferred').length;counts.answered+=answered;counts.deferred+=deferred;counts.total+=qs.length;const opinions={};for(const model of models){const o=f.opinions?.[n.id]?.[model];if(o)opinions[model]={...o,stale:o.snapshotId!==snap,displayColor:o.snapshotId!==snap?'violet':o.colorId};}if(opinions.NONE?.displayColor==='emerald')counts.clear++;result[n.id]={answered,deferred,total:qs.length,opinions};}return {snapshotId:snap,cards:result,counts,conflicts:cs};}
function next(g,focus=null,skip=[]){const f=g.funnel||{},cs=clashes(g),touched=new Set(cs.flatMap(c=>c.nodeIds)),qs=(focus?questions(g,focus):catalog(g)).filter(q=>!skip.includes(q.id));const pending=qs.filter(q=>!f.answers?.[q.id]);const covered=new Set(Object.values(f.answers||{}).filter(a=>a.state==='answered').map(a=>a.nodeId));pending.sort((a,b)=>Number(covered.has(a.nodeId))-Number(covered.has(b.nodeId))||Number(touched.has(b.nodeId))-Number(touched.has(a.nodeId))||Number(b.required)-Number(a.required)||Number(!!g.nodes.find(n=>n.id===b.nodeId)?.overviewVisible)-Number(!!g.nodes.find(n=>n.id===a.nodeId)?.overviewVisible));return pending[0]||qs.find(q=>f.answers?.[q.id]?.state==='deferred')||qs[0]||null;}
function packet(g,model,targetIds,runId){if(!models.includes(model)||model==='NONE')throw Error('Select an external reviewer.');const f=ensure(g),ids=targetIds||g.nodes.map(n=>n.id);if(!ids.length||ids.some(id=>!g.nodes.some(n=>n.id===id)))throw Error('Choose existing cards to review.');const snap=snapshot(g);const request={runId,model,snapshotId:snap,nodeIds:ids,at:new Date().toISOString()};f.requests[model]=request;return {schema:'moor.funnel-review-request',version:1,...request,instruction:'Review the entire connected architecture and all current owner answers. Produce one opinion per requested node, never claim built or done. Find explicit and semantic contradictions, cite exact answer IDs, explain uncertain gaps, and propose focused follow-up questions. Return ONLY JSON matching responseSchema. Do not alter owner answers or code. Grades are opinions on clarity/alignment. Each model has one replaceable opinion per card. Do not fabricate another model’s opinion.',pipeline:['Original intent and architecture','Submitted owner answers','Learned resolutions','Conflict analysis','Per-component opinion color','Next question'],originalIntent:g.clarityIntent||g.rawIntent,offer:g.offer,decisions:g.decisions,grades,components:g.nodes.map(n=>({id:n.id,title:n.title,domain:n.domain,kind:n.kind,status:n.status,overview:n.overview,why:n.why,acceptance:n.acceptance,tradeoffs:n.tradeoffs,questions:n.questions,ports:n.ports,parent:n.parent,sources:n.sources})),connections:g.edges,answers:Object.values(f.answers).filter(a=>g.nodes.some(n=>n.id===a.nodeId)),resolutions:f.resolutions,learnedRules:f.learnedRules,currentOpinions:f.opinions,sourceLedger:g.sources,responseSchema:{schema:'moor.funnel-opinions',version:1,model,runId,snapshotId:snap,opinions:[{nodeId:ids[0],colorId:'olive',reason:'Explain this opinion using the actual answers.',answerIds:[],conflicts:[{nodeIds:[ids[0]],questionIds:[],reason:'Exact contradiction, if any.',proposal:'An owner decision that could resolve it.'}]}],questions:[{nodeId:ids[0],prompt:'One specific follow-up question.'}]}};}
function parseReply(raw){let text=String(raw).trim();if(text.startsWith('```'))text=text.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');try{return JSON.parse(text);}catch{throw Error('Paste valid JSON from the selected model.');}}
function importReply(g,model,raw){const r=typeof raw==='string'?parseReply(raw):raw,f=ensure(g),request=f.requests[model];if(!request)throw Error('Copy a context packet for this model first.');if(!r||r.schema!=='moor.funnel-opinions'||r.version!==1||r.model!==model||r.runId!==request.runId||r.snapshotId!==request.snapshotId)throw Error('Response model, run, or snapshot does not match its context packet.');if(r.snapshotId!==snapshot(g))throw Error('Answers or architecture changed since this packet. Copy fresh context and recompile.');if(!Array.isArray(r.opinions)||!r.opinions.length||r.opinions.length>g.nodes.length)throw Error('Expected per-component opinions.');const live=new Set(g.nodes.map(n=>n.id)),wanted=new Set(request.nodeIds),seen=new Set(),answerIds=new Set(Object.keys(f.answers));
for(const o of r.opinions){if(!o||!live.has(o.nodeId)||!wanted.has(o.nodeId)||seen.has(o.nodeId)||!grades[o.colorId]||typeof o.reason!=='string'||!o.reason.trim()||o.reason.length>12000)throw Error('Invalid or duplicate component opinion.');seen.add(o.nodeId);if(o.colorId==='amber'&&!(o.conflicts||[]).length)throw Error('A conflict grade needs a specific conflict.');if(o.colorId==='emerald'&&(o.conflicts||[]).length)throw Error('An aligned grade cannot contain unresolved conflicts.');if(!Array.isArray(o.answerIds)||o.answerIds.some(id=>!answerIds.has(id)))throw Error('Opinion cites an unknown answer.');if(o.conflicts!=null&&(!Array.isArray(o.conflicts)||o.conflicts.length>100))throw Error('Invalid conflicts.');for(const c of o.conflicts||[])if(!Array.isArray(c.nodeIds)||!c.nodeIds.length||c.nodeIds.some(id=>!live.has(id))||!Array.isArray(c.questionIds)||c.questionIds.some(id=>!answerIds.has(id))||typeof c.reason!=='string'||!c.reason.trim()||typeof c.proposal!=='string')throw Error('Conflict needs valid affected nodes, answer IDs, a reason and a proposal.');}
if(r.questions!=null&&(!Array.isArray(r.questions)||r.questions.length>1000))throw Error('Invalid follow-up questions.');for(const q of r.questions||[])if(!q||!live.has(q.nodeId)||typeof q.prompt!=='string'||!q.prompt.trim()||q.prompt.length>2000)throw Error('Invalid follow-up question.');
for(const o of r.opinions){if(!f.opinions[o.nodeId])f.opinions[o.nodeId]={};f.opinions[o.nodeId][model]={...clone(o),model,snapshotId:r.snapshotId,runId:r.runId,at:new Date().toISOString()};}for(const q of r.questions||[]){const id=qid(q.nodeId,'followup-'+hash(model+q.prompt));if(!f.customQuestions.some(x=>x.id===id))f.customQuestions.push({id,nodeId:q.nodeId,prompt:q.prompt.trim(),model});}
// Follow-ups change the question catalog, not the owner evidence reviewed by this run.
const now=snapshot(g);for(const o of r.opinions)f.opinions[o.nodeId][model].snapshotId=now;f.receipts.push({model,runId:r.runId,at:new Date().toISOString(),count:r.opinions.length,requested:request.nodeIds.length,snapshotId:now});f.receipts=f.receipts.slice(-100);return {count:r.opinions.length,requested:request.nodeIds.length};}
function restoreAnswers(g,r){if(!r||r.schema!=='moor.canonical-answers'||r.version!==1||!r.answers||!Array.isArray(r.history))throw Error('Expected a canonical answers export.');const f=ensure(g),candidate=clone(g);candidate.funnel.answers=clone(r.answers);candidate.funnel.answerHistory=clone(r.history);candidate.funnel.customQuestions=clone(r.customQuestions||[]);candidate.funnel.resolutions=clone(r.resolutions||[]);candidate.funnel.learnedRules=clone(r.learnedRules||[]);validate(candidate);const known=new Set([...g.nodes.map(n=>n.id),...(g.tombstones||[]).map(t=>t.node.id)]);for(const a of Object.values(r.answers))if(!known.has(a.nodeId))throw Error('Answers refer to a different blueprint. Import its full context instead.');const prior=[...f.answerHistory,...Object.values(f.answers)].map(clone);f.answers=candidate.funnel.answers;f.answerHistory=[...prior,...candidate.funnel.answerHistory];f.customQuestions=candidate.funnel.customQuestions;f.resolutions=candidate.funnel.resolutions;f.learnedRules=candidate.funnel.learnedRules;f.sequence=Math.max(0,...Object.values(f.answers).map(a=>a.sequence||0),...f.answerHistory.map(a=>a.sequence||0));f.questionLog=f.questionLog||[];f.questionLog.push({at:new Date().toISOString(),reason:'Restored an answers snapshot as the single canonical ledger; prior answers retained in history.'});return g;}
function refreshQuestions(g){const f=ensure(g);f.questionEpoch=(f.questionEpoch||0)+1;f.questionLog=f.questionLog||[];f.questionLog.push({epoch:f.questionEpoch,at:new Date().toISOString(),reason:'Owner refreshed questions against the current architecture; submitted answers retained.'});return f.questionEpoch;}
function validate(g){const f=g.funnel;if(!f)return g;const record=x=>x&&typeof x==='object'&&!Array.isArray(x);if(f.version!==1||!record(f.answers)||!record(f.opinions)||!record(f.requests)||!record(f.cadence))throw Error('Invalid funnel ledger.');for(const k of ['answerHistory','customQuestions','resolutions','learnedRules','receipts'])if(!Array.isArray(f[k]))throw Error('Invalid funnel '+k);if(Object.keys(f.answers).length>100000||f.customQuestions.length>10000)throw Error('Funnel exceeds supported size.');for(const a of f.answerHistory)if(!a||typeof a.questionId!=='string'||typeof a.nodeId!=='string'||typeof a.prompt!=='string'||typeof a.text!=='string'||!Number.isFinite(a.sequence))throw Error('Invalid answer history.');for(const r of f.resolutions)if(!r||typeof r.conflictId!=='string'||typeof r.note!=='string')throw Error('Invalid conflict resolution.');for(const r of f.learnedRules)if(!r||typeof r.questionId!=='string'||typeof r.choice!=='string')throw Error('Invalid learned resolution.');for(const [id,a] of Object.entries(f.answers))if(!a||a.questionId!==id||typeof a.nodeId!=='string'||typeof a.prompt!=='string'||!Number.isFinite(a.sequence)||typeof a.text!=='string'||a.text.length>20000||!['answered','deferred'].includes(a.state))throw Error('Invalid funnel answer.');for(const [id,opinions] of Object.entries(f.opinions)){if(!record(opinions))throw Error('Invalid opinions.');for(const [m,o] of Object.entries(opinions))if(!models.includes(m)||!o||o.nodeId!==id||o.model!==m||!grades[o.colorId]||typeof o.reason!=='string'||!Array.isArray(o.answerIds)||typeof o.snapshotId!=='string')throw Error('Invalid model opinion.');}for(const q of f.customQuestions)if(!q||typeof q.id!=='string'||typeof q.nodeId!=='string'||typeof q.prompt!=='string'||q.prompt.length>2000)throw Error('Invalid funnel question.');for(const [m,c] of Object.entries(f.cadence))if(!models.includes(m)||!c||!['off','answers','5','15','60','1440'].includes(c.interval))throw Error('Invalid review cadence.');return g;}
return {models,lanes,grades,ensure,questions,catalog,answer,applyAnswer,snapshot,clashes,resolve,compileNone,view,next,packet,parseReply,importReply,restoreAnswers,refreshQuestions,validate,qid};
});
