/* Reference previews are bounded examples, not production claims. Imported HTML runs verbatim in a sandbox. */
(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const literal=x=>JSON.stringify(x).replace(/</g,'\\u003c');
 const style='body{font:14px/1.6 system-ui;background:#f0f4f1;color:#213c33;padding:26px;margin:0}h1{font-size:24px;margin:0 0 10px}p{max-width:760px}small{color:#5c7168}button,input,select{font:inherit;padding:9px 12px;border:1px solid #9fb5aa;border-radius:7px;background:white;color:#213c33;margin:4px}button{cursor:pointer;background:#cce7d8}pre,.row{background:white;border:1px solid #c6d7cd;border-radius:9px;padding:13px;white-space:pre-wrap;overflow-wrap:anywhere;margin-top:8px}canvas{background:#183c33;width:100%;height:240px;border-radius:10px}label{display:block}';
 function wrap(n,body,js){
  return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(n.title)+'</title><style>'+style+'</style></head><body>'+
    '<small>MOOR · Reference mechanism · isolated / ephemeral</small><h1>'+esc(n.title)+'</h1><p>'+esc(n.overview)+'</p>'+
    body+'<script>'+js+'</'+'script></body></html>';
 }
 function generate(n){
  if(/seed|random|terrain|planet|island|garden|forest|spatial|world|architecture|nature|landscape/i.test(n.id+' '+n.title))return wrap(n,'<label>World seed <input id="seed" value="moor-42"></label><button id="reroll">Render seed</button><canvas id="world" width="800" height="260"></canvas><pre id="result"></pre>',`function draw(){let seed=document.getElementById('seed').value,s=2166136261;for(const c of seed)s=Math.imul(s^c.charCodeAt(0),16777619)>>>0;const random=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296};let c=document.getElementById('world'),x=c.getContext('2d');x.fillStyle='#173b34';x.fillRect(0,0,800,260);const heights=[];for(let i=0;i<50;i++){const h=40+random()*140;heights.push(Math.round(h));x.fillStyle='hsl('+Math.round(130+random()*30)+' 23% '+Math.round(30+random()*25)+'%)';x.fillRect(i*16,260-h,16,h);}document.getElementById('result').textContent=JSON.stringify({seed,heights,contract:'same seed → same output; illustrative 2D terrain, not full world engine'},null,2)}document.getElementById('reroll').onclick=draw;draw();`);
  if(/permission|roles|envelope|valuable|entitlement|ownership/i.test(n.id+' '+n.title))return wrap(n,'<label>Actor <select id="actor"><option>owner</option><option>editor</option><option>viewer</option></select></label><button id="read">Read</button><button id="edit">Edit</button><button id="share">Share</button><pre id="receipt">Choose an action.</pre>',`const grants={owner:['read','edit','share'],editor:['read','edit'],viewer:['read']};for(const action of ['read','edit','share'])document.getElementById(action).onclick=()=>{const actor=document.getElementById('actor').value;document.getElementById('receipt').textContent=JSON.stringify({actor,action,allowed:grants[actor].includes(action),scope:'reference object only',notice:'Enforcement demonstrated locally; real authentication/server authority is absent.'},null,2)};`);
  if(/quiz|funnel|intent|resolver/i.test(n.id+' '+n.title))return wrap(n,'<label>Original outcome <input id="ask" placeholder="What should work?"></label><label>Must preserve <input id="keep" placeholder="State, files, privacy…"></label><label>Output <select id="type"><option>Working tool</option><option>Document</option><option>Scene</option></select></label><button id="lock">Lock contract</button><pre id="contract"></pre>',`document.getElementById('lock').onclick=()=>{const rawIntent=document.getElementById('ask').value;document.getElementById('contract').textContent=JSON.stringify({rawIntent,locked:{preserve:document.getElementById('keep').value,output:document.getElementById('type').value},unresolved:rawIntent?['Verification of the actual output']:['Desired outcome is missing'],provenance:'Explicit form inputs; no inferred model answers'},null,2)};`);
  if(/clock|sequence|worker|verification|convergence|harness|pipeline/i.test(n.id+' '+n.title))return wrap(n,'<button id="step">Execute next gate</button><button id="reset">Reset</button><pre id="receipt"></pre>',`const gates=['Validate input','Resolve references','Prepare candidate','Exercise behavior','Check original intent'],receipts=[];function show(){document.getElementById('receipt').textContent=JSON.stringify({next:gates[receipts.length]||'Reference complete',receipts,notice:'Gate sequencing mechanism only; these labels do not run the production compiler.'},null,2)}document.getElementById('step').onclick=()=>{if(receipts.length<gates.length)receipts.push({gate:gates[receipts.length],state:'reference step executed',at:new Date().toISOString()});show()};document.getElementById('reset').onclick=()=>{receipts.length=0;show()};show();`);
  if(/chart|metric|analyt|econom|performance/i.test(n.id+' '+n.title))return wrap(n,'<label>Numbers <input id="data" value="12, 23, 18, 34, 28"></label><button id="draw">Render values</button><canvas id="chart" width="800" height="260"></canvas><pre id="receipt"></pre>',`function draw(){const values=document.getElementById('data').value.split(',').map(Number);if(values.some(x=>!Number.isFinite(x)||x<0))throw Error('Use nonnegative numeric values');const ctx=document.getElementById('chart').getContext('2d');ctx.clearRect(0,0,800,260);const max=Math.max(1,...values);values.forEach((v,i)=>{ctx.fillStyle='#a3dfc2';ctx.fillRect(i*800/values.length+8,240-v/max*210,800/values.length-16,v/max*210)});document.getElementById('receipt').textContent=JSON.stringify({values,notice:'User-entered illustrative values; no revenue or activity claim.'},null,2)}document.getElementById('draw').onclick=draw;draw();`);
  return wrap(n,'<label>Record <input id="input" placeholder="Add a concrete object or task"></label><button id="add">Keep record</button><button id="export">Export state</button><div id="records"></div><pre id="receipt"></pre>',`const state={schema:'moor.reference.records',version:1,component:${literal(n.id)},revision:0,records:[]};const input=document.getElementById('input');function render(){const host=document.getElementById('records');host.replaceChildren();for(const record of state.records){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=record.title+' ';const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=()=>{state.records=state.records.filter(x=>x.id!==record.id);state.revision++;render()};row.append(label,remove);host.append(row)}document.getElementById('receipt').textContent=JSON.stringify(state,null,2)}document.getElementById('add').onclick=()=>{if(!input.value.trim())return;state.records.push({id:'object-'+(state.revision+1),title:input.value.trim()});state.revision++;input.value='';render()};document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='reference-state.json';a.textContent='Download JSON (sandbox may block downloads; state remains visible below)';document.getElementById('receipt').before(a)};render();`);
 }
 function compile(code){
  if(!code.trim().startsWith('{'))return code;
  let spec;try{spec=JSON.parse(code)}catch(e){throw Error('Reference JSON is malformed: '+e.message)}
  if(spec.schema!=='moor.reference-ui'||spec.version!==1||!Array.isArray(spec.blocks))throw Error('Reference JSON needs schema "moor.reference-ui", version 1 and blocks. Or paste a complete HTML document.');
  const allowed=['text','input','button','card','list','chart'];for(const b of spec.blocks)if(!allowed.includes(b.type))throw Error('Unsupported reference block: '+b.type);
  return wrap({title:spec.title||'Reference UI',overview:spec.description||'Imported structured reference code.'},'<div id="root"></div>',`const spec=${literal(spec)},state={...(spec.state||{})};const root=document.getElementById('root');function render(){root.replaceChildren();for(const block of spec.blocks){const el=document.createElement(block.type==='button'?'button':block.type==='input'?'input':'div');if(block.type==='input'){el.placeholder=block.label||'';el.value=state[block.key]||'';el.oninput=()=>{state[block.key]=el.value}}else if(block.type==='button'){el.textContent=block.label||'Run';el.onclick=()=>{const action=block.action||{};if(action.type==='increment')state[action.key]=Number(state[action.key]||0)+1;else if(action.type==='append')state[action.key]=[...(state[action.key]||[]),state[action.from]||action.value||'Item'];else if(action.type==='clear')state[action.key]=[];else if(action.type==='toggle')state[action.key]=!state[action.key];else throw Error('Unsupported action');render()}}else if(block.type==='list'){for(const value of state[block.key]||[]){const row=document.createElement('div');row.className='row';row.textContent=typeof value==='object'?JSON.stringify(value):String(value);el.append(row)}}else if(block.type==='chart'){const values=state[block.key]||block.values||[];values.forEach(v=>{const bar=document.createElement('div');bar.style.cssText='background:#a3dfc2;margin:5px 0;padding:4px;width:'+Math.min(100,Math.max(1,Number(v)))+'%';bar.textContent=String(v);el.append(bar)})}else{el.className=block.type==='card'?'row':'';el.textContent=(block.text||'').replace(/\\{\\{([\\w-]+)\\}\\}/g,(_,k)=>String(state[k]??''))}root.append(el)}}render();`);
 }
 function isolate(code,token){
  const html=compile(code),policy="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; media-src data: blob:; connect-src 'none'; form-action 'none'; base-uri 'none'";
  const instrumentation='<meta http-equiv="Content-Security-Policy" content="'+policy+'"><script>(()=>{const send=(kind,message)=>parent.postMessage({type:"moor:reference",token:'+literal(token)+',kind,message},"*");addEventListener("error",e=>send("error",e.message));addEventListener("unhandledrejection",e=>send("error",String(e.reason)));addEventListener("DOMContentLoaded",()=>send("ready","Rendered imported code. Check its behavior; a render is not production verification."));})();</'+'script>';
  // Instrument before any user scripts. External requests and host access remain blocked.
  return /<head[\s>]/i.test(html)?html.replace(/<head([^>]*)>/i,'<head$1>'+instrumentation):'<!doctype html><html><head>'+instrumentation+'</head><body>'+html+'</body></html>';
 }
 root.BlueprintReference={generate,compile,isolate};
})(globalThis);
