/* Moor kit: kanban v1.0.0
 * Engine: window.MoorKit.build(config) -> complete <!DOCTYPE html> document.
 * config: { board: "personal"|"work"|"project"|"launch",
 *           columns: "classic"|"flow"|"sprint"|"simple",
 *           accent: "ocean"|"sunset"|"mint"|"violet",
 *           extras: ["wip","progress","labels","archive"] }
 * Touch-first: taps via pointerup (never synthesized click); cards move by
 * tap-select + tap-a-column, or by long-press drag with pointer events.
 * Storage: localStorage wrapped in try/catch; app runs fully in-memory if blocked.
 */
(function () {
'use strict';

var CSS = [
"*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}",
"html,body{margin:0;padding:0}",
"body{font-family:-apple-system,BlinkMacSystemFont,'SF Pro Text','Segoe UI',Roboto,sans-serif;min-height:100vh;background:var(--bg);color:var(--tx);touch-action:manipulation;-webkit-font-smoothing:antialiased}",
"body[data-accent=ocean]{--bg:#070b12;--card:rgba(255,255,255,.045);--card2:rgba(255,255,255,.085);--tx:#eef3fa;--mut:#8b96a9;--line:rgba(255,255,255,.1);--acc:#38bdf8;--acc2:#2563eb;--sheet:#10161f;--danger:#f87171}",
"body[data-accent=sunset]{--bg:#100a07;--card:rgba(255,255,255,.045);--card2:rgba(255,255,255,.085);--tx:#faf1e8;--mut:#a89a88;--line:rgba(255,255,255,.1);--acc:#fb923c;--acc2:#ea580c;--sheet:#1a120b;--danger:#f87171}",
"body[data-accent=mint]{--bg:#07100c;--card:rgba(255,255,255,.045);--card2:rgba(255,255,255,.085);--tx:#eafaf2;--mut:#8aa89a;--line:rgba(255,255,255,.1);--acc:#34d399;--acc2:#059669;--sheet:#0d1712;--danger:#f87171}",
"body[data-accent=violet]{--bg:#0c0812;--card:rgba(255,255,255,.045);--card2:rgba(255,255,255,.085);--tx:#f1ecfa;--mut:#9a8fb0;--line:rgba(255,255,255,.1);--acc:#a78bfa;--acc2:#7c3aed;--sheet:#141020;--danger:#f87171}",
".wrap{max-width:1200px;margin:0 auto;padding:0 0 calc(env(safe-area-inset-bottom,0px) + 40px)}",
".top{position:sticky;top:0;z-index:20;display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding:calc(env(safe-area-inset-top,0px) + 16px) 18px 12px;background:linear-gradient(var(--bg) 78%,transparent);-webkit-backdrop-filter:blur(8px);backdrop-filter:blur(8px)}",
".kicker{font-size:12px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase;color:var(--mut);margin:0 0 2px}",
".btitle{display:flex;align-items:center;gap:8px;background:none;border:none;color:var(--tx);padding:6px 0;min-height:44px;cursor:pointer;text-align:left}",
".btitle h1{font-size:30px;font-weight:800;margin:0;letter-spacing:-.5px}",
".btitle .tp{font-size:14px;color:var(--mut)}",
".tractions{display:flex;gap:8px}",
".iconbtn{width:44px;height:44px;flex:none;border-radius:14px;border:1px solid var(--line);background:var(--card);color:var(--tx);font-size:18px;display:flex;align-items:center;justify-content:center;cursor:pointer}",
".iconbtn.hidden{display:none}",
"#cancelmove{border-color:var(--acc);color:var(--acc)}",
"#pwrap{padding:2px 18px 12px}",
".pbar{height:10px;border-radius:99px;background:var(--card2);overflow:hidden}",
".pfill{height:100%;width:0;border-radius:99px;background:linear-gradient(90deg,var(--acc),var(--acc2));transition:width .35s ease}",
".psub{font-size:13px;color:var(--mut);margin:8px 2px 0}",
"#board{display:flex;gap:12px;overflow-x:auto;padding:4px 18px 18px;scroll-snap-type:x proximity;-webkit-overflow-scrolling:touch}",
".col{flex:0 0 272px;max-width:82vw;background:var(--card);border:1px solid var(--line);border-radius:18px;padding:12px;scroll-snap-align:start;display:flex;flex-direction:column;max-height:calc(100dvh - 250px);min-height:180px}",
".col.drop-hi{outline:2px solid var(--acc);outline-offset:-2px}",
".colhead{display:flex;align-items:center;gap:8px;margin-bottom:4px}",
".chmain{flex:1;min-width:0;display:flex;align-items:center;gap:8px}",
".cname{font-size:15px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
".count{flex:none;min-width:26px;height:26px;padding:0 8px;border-radius:99px;background:var(--card2);color:var(--mut);font-size:12px;font-weight:800;display:flex;align-items:center;justify-content:center}",
".count.over{background:rgba(248,113,113,.18);color:var(--danger)}",
".addbtn{width:44px;height:44px;flex:none;border-radius:12px;border:1px dashed var(--line);background:transparent;color:var(--mut);font-size:22px;line-height:1;display:flex;align-items:center;justify-content:center;cursor:pointer}",
".addbtn:active{background:var(--card2)}",
".droppill{display:none;width:100%;margin:6px 0 2px;padding:12px;border-radius:12px;border:2px dashed var(--acc);background:rgba(56,189,248,.08);color:var(--acc);font-size:14px;font-weight:800;cursor:pointer}",
"body.movemode .droppill{display:block}",
"body.movemode .col.issrc .droppill{display:none}",
".cards{overflow-y:auto;display:flex;flex-direction:column;gap:10px;padding:2px;min-height:60px}",
".nocol{border:1px dashed var(--line);border-radius:14px;padding:18px 12px;text-align:center;color:var(--mut);font-size:13px}",
".card{position:relative;background:var(--card2);border:1px solid var(--line);border-radius:14px;padding:12px 48px 12px 12px;touch-action:pan-y;user-select:none;-webkit-user-select:none;cursor:pointer}",
".card.sel{border-color:var(--acc);box-shadow:0 0 0 2px var(--acc),0 8px 24px rgba(0,0,0,.35)}",
".card.dragsrc{opacity:.35}",
".card.ghost{position:fixed;z-index:90;pointer-events:none;margin:0;transform:rotate(3deg) scale(1.05);box-shadow:0 18px 44px rgba(0,0,0,.5)}",
".lchip{display:block;width:34px;height:6px;border-radius:99px;margin-bottom:8px}",
".ctitle{font-size:15px;font-weight:600;line-height:1.45;overflow-wrap:break-word}",
".cedit{position:absolute;top:4px;right:4px;width:44px;height:44px;border:none;background:transparent;color:var(--mut);font-size:16px;display:flex;align-items:center;justify-content:center;cursor:pointer;border-radius:12px}",
"#archsec{padding:0 18px}",
".archhead{width:100%;display:flex;align-items:center;justify-content:space-between;background:var(--card);border:1px solid var(--line);border-radius:14px;color:var(--mut);font-size:14px;font-weight:700;padding:14px 16px;cursor:pointer}",
".archlist{margin-top:8px;display:flex;flex-direction:column;gap:8px}",
".archrow{display:flex;align-items:center;gap:8px;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:10px 10px 10px 14px}",
".atitle{flex:1;min-width:0;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
".mini{flex:none;min-width:44px;min-height:44px;padding:8px 14px;border-radius:12px;border:1px solid var(--line);background:transparent;color:var(--tx);font-size:13px;font-weight:700;cursor:pointer}",
".mini.armed{background:var(--danger);border-color:var(--danger);color:#fff}",
".mini.danger2{color:var(--danger)}",
"#backdrop{position:fixed;inset:0;background:rgba(0,0,0,.55);opacity:0;pointer-events:none;transition:opacity .25s;z-index:50}",
"#backdrop.on{opacity:1;pointer-events:auto}",
"#sheet{position:fixed;left:0;right:0;bottom:0;max-width:560px;margin:0 auto;background:var(--sheet);border-radius:22px 22px 0 0;padding:18px 18px calc(env(safe-area-inset-bottom,0px) + 22px);transform:translateY(105%);transition:transform .28s cubic-bezier(.2,.9,.25,1);z-index:51;border-top:1px solid var(--line);max-height:86dvh;overflow-y:auto}",
"#sheet.on{transform:translateY(0)}",
"#sheet h2{margin:2px 0 14px;font-size:20px}",
".field{margin-bottom:16px}",
".field label{display:block;font-size:12px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:var(--mut);margin-bottom:8px}",
".field input[type=text]{width:100%;font-size:17px;padding:14px;border-radius:14px;border:1px solid var(--line);background:var(--card);color:var(--tx);outline:none}",
".csegs{display:flex;flex-wrap:wrap;gap:8px}",
".cseg{border:1px solid var(--line);background:var(--card);color:var(--mut);font-size:14px;font-weight:700;padding:12px 16px;min-height:44px;border-radius:12px;cursor:pointer}",
".cseg.sel{background:linear-gradient(135deg,var(--acc),var(--acc2));border-color:transparent;color:#fff}",
".sws{display:flex;gap:10px;flex-wrap:wrap}",
".sw{width:44px;height:44px;border-radius:50%;border:2px solid var(--line);background:var(--card2);color:var(--mut);font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center}",
".sw.sel{border-color:#fff;box-shadow:0 0 0 2px var(--acc)}",
".cta{width:100%;border:none;border-radius:16px;padding:16px;font-size:17px;font-weight:800;background:linear-gradient(135deg,var(--acc),var(--acc2));color:#fff;cursor:pointer;margin-top:4px}",
".danger{width:100%;border:1px solid var(--line);border-radius:16px;padding:14px;font-size:15px;font-weight:700;background:transparent;color:var(--danger);cursor:pointer;margin-top:10px}",
".danger.armed{background:var(--danger);color:#fff;border-color:var(--danger)}",
".ghostbtn{width:100%;border:1px dashed var(--line);border-radius:14px;padding:14px;font-size:15px;font-weight:700;background:transparent;color:var(--mut);cursor:pointer}",
".colrow{display:flex;align-items:center;gap:8px;margin-bottom:10px}",
".colrow input[type=text]{flex:1;min-width:0;font-size:16px;padding:12px;border-radius:12px;border:1px solid var(--line);background:var(--card);color:var(--tx);outline:none}",
".lim{flex:none;display:flex;align-items:center;gap:6px}",
".lbtn{width:44px;height:44px;border-radius:12px;border:1px solid var(--line);background:var(--card);color:var(--tx);font-size:18px;cursor:pointer}",
".lval{flex:none;min-width:34px;text-align:center;font-size:14px;font-weight:800;color:var(--mut)}",
".xbtn{flex:none;width:44px;height:44px;border-radius:12px;border:1px solid var(--line);background:transparent;color:var(--mut);font-size:18px;cursor:pointer}",
"#toast{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom,0px) + 40px);transform:translateX(-50%) translateY(20px);background:var(--tx);color:var(--bg);font-size:14px;font-weight:700;padding:12px 20px;border-radius:99px;opacity:0;pointer-events:none;transition:all .3s;z-index:70;white-space:nowrap;max-width:92vw;overflow:hidden;text-overflow:ellipsis}",
"#toast.on{opacity:1;transform:translateX(-50%) translateY(0)}",
"@media (min-width:700px){.col{flex-basis:300px}}"
].join("\n");

var APP = [
"/* Kanban Board app. CFG is injected above: {board, columns[], accent, extras[], title, starter[]} */",
"function $(id){ return document.getElementById(id); }",
"function esc(s){ var d=document.createElement('div'); d.textContent=String(s==null?'':s); return d.innerHTML; }",
"function has(x){ return CFG.extras.indexOf(x)>=0; }",
"function onTap(el, fn){",
"  if(!el) return;",
"  var sx=0, sy=0, down=false;",
"  el.addEventListener('pointerdown', function(e){ down=true; sx=e.clientX; sy=e.clientY; });",
"  el.addEventListener('pointerup', function(e){ if(!down) return; down=false; if(Math.abs(e.clientX-sx)<14 && Math.abs(e.clientY-sy)<14){ fn(e); } });",
"  el.addEventListener('pointercancel', function(){ down=false; });",
"}",
"var store = {",
"  read: function(){ try{ var r=localStorage.getItem('kanban.v1'); return r?JSON.parse(r):null; }catch(e){ return null; } },",
"  write: function(s){ try{ localStorage.setItem('kanban.v1', JSON.stringify(s)); }catch(e){} }",
"};",
"function uid(){ return 'k'+Math.random().toString(36).slice(2,9)+Date.now().toString(36); }",
"var LABELS=[['none',''],['red','#ff6b6b'],['orange','#ffa94d'],['yellow','#ffd43b'],['green','#69db7c'],['blue','#4dabf7'],['violet','#b197fc']];",
"function labelColor(id){ for(var i=0;i<LABELS.length;i++) if(LABELS[i][0]===id) return LABELS[i][1]; return ''; }",
"function validState(s){",
"  if(!s||typeof s!=='object'||Array.isArray(s)) return false;",
"  if(!Array.isArray(s.cols)||!s.cols.length) return false;",
"  if(!Array.isArray(s.cards)) return false;",
"  for(var i=0;i<s.cols.length;i++){ var c=s.cols[i]; if(!c||typeof c.id!=='string'||typeof c.name!=='string') return false; }",
"  return true;",
"}",
"var S=null, selId=null, archOpen=false;",
"function defaultState(){",
"  var cols=CFG.columns.map(function(n,i){ return {id:'col'+i+'_'+uid(), name:n, limit:0}; });",
"  var cards=[];",
"  CFG.starter.forEach(function(st){",
"    var ci=st.c<0?cols.length-1:Math.min(st.c,cols.length-1);",
"    cards.push({id:uid(), col:cols[ci].id, title:st.title, label:st.label||'none', archived:false, created:Date.now()});",
"  });",
"  return {title:CFG.title, cols:cols, cards:cards};",
"}",
"function save(){ store.write(S); }",
"function load(){ var s=store.read(); S=validState(s)?s:defaultState(); save(); }",
"function colById(id){ for(var i=0;i<S.cols.length;i++) if(S.cols[i].id===id) return S.cols[i]; return null; }",
"function cardById(id){ for(var i=0;i<S.cards.length;i++) if(S.cards[i].id===id) return S.cards[i]; return null; }",
"function liveCards(){ return S.cards.filter(function(k){ return !k.archived; }); }",
"function cardsIn(colId){ return S.cards.filter(function(k){ return k.col===colId && !k.archived; }); }",
"var toastT=null;",
"function toast(msg){ var t=$('toast'); if(!t) return; t.textContent=msg; t.classList.add('on'); if(toastT) clearTimeout(toastT); toastT=setTimeout(function(){ t.classList.remove('on'); },1800); }",
"function showSheet(){ $('backdrop').classList.add('on'); $('sheet').classList.add('on'); }",
"function closeSheet(){ $('backdrop').classList.remove('on'); $('sheet').classList.remove('on'); }",
"function countBadge(c,n){",
"  if(!has('wip')) return '';",
"  if(c.limit>0){ var over=n>c.limit; return '<span class=\"count'+(over?' over':'')+'\">'+n+'/'+c.limit+'</span>'; }",
"  return '<span class=\"count\">'+n+'</span>';",
"}",
"function labelChip(l){",
"  if(!has('labels')||!l||l==='none') return '';",
"  var c=labelColor(l); if(!c) return '';",
"  return '<span class=\"lchip\" style=\"background:'+c+'\"></span>';",
"}",
"function renderProgress(){",
"  var w=$('pwrap');",
"  if(!has('progress')){ w.style.display='none'; return; }",
"  w.style.display='';",
"  var live=liveCards(), total=live.length;",
"  var lastCol=S.cols[S.cols.length-1];",
"  var done=lastCol?cardsIn(lastCol.id).length:0;",
"  var pct=total?Math.round(done/total*100):0;",
"  $('pfill').style.width=pct+'%';",
"  $('psub').textContent=done+' of '+total+' done \u00b7 '+pct+'%';",
"}",
"function render(){",
"  $('btitle').textContent=S.title;",
"  renderProgress();",
"  var bd=$('board'); bd.innerHTML='';",
"  S.cols.forEach(function(c){",
"    var ks=cardsIn(c.id);",
"    var sec=document.createElement('section'); sec.className='col'; sec.setAttribute('data-col',c.id);",
"    var h='<div class=\"colhead\">'+",
"      '<div class=\"chmain\"><span class=\"cname\">'+esc(c.name)+'</span>'+countBadge(c,ks.length)+'</div>'+",
"      '<button class=\"addbtn\" data-add=\"'+c.id+'\" aria-label=\"add card to '+esc(c.name)+'\">+</button></div>'+",
"      '<button class=\"droppill\" data-drop=\"'+c.id+'\">Drop here</button>'+",
"      '<div class=\"cards\">';",
"    if(!ks.length) h+='<div class=\"nocol\">No cards yet</div>';",
"    ks.forEach(function(k){",
"      h+='<article class=\"card'+(k.id===selId?' sel':'')+'\" data-id=\"'+k.id+'\">'+labelChip(k.label)+",
"        '<div class=\"ctitle\">'+esc(k.title)+'</div>'+",
"        '<button class=\"cedit\" data-edit=\"'+k.id+'\" aria-label=\"edit card\">&#9998;</button></article>';",
"    });",
"    h+='</div>';",
"    sec.innerHTML=h; bd.appendChild(sec);",
"  });",
"  bindBoard(bd);",
"  renderArchive();",
"  updateMoveUI();",
"}",
"function bindBoard(bd){",
"  var adds=bd.querySelectorAll('[data-add]');",
"  for(var i=0;i<adds.length;i++){ (function(b){ onTap(b,function(e){ if(e.stopPropagation) e.stopPropagation(); selId=null; updateMoveUI(); openCardSheet({id:null,col:b.getAttribute('data-add'),title:'',label:'none'}); }); })(adds[i]); }",
"  var drops=bd.querySelectorAll('[data-drop]');",
"  for(var j=0;j<drops.length;j++){ (function(b){ onTap(b,function(e){ if(e.stopPropagation) e.stopPropagation(); moveSelectedTo(b.getAttribute('data-drop')); }); })(drops[j]); }",
"  var eds=bd.querySelectorAll('[data-edit]');",
"  for(var m=0;m<eds.length;m++){ (function(b){ onTap(b,function(e){ if(e.stopPropagation) e.stopPropagation(); var k=cardById(b.getAttribute('data-edit')); if(k){ selId=null; updateMoveUI(); openCardSheet(k); } }); })(eds[m]); }",
"  var cards=bd.querySelectorAll('.card');",
"  for(var n=0;n<cards.length;n++){ bindCard(cards[n], cards[n].getAttribute('data-id')); }",
"}",
"function onCardTap(id){",
"  if(selId===id){ var k=cardById(id); selId=null; updateMoveUI(); if(k) openCardSheet(k); return; }",
"  selId=id; updateMoveUI();",
"  toast('Tap a column to move it');",
"}",
"function moveSelectedTo(colId){",
"  var k=selId?cardById(selId):null; selId=null;",
"  if(!k){ updateMoveUI(); return; }",
"  if(k.col!==colId) k.col=colId;",
"  save(); render();",
"  var c=colById(colId);",
"  toast('Moved to '+(c?c.name:'column'));",
"}",
"function updateMoveUI(){",
"  document.body.classList.toggle('movemode', !!selId);",
"  $('cancelmove').classList.toggle('hidden', !selId);",
"  var srcCol=selId&&cardById(selId)?cardById(selId).col:null;",
"  var cards=document.querySelectorAll('#board .card');",
"  for(var i=0;i<cards.length;i++) cards[i].classList.toggle('sel', cards[i].getAttribute('data-id')===selId);",
"  var cols=document.querySelectorAll('#board .col');",
"  for(var j=0;j<cols.length;j++) cols[j].classList.toggle('issrc', cols[j].getAttribute('data-col')===srcCol);",
"}",
"function bindCard(el,id){",
"  var sx=0,sy=0,down=false,timer=null,dragging=false,ghost=null,grabDX=0,grabDY=0,dropCol=null;",
"  el.addEventListener('pointerdown',function(e){",
"    down=true; sx=e.clientX; sy=e.clientY; dropCol=null;",
"    timer=setTimeout(function(){ if(down&&!dragging) startDrag(e); },340);",
"  });",
"  el.addEventListener('pointermove',function(e){",
"    if(!down) return;",
"    if(!dragging){ if(Math.hypot(e.clientX-sx,e.clientY-sy)>12&&timer){ clearTimeout(timer); timer=null; } return; }",
"    moveDrag(e);",
"  });",
"  el.addEventListener('pointerup',function(e){",
"    if(timer){ clearTimeout(timer); timer=null; }",
"    if(dragging){ endDrag(); dragging=false; }",
"    else if(down&&Math.hypot(e.clientX-sx,e.clientY-sy)<14){",
"      if(!(e.target&&e.target.closest&&e.target.closest('.cedit'))) onCardTap(id);",
"    }",
"    down=false;",
"  });",
"  el.addEventListener('pointercancel',function(){ if(timer){clearTimeout(timer);timer=null;} if(dragging){cancelDrag();dragging=false;} down=false; });",
"  function startDrag(e){",
"    dragging=true; selId=null; updateMoveUI(); closeSheet();",
"    document.body.classList.add('dragging');",
"    ghost=el.cloneNode(true); ghost.classList.add('ghost'); ghost.classList.remove('sel');",
"    var r=el.getBoundingClientRect();",
"    grabDX=e.clientX-r.left; grabDY=e.clientY-r.top;",
"    ghost.style.width=r.width+'px';",
"    ghost.style.left=(e.clientX-grabDX)+'px'; ghost.style.top=(e.clientY-grabDY)+'px';",
"    document.body.appendChild(ghost); el.classList.add('dragsrc');",
"    moveDrag(e);",
"  }",
"  function moveDrag(e){",
"    if(!ghost) return;",
"    ghost.style.left=(e.clientX-grabDX)+'px'; ghost.style.top=(e.clientY-grabDY)+'px';",
"    var bd=$('board');",
"    if(e.clientX<70) bd.scrollLeft-=14; else if(e.clientX>window.innerWidth-70) bd.scrollLeft+=14;",
"    var els=document.elementsFromPoint(e.clientX,e.clientY), col=null;",
"    for(var i=0;i<els.length;i++){ var c=els[i].closest?els[i].closest('.col'):null; if(c){ col=c; break; } }",
"    if(dropCol&&dropCol!==col) dropCol.classList.remove('drop-hi');",
"    dropCol=col;",
"    if(dropCol) dropCol.classList.add('drop-hi');",
"  }",
"  function endDrag(){",
"    var target=dropCol?dropCol.getAttribute('data-col'):null;",
"    cancelDrag();",
"    if(target){",
"      var k=cardById(id);",
"      if(k&&k.col!==target){ k.col=target; save(); render(); var c=colById(target); toast('Moved to '+(c?c.name:'column')); }",
"      else render();",
"    }",
"  }",
"  function cancelDrag(){",
"    if(ghost&&ghost.parentNode) ghost.parentNode.removeChild(ghost); ghost=null;",
"    el.classList.remove('dragsrc'); document.body.classList.remove('dragging');",
"    var hi=document.querySelectorAll('.col.drop-hi'); for(var i=0;i<hi.length;i++) hi[i].classList.remove('drop-hi'); dropCol=null;",
"  }",
"}",
"function openCardSheet(k){",
"  var isNew=!k.id;",
"  var colSel=k.col, labSel=k.label||'none';",
"  var h='<h2>'+(isNew?'New card':'Edit card')+'</h2>'+",
"    '<div class=\"field\"><label>Card title</label><input type=\"text\" id=\"ctitle\" maxlength=\"120\" value=\"'+esc(k.title)+'\" autocomplete=\"off\"></div>'+",
"    '<div class=\"field\"><label>Column</label><div class=\"csegs\" id=\"ccols\">';",
"  S.cols.forEach(function(c){ h+='<button class=\"cseg'+(c.id===colSel?' sel':'')+'\" data-c=\"'+c.id+'\">'+esc(c.name)+'</button>'; });",
"  h+='</div></div>';",
"  if(has('labels')){",
"    h+='<div class=\"field\"><label>Label</label><div class=\"sws\" id=\"csw\">';",
"    LABELS.forEach(function(L){",
"      h+='<button class=\"sw'+(L[0]===labSel?' sel':'')+'\" data-l=\"'+L[0]+'\" aria-label=\"'+L[0]+' label\"'+(L[1]?' style=\"background:'+L[1]+'\"':'')+'>'+(L[0]==='none'?'&times;':'')+'</button>';",
"    });",
"    h+='</div></div>';",
"  }",
"  h+='<button class=\"cta\" id=\"csave\">'+(isNew?'Add card':'Save')+'</button>';",
"  if(!isNew) h+='<button class=\"danger\" id=\"cdel\">'+(has('archive')?'Archive card':'Delete card')+'</button>';",
"  $('sheet').innerHTML=h; showSheet();",
"  var segs=$('ccols').querySelectorAll('.cseg');",
"  for(var i=0;i<segs.length;i++){ (function(b){ onTap(b,function(){ colSel=b.getAttribute('data-c'); for(var j=0;j<segs.length;j++) segs[j].classList.toggle('sel',segs[j]===b); }); })(segs[i]); }",
"  if(has('labels')){",
"    var sws=$('csw').querySelectorAll('.sw');",
"    for(var m=0;m<sws.length;m++){ (function(b){ onTap(b,function(){ labSel=b.getAttribute('data-l'); for(var j=0;j<sws.length;j++) sws[j].classList.toggle('sel',sws[j]===b); }); })(sws[m]); }",
"  }",
"  onTap($('csave'),function(){",
"    var t=$('ctitle').value.trim()||'Untitled card';",
"    if(isNew){ S.cards.push({id:uid(),col:colSel,title:t,label:labSel,archived:false,created:Date.now()}); }",
"    else { k.title=t; k.col=colSel; k.label=labSel; }",
"    save(); render(); closeSheet(); toast(isNew?'Card added':'Saved');",
"  });",
"  if(!isNew){",
"    var armed=false, db=$('cdel');",
"    onTap(db,function(){",
"      if(!armed){ armed=true; db.classList.add('armed'); db.textContent=has('archive')?'Tap again to archive':'Tap again to delete'; return; }",
"      if(has('archive')){ k.archived=true; toast('Archived'); }",
"      else { S.cards=S.cards.filter(function(x){ return x.id!==k.id; }); toast('Deleted'); }",
"      save(); render(); closeSheet();",
"    });",
"  }",
"  setTimeout(function(){ var i=$('ctitle'); if(i) i.focus({preventScroll:true}); },350);",
"}",
"function openBoardSheet(){",
"  var h='<h2>Board &amp; columns</h2>'+",
"    '<div class=\"field\"><label>Board name</label><input type=\"text\" id=\"bname\" maxlength=\"60\" value=\"'+esc(S.title)+'\" autocomplete=\"off\"></div>'+",
"    '<div class=\"field\"><label>Columns</label><div id=\"colrows\">';",
"  S.cols.forEach(function(c,i){",
"    h+='<div class=\"colrow\">'+",
"      '<input type=\"text\" class=\"cname-in\" maxlength=\"24\" value=\"'+esc(c.name)+'\" autocomplete=\"off\" aria-label=\"column name\">'+",
"      (has('wip')?'<div class=\"lim\"><button class=\"lbtn\" data-li=\"'+i+'\" data-d=\"-1\" aria-label=\"lower wip limit\">&minus;</button><span class=\"lval\" id=\"lval'+i+'\">'+(c.limit>0?String(c.limit):'&infin;')+'</span><button class=\"lbtn\" data-li=\"'+i+'\" data-d=\"1\" aria-label=\"raise wip limit\">+</button></div>':'')+",
"      (S.cols.length>1?'<button class=\"xbtn\" data-rm=\"'+i+'\" aria-label=\"remove column\">&times;</button>':'')+",
"      '</div>';",
"  });",
"  h+='</div><button class=\"ghostbtn\" id=\"addcol\">+ Add column</button></div>'+",
"    '<button class=\"cta\" id=\"bdone\">Done</button>';",
"  $('sheet').innerHTML=h; showSheet();",
"  if(has('wip')){",
"    var lbs=$('sheet').querySelectorAll('.lbtn');",
"    for(var i=0;i<lbs.length;i++){ (function(b){ onTap(b,function(){",
"      var li=+b.getAttribute('data-li');",
"      var c=S.cols[li]; c.limit=Math.max(0,Math.min(99,c.limit+(+b.getAttribute('data-d'))));",
"      $('lval'+li).innerHTML=c.limit>0?String(c.limit):'&infin;';",
"    }); })(lbs[i]); }",
"  }",
"  var rms=$('sheet').querySelectorAll('[data-rm]');",
"  for(var r=0;r<rms.length;r++){ (function(b){ onTap(b,function(){",
"    var i=+b.getAttribute('data-rm');",
"    var gone=S.cols[i];",
"    var dest=S.cols[i===0?1:0];",
"    S.cards.forEach(function(k){ if(k.col===gone.id) k.col=dest.id; });",
"    S.cols.splice(i,1); save(); openBoardSheet();",
"  }); })(rms[r]); }",
"  onTap($('addcol'),function(){",
"    if(S.cols.length>=6){ toast('Max 6 columns'); return; }",
"    S.cols.push({id:uid(),name:'New column',limit:0}); save(); openBoardSheet();",
"  });",
"  onTap($('bdone'),function(){",
"    S.title=$('bname').value.trim()||CFG.title;",
"    var ins=$('sheet').querySelectorAll('.cname-in');",
"    for(var i=0;i<ins.length&&i<S.cols.length;i++){ var v=ins[i].value.trim(); if(v) S.cols[i].name=v; }",
"    save(); render(); closeSheet();",
"  });",
"}",
"function renderArchive(){",
"  var sec=$('archsec');",
"  if(!has('archive')){ sec.innerHTML=''; return; }",
"  var arch=S.cards.filter(function(k){ return k.archived; });",
"  if(!arch.length){ sec.innerHTML=''; return; }",
"  var h='<button class=\"archhead\" id=\"archtoggle\">Archived ('+arch.length+')<span>'+(archOpen?'&#9662;':'&#9656;')+'</span></button>';",
"  if(archOpen){",
"    h+='<div class=\"archlist\">';",
"    arch.forEach(function(k){",
"      h+='<div class=\"archrow\"><span class=\"atitle\">'+esc(k.title)+'</span>'+",
"        '<button class=\"mini\" data-restore=\"'+k.id+'\">Restore</button>'+",
"        '<button class=\"mini danger2\" data-adel=\"'+k.id+'\">Delete</button></div>';",
"    });",
"    h+='</div>';",
"  }",
"  sec.innerHTML=h;",
"  onTap($('archtoggle'),function(){ archOpen=!archOpen; renderArchive(); });",
"  var rs=sec.querySelectorAll('[data-restore]');",
"  for(var i=0;i<rs.length;i++){ (function(b){ onTap(b,function(){ var k=cardById(b.getAttribute('data-restore')); if(k){ k.archived=false; save(); render(); toast('Restored'); } }); })(rs[i]); }",
"  var ds=sec.querySelectorAll('[data-adel]');",
"  for(var j=0;j<ds.length;j++){ (function(b){ var armed=false; onTap(b,function(){",
"    if(!armed){ armed=true; b.classList.add('armed'); b.textContent='Sure?'; return; }",
"    var id=b.getAttribute('data-adel'); S.cards=S.cards.filter(function(x){ return x.id!==id; }); save(); render(); toast('Deleted');",
"  }); })(ds[j]); }",
"}",
"function boot(){",
"  load();",
"  onTap($('btitlebtn'),function(){ openBoardSheet(); });",
"  onTap($('boardbtn'),function(){ openBoardSheet(); });",
"  onTap($('cancelmove'),function(){ selId=null; updateMoveUI(); });",
"  onTap($('backdrop'),function(){ closeSheet(); });",
"  onTap($('board'),function(e){ if(e.target.closest&&e.target.closest('.card,.colhead,.droppill')) return; if(selId){ selId=null; updateMoveUI(); } });",
"  window.addEventListener('resize',function(){});",
"  window.addEventListener('orientationchange',function(){});",
"  render();",
"}",
"if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot); else boot();"
].join("\n");

var BODY = [
"<div class=\"wrap\">",
"  <header class=\"top\">",
"    <div><p class=\"kicker\">Kanban</p>",
"    <button class=\"btitle\" id=\"btitlebtn\" aria-label=\"rename board\"><h1 id=\"btitle\">Board</h1><span class=\"tp\">&#9998;</span></button></div>",
"    <div class=\"tractions\">",
"      <button class=\"iconbtn hidden\" id=\"cancelmove\" aria-label=\"cancel move\">&times;</button>",
"      <button class=\"iconbtn\" id=\"boardbtn\" aria-label=\"board settings\">&#9881;</button>",
"    </div>",
"  </header>",
"  <div id=\"pwrap\"><div class=\"pbar\"><div class=\"pfill\" id=\"pfill\"></div></div><p class=\"psub\" id=\"psub\"></p></div>",
"  <div id=\"board\"></div>",
"  <div id=\"archsec\"></div>",
"</div>",
"<div id=\"backdrop\"></div>",
"<div id=\"sheet\"></div>",
"<div id=\"toast\"></div>"
].join("\n");

var BOARDS = ['personal', 'work', 'project', 'launch'];
var COLSETS = ['classic', 'flow', 'sprint', 'simple'];
var ACCENTS = ['ocean', 'sunset', 'mint', 'violet'];
var EXTRAS = ['wip', 'progress', 'labels', 'archive'];
var COLNAMES = {
  classic: ['To do', 'Doing', 'Done'],
  flow: ['Backlog', 'To do', 'In progress', 'Done'],
  sprint: ['Backlog', 'To do', 'In progress', 'Review', 'Done'],
  simple: ['To do', 'Done']
};
var BOARDTITLES = { personal: 'Personal Board', work: 'Work Board', project: 'Project Board', launch: 'Launch Board' };
var STARTERS = {
  personal: [
    {c:0, title:'Buy groceries', label:'green'},
    {c:0, title:'Book dentist appointment', label:'blue'},
    {c:1, title:'Plan weekend trip', label:'orange'},
    {c:-1, title:'Water the plants', label:'none'}
  ],
  work: [
    {c:0, title:'Review pull requests', label:'blue'},
    {c:0, title:'Update project roadmap', label:'violet'},
    {c:1, title:'Draft Q3 planning doc', label:'orange'},
    {c:-1, title:'Ship v1.0', label:'green'}
  ],
  project: [
    {c:0, title:'Write the spec', label:'blue'},
    {c:0, title:'Design mockups', label:'violet'},
    {c:1, title:'Build prototype', label:'orange'},
    {c:-1, title:'User testing', label:'green'}
  ],
  launch: [
    {c:0, title:'Landing page copy', label:'blue'},
    {c:0, title:'Record demo video', label:'violet'},
    {c:1, title:'Invite beta users', label:'orange'},
    {c:-1, title:'Launch day checklist', label:'green'}
  ]
};
var THEME = { ocean: '#070b12', sunset: '#100a07', mint: '#07100c', violet: '#0c0812' };

function normConfig(c) {
  c = (c && typeof c === 'object' && !Array.isArray(c)) ? c : {};
  var board = BOARDS.indexOf(c.board) >= 0 ? c.board : 'personal';
  var set = COLSETS.indexOf(c.columns) >= 0 ? c.columns : 'classic';
  var accent = ACCENTS.indexOf(c.accent) >= 0 ? c.accent : 'ocean';
  var ex = Array.isArray(c.extras)
    ? c.extras.filter(function (x) { return EXTRAS.indexOf(x) >= 0; })
    : ['wip', 'progress', 'labels', 'archive'];
  return {
    board: board,
    columns: COLNAMES[set].slice(),
    accent: accent,
    extras: ex,
    title: BOARDTITLES[board],
    starter: STARTERS[board].slice()
  };
}

function build(config) {
  var cfg = normConfig(config);
  var html = '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' +
    '<meta name="theme-color" content="' + THEME[cfg.accent] + '">\n' +
    '<title>Kanban Board</title>\n<style>\n' + CSS + '\n</style>\n</head>\n' +
    '<body data-accent="' + cfg.accent + '">\n' + BODY + '\n' +
    '<script>\nvar CFG=' + JSON.stringify(cfg) + ';\n' + APP + '\n</scr' + 'ipt>\n</body>\n</html>';
  return html;
}

window.MoorKit = { build: build };
})();
