import {T,clamp} from './assets.mjs';
import {buildWorld,disposeWorld} from './worlds.mjs';
import {direct} from './director.mjs';
import {settings,SHOTS,shotAt,buildManifest,FPS,DURATION,VERSION} from './timeline.mjs';
import {createPost} from './post.mjs';
import {drawOverlay} from './overlay.mjs';
import {Score,pcm,wav} from './sound.mjs';
const $=id=>document.getElementById(id),qs=new URLSearchParams(location.search),KEY='vita-verde-project-v1';
let restored={};try{restored=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{}
let config=settings({...restored.settings,...Object.fromEntries(qs),grain:qs.get('grain')??restored.settings?.grain??.2});
const state={time:clamp(Number(qs.get('t')??restored.playhead)||0,0,89.958333),playing:false,ready:false,exporting:false,cancel:false,sound:false,pass:0};
let renderer,post,camera,current,worlds=new Map(),last=0,labelTime=0,frameCounter=0,exportURL,brandTexture;const score=new Score();
const stamp=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const status=t=>$('status').textContent=t;
function persist(){try{localStorage.setItem(KEY,JSON.stringify({...buildManifest(config),playhead:state.time}));}catch{status('This browser could not remember the edit. Save a project file to keep it.');}}
function url(){const u=new URL(location.href);u.search='';for(const [k,v] of Object.entries(config))u.searchParams.set(k,v);u.searchParams.set('t',state.time.toFixed(3));return u;}
function updateLabels(){const shot=shotAt(state.time);$('clock').textContent=`${stamp(state.time)} / 1:30`;$('timeline').value=state.time;$('shotTitle').textContent=shot.title;$('chapterBadge').textContent=`${String(shot.id).padStart(2,'0')} / ${shot.title.toUpperCase()}`;$('play').textContent=state.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',state.playing?'Pause film':'Play film');$('sound').setAttribute('aria-pressed',state.sound);$('sound').setAttribute('aria-label',state.sound?'Mute sound':'Enable sound');$('sound').querySelector('span').textContent=state.sound?'Sound on':'Sound off';document.querySelectorAll('[data-shot]').forEach(b=>b.setAttribute('aria-current',+b.dataset.shot===shot.id));const chapter=state.time<17?0:state.time<44?17:state.time<66?44:66;document.querySelectorAll('[data-time]').forEach(b=>b.classList.toggle('active',+b.dataset.time===chapter));}
function sync(){for(const k of ['seed','store','house','quality','grain'])$(k).value=config[k];$('exportSound').checked=config.sound;$('viewport').classList.toggle('portrait',config.format==='portrait');document.querySelectorAll('[data-format]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.format===config.format));updateLabels();}
function world(kind){if(!worlds.has(kind)){const w=buildWorld(kind,config);if(brandTexture)applyBrand(w);worlds.set(kind,w);}return worlds.get(kind);}
function applyBrand(w){w.scene.traverse(o=>{if(o.name==='printed-wordmark')o.visible=false;if(o.name==='brand-print'){const mat=new T.MeshStandardMaterial({map:brandTexture,roughness:.9});o.material=mat;}});}
function resize(w,h){if(!renderer)return;if(!w){const r=$('viewport').getBoundingClientRect(),scale=config.quality==='balanced'?1:config.quality==='ultra'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.4);w=Math.max(2,Math.round(r.width*scale/2)*2);h=Math.max(2,Math.round(r.height*scale/2)*2);}renderer.setSize(w,h,false);post.resize(w,h);$('overlay').width=w;$('overlay').height=h;camera.aspect=w/h;camera.updateProjectionMatrix();}
function draw(t){const w=world(shotAt(t).world);current=w;const s=direct(w,camera,t,config);post.draw(w,camera,t,config,state.pass);const o=$('overlay'),ctx=o.getContext('2d');ctx.clearRect(0,0,o.width,o.height);if(!state.pass)drawOverlay(ctx,o.width,o.height,t,config);Object.assign($('scene').dataset,{ready:'true',frameTime:t.toFixed(6),seed:config.seed,world:w.kind,shot:String(s.shot.id),owner:s.owner,hero:s.heroId,pass:String(state.pass),drawCalls:renderer.info.render.calls});}
function loop(now){if(state.ready&&!state.exporting){if(state.playing&&last){state.time+=Math.min(.1,(now-last)/1000);if(state.time>=90){state.time=89.958333;state.playing=false;score.stop();persist();}}draw(state.time);frameCounter++;if(now-labelTime>1000){$('renderInfo').textContent=`${config.quality.toUpperCase()} · ${Math.round(frameCounter*1000/(now-labelTime))} FPS · ${current.kind.toUpperCase()}`;frameCounter=0;labelTime=now;}updateLabels();}last=now;requestAnimationFrame(loop);}
async function play(on){if(!state.ready||state.exporting)return;state.playing=on;if(on&&state.time>=89.95)state.time=0;last=performance.now();if(on&&state.sound)try{await score.play(state.time);}catch(e){state.sound=false;status(`Sound could not start: ${e.message}`);}else score.stop();updateLabels();if(!on)persist();}
function seek(t){if(!state.ready||state.exporting)return;state.time=clamp(t,0,89.958333);if(state.sound&&state.playing)score.play(state.time).catch(()=>{});draw(state.time);updateLabels();persist();}
async function rebuild(changes){if(state.exporting)return;if(!state.ready){config=settings({...config,...changes});sync();persist();return;}const was=state.playing;await play(false);config=settings({...config,...changes});for(const w of worlds.values())disposeWorld(w);worlds.clear();sync();resize();draw(state.time);persist();status('A new setting, with the same carrot and the same story.');if(was)await play(true);}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function dimensions(){const short=+$('resolution').value,long=Math.round(short*16/9/2)*2;return config.format==='portrait'?{w:short,h:long}:{w:long,h:short};}
function composite(target){const c=target||document.createElement('canvas');c.width=$('scene').width;c.height=$('scene').height;const ctx=c.getContext('2d',{alpha:false});ctx.drawImage($('scene'),0,0);ctx.drawImage($('overlay'),0,0);return c;}
async function still(){if(!state.ready||state.exporting)return;const d=dimensions();try{state.exporting=true;resize(d.w,d.h);draw(state.time);const blob=await new Promise(r=>composite().toBlob(r,'image/png'));if(!blob)throw Error('The image could not be created.');download(blob,`vita-verde-${config.seed}-${state.time.toFixed(2)}s${state.pass?'-pass'+state.pass:''}.png`);status('Saved the current frame.');}catch(e){status(e.message);}finally{state.exporting=false;resize();draw(state.time);}}
async function exportVideo(options={}){
 if(!state.ready||state.exporting)return;const shot=shotAt(state.time),whole=$('range').value==='film',start=options.start??(whole?0:shot.start),seconds=options.seconds??(whole?90:shot.end-shot.start),fps=24,{w,h}=options.w?options:dimensions(),frames=Math.round(seconds*fps),sound=$('exportSound').checked;
 if(start<0||seconds<=0||start+seconds>90.00001){status('A film export must stay within its 90-second timeline.');return;}
 const saved={time:state.time,playing:state.playing,pass:state.pass};await play(false);state.exporting=true;state.cancel=false;state.pass=0;let ve,ae,muxer,asyncError,wakeLock,chunks=0,audioChunks=0;
 if(exportURL)URL.revokeObjectURL(exportURL);$('exportTitle').textContent='Making your film.';$('exportDetail').textContent=`${w} × ${h} · 24 fps · ${seconds}s · ${sound?'original score & foley':'silent'}`;$('progress').value=0;$('exportActions').replaceChildren($('cancelExport'));$('cancelExport').hidden=false;$('cancelExport').textContent='Cancel render';$('exportDialog').showModal();
 try{
  if(!window.VideoEncoder||!window.VideoFrame)throw Error('This browser cannot encode MP4. Use a current browser with WebCodecs support, or save PNG frames.');
  const codec=w*h>2300000?'avc1.640033':'avc1.420028',vc={codec,width:w,height:h,bitrate:Math.min(45000000,w*h*7),framerate:24};
  if(!(await VideoEncoder.isConfigSupported(vc)).supported)throw Error('This device cannot encode that size. Select 720p or 1080p.');
  if(w>renderer.capabilities.maxTextureSize||h>renderer.capabilities.maxTextureSize)throw Error('Choose a smaller export size for this device.');
  const ac={codec:'mp4a.40.2',sampleRate:48000,numberOfChannels:1,bitrate:160000};
  if(sound&&(!window.AudioEncoder||!window.AudioData||!(await AudioEncoder.isConfigSupported(ac)).supported))throw Error('AAC audio export is unavailable on this browser. Uncheck “Include original score & foley” and download the Score WAV separately.');
  muxer=new window.Mp4Muxer.Muxer({target:new window.Mp4Muxer.ArrayBufferTarget(),video:{codec:'avc',width:w,height:h},...(sound?{audio:{codec:'aac',sampleRate:48000,numberOfChannels:1}}:{}),fastStart:'in-memory',firstTimestampBehavior:'offset'});
  ve=new VideoEncoder({output(chunk,meta){try{const bytes=new Uint8Array(chunk.byteLength);chunk.copyTo(bytes);muxer.addVideoChunkRaw(bytes,chunk.type,chunk.timestamp,chunk.duration||Math.round(1e6/fps),meta);chunks++;}catch(e){asyncError=e;}},error:e=>asyncError=e});ve.configure(vc);
  if(sound){ae=new AudioEncoder({output(chunk,meta){try{muxer.addAudioChunk(chunk,meta);audioChunks++;}catch(e){asyncError=e;}},error:e=>asyncError=e});ae.configure(ac);}
  const c=document.createElement('canvas');try{wakeLock=await navigator.wakeLock?.request('screen');}catch{}resize(w,h);const began=performance.now();
  for(let i=0;i<frames;i++){
   if(state.cancel)throw Error('Render cancelled. No partial file was saved.');if(asyncError)throw asyncError;
   while(ve.encodeQueueSize>6||(ae&&ae.encodeQueueSize>10)){await new Promise(r=>setTimeout(r,10));if(asyncError)throw asyncError;if(state.cancel)throw Error('Render cancelled. No partial file was saved.');}
   const t=start+i/fps;draw(t);composite(c);const frame=new VideoFrame(c,{timestamp:Math.round(i*1e6/fps),duration:Math.round(1e6/fps),alpha:'discard'});try{ve.encode(frame,{keyFrame:i%48===0});}finally{frame.close();}
   if(ae){const samples=pcm(t,1/fps),audio=new AudioData({format:'f32',sampleRate:48000,numberOfFrames:samples.length,numberOfChannels:1,timestamp:Math.round(i*1e6/fps),data:samples});try{ae.encode(audio);}finally{audio.close();}}
   if(i%4===0||i===frames-1){$('progress').value=(i+1)/frames;$('exportStatus').textContent=`Frame ${i+1} of ${frames} · ${((i+1)/((performance.now()-began)/1000)).toFixed(1)} frames/sec`;await new Promise(requestAnimationFrame);}
  }
  await ve.flush();if(ae)await ae.flush();if(asyncError)throw asyncError;if(!chunks||(sound&&!audioChunks))throw Error('The encoder returned an empty track.');muxer.finalize();const bytes=muxer.target.buffer,blob=new Blob([bytes],{type:'video/mp4'});if(blob.size<1500)throw Error('The output is empty.');window.__renderResult=bytes;exportURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=exportURL;a.download=`vita-verde-${config.seed}-${whole?'film':'shot-'+shot.id}.mp4`;a.textContent='Download MP4';$('exportActions').append(a);$('cancelExport').textContent='Back to the film';$('exportTitle').textContent='Your film is ready.';$('exportStatus').textContent=`${chunks} frames · ${(blob.size/1048576).toFixed(1)} MB${sound?' · with audio':''}`;Object.assign($('exportDialog').dataset,{frames:String(chunks),audioChunks:String(audioChunks),bytes:String(blob.size),duration:String(seconds)});status('Film rendered. Download your MP4 from the export window.');
 }catch(e){$('exportTitle').textContent=state.cancel?'Render cancelled.':'Couldn’t finish the render.';$('exportStatus').textContent=e.message;$('cancelExport').textContent='Back to the film';console.warn(e);}
 finally{try{ve?.close();ae?.close();}catch{}try{await wakeLock?.release();}catch{}state.exporting=false;state.time=saved.time;state.pass=saved.pass;resize();draw(state.time);last=performance.now();if(saved.playing)await play(true);}
}
$('watch').onclick=async()=>{seek(0);state.sound=true;await play(true);$('viewport').scrollIntoView({behavior:'smooth',block:'center'});};$('play').onclick=()=>play(!state.playing);$('restart').onclick=()=>seek(0);$('timeline').oninput=()=>seek(+$('timeline').value);$('sound').onclick=async()=>{state.sound=!state.sound;if(state.playing)await play(true);else score.stop();updateLabels();};
for(const s of SHOTS){const b=document.createElement('button');b.dataset.shot=s.id;b.innerHTML=`<b>${String(s.id).padStart(2,'0')}</b><span>${s.title}</span><small>${stamp(s.start)}</small>`;b.onclick=()=>seek(s.start);$('shots').append(b);}
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>seek(+b.dataset.time));document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>rebuild({format:b.dataset.format}));for(const k of ['seed','store','house'])$(k).onchange=()=>rebuild({[k]:$(k).value});$('newSeed').onclick=()=>{const a=crypto.getRandomValues(new Uint32Array(1))[0].toString(16).toUpperCase();rebuild({seed:'VV1-'+a});};$('quality').onchange=()=>{config.quality=$('quality').value;resize();persist();};$('grain').oninput=()=>{config.grain=+$('grain').value;persist();};$('pass').onchange=()=>state.pass=+$('pass').value;
$('exportSound').onchange=()=>{config.sound=$('exportSound').checked;persist();};$('saveStill').onclick=still;$('exportVideo').onclick=()=>exportVideo();$('cancelExport').onclick=()=>{if(state.exporting)state.cancel=true;else $('exportDialog').close();};$('exportDialog').addEventListener('cancel',e=>{if(state.exporting){e.preventDefault();state.cancel=true;}});
$('saveProject').onclick=()=>{download(new Blob([JSON.stringify({...buildManifest(config),playhead:state.time},null,2)],{type:'application/json'}),`vita-verde-${config.seed}.json`);persist();status('Saved the seed, settings, and playhead.');};$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('That project file is too large.');const p=JSON.parse(await file.text());if(p.engine!=='vita-verde'||p.schemaVersion!==1||!p.settings||!Number.isFinite(p.playhead??0))throw Error('Choose a Vita Verde version 1 project file.');state.time=clamp(p.playhead||0,0,89.958333);await rebuild(p.settings);status('Project restored.');}catch(error){status(error.message);}finally{e.target.value='';}};
$('saveAudio').onclick=()=>{download(new Blob([wav()],{type:'audio/wav'}),'vita-verde-original-score.wav');status('Saved the complete original score and foley as WAV.');};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(url().href);status('Copied the scene, settings, and playhead.');}catch{status(url().href);}};
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('viewport').requestFullscreen?.();};window.addEventListener('resize',()=>{if(!state.exporting)resize();});document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden&&state.playing)play(false);});document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||state.exporting)return;if(e.code==='Space'){e.preventDefault();play(!state.playing);}if(e.key==='ArrowRight')seek(state.time+1);if(e.key==='ArrowLeft')seek(state.time-1);if(e.key.toLowerCase()==='h'){document.body.classList.toggle('clean');resize();}});
$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();state.ready=false;state.cancel=true;state.playing=false;score.stop();status('Graphics memory was interrupted. Save your project, reload, and select Balanced quality.');});
async function init(){sync();try{
 const canvas=$('scene'),gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('This film needs WebGL 2. Enable graphics acceleration or use another browser. Your project settings and score downloads remain available.');
 renderer=new T.WebGLRenderer({canvas,context:gl,antialias:true,preserveDrawingBuffer:true});renderer.outputColorSpace=T.LinearSRGBColorSpace;renderer.toneMapping=T.NoToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.debug.onShaderError=(gl,p)=>{console.error(gl.getProgramInfoLog(p));status('A graphics shader could not compile on this device.');};camera=new T.PerspectiveCamera(44,16/9,.008,140);post=createPost(renderer);brandTexture=await new T.TextureLoader().loadAsync('vita-verde/brand.png');brandTexture.colorSpace=T.SRGBColorSpace;brandTexture.anisotropy=4;resize();draw(state.time);state.ready=true;$('loading').hidden=true;window.__renderCanvas=canvas;requestAnimationFrame(loop);status('Ready. Watch the film, explore a shot, or grow another world.');if(qs.get('render')==='1')await exportVideo({start:0,seconds:Math.min(90,Math.max(1,Number(qs.get('seconds'))||90)),w:Math.max(64,Math.round((+qs.get('w')||1280)/2)*2),h:Math.max(64,Math.round((+qs.get('h')||720)/2)*2)});
 }catch(e){$('loading').querySelector('strong').textContent='The scene couldn’t start.';$('loadText').textContent=e.message;$('renderInfo').textContent='GRAPHICS UNAVAILABLE';status(e.message);console.error(e);}}
init();
