/* Moor kit: habit-tracker v1.0.0
 * Engine: window.MoorKit.build(config) -> complete <!DOCTYPE html> document.
 * config: { vibe: "midnight"|"paper"|"forest", tracking: ["streaks","grid","ring"], starter: "fitness"|"mindful"|"productive"|"blank" }
 * Touch-first: all taps handled via pointerup (never synthesized click).
 * Storage: localStorage wrapped in try/catch; app runs fully in-memory if blocked.
 */
(function () {
'use strict';

var CSS = [
"*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}",
"html,body{margin:0;padding:0}",
"body{font-family:-apple-system,BlinkMacSystemFont,'SF Pro Text','Segoe UI',Roboto,sans-serif;min-height:100vh;background:var(--bg);color:var(--tx);touch-action:manipulation;-webkit-font-smoothing:antialiased}",
"body[data-vibe=midnight]{--bg:#0a0c10;--card:rgba(255,255,255,.045);--card2:rgba(255,255,255,.08);--tx:#f2f4f8;--mut:#8b93a3;--line:rgba(255,255,255,.1);--acc:#ff9f43;--acc2:#ff7b2e;--ok:#4ade80;--sheet:#14171d}",
"body[data-vibe=paper]{--bg:#f5efe3;--card:#fffdf7;--card2:#ece2cd;--tx:#2b2620;--mut:#8a8071;--line:rgba(60,50,35,.14);--acc:#e07b39;--acc2:#c96425;--ok:#2f9e5f;--sheet:#fffdf7}",
"body[data-vibe=forest]{--bg:#0c1411;--card:rgba(255,255,255,.05);--card2:rgba(255,255,255,.09);--tx:#edf4ee;--mut:#8fa398;--line:rgba(255,255,255,.11);--acc:#ffb14d;--acc2:#ff8f2b;--ok:#5fd68a;--sheet:#101915}",
".wrap{max-width:520px;margin:0 auto;padding:calc(env(safe-area-inset-top,0px) + 22px) 18px calc(env(safe-area-inset-bottom,0px) + 110px)}",
".head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:6px}",
".date-line{font-size:13px;color:var(--mut);letter-spacing:.4px;margin:0 0 2px}",
"h1{font-size:34px;font-weight:800;margin:0;letter-spacing:-.5px}",
".sub{font-size:14px;color:var(--mut);margin:6px 0 18px}",
".ringbox{width:96px;height:96px;flex:none;position:relative}",
".ringbox svg{width:96px;height:96px;transform:rotate(-90deg)}",
".ring-lab{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}",
".ring-lab b{font-size:20px}",
".ring-lab span{font-size:10px;color:var(--mut)}",
".sec{font-size:12px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase;color:var(--mut);margin:22px 2px 10px}",
".hcard{display:flex;align-items:center;gap:14px;background:var(--card);border:1px solid var(--line);border-radius:16px;padding:14px;margin-bottom:10px}",
".check{width:56px;height:56px;flex:none;border-radius:50%;border:2px solid var(--line);background:transparent;color:transparent;font-size:24px;display:flex;align-items:center;justify-content:center;cursor:pointer;position:relative;transition:transform .12s ease,background .2s,border-color .2s}",
".check.done{background:linear-gradient(135deg,var(--acc),var(--acc2));border-color:transparent;color:#fff}",
".check.pop{animation:pop .35s ease}",
"@keyframes pop{0%{transform:scale(1)}40%{transform:scale(1.28)}100%{transform:scale(1)}}",
".hinfo{flex:1;min-width:0}",
".hname{font-size:16px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
".hmeta{display:flex;align-items:center;gap:8px;margin-top:4px}",
".freq{font-size:11px;font-weight:700;letter-spacing:.6px;text-transform:uppercase;color:var(--mut);background:var(--card2);padding:3px 8px;border-radius:99px}",
".streak{font-size:14px;font-weight:800;color:var(--acc)}",
".streak.zero{color:var(--mut);font-weight:600}",
".editbtn{width:44px;height:44px;flex:none;border-radius:12px;border:1px solid var(--line);background:transparent;color:var(--mut);font-size:18px;display:flex;align-items:center;justify-content:center;cursor:pointer}",
".burst{position:fixed;width:8px;height:8px;border-radius:50%;background:var(--acc);pointer-events:none;z-index:60;animation:burst .55s ease-out forwards}",
"@keyframes burst{0%{transform:translate(0,0) scale(1);opacity:1}100%{transform:translate(var(--dx),var(--dy)) scale(.2);opacity:0}}",
".grid{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:14px;overflow:hidden}",
".grow{display:flex;align-items:center;margin-bottom:6px}",
".grow:last-child{margin-bottom:0}",
".gname{width:92px;flex:none;font-size:12px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--tx)}",
".gcells{flex:1;display:flex;justify-content:space-between}",
".gcell{width:30px;height:30px;border-radius:9px;background:var(--card2);display:flex;align-items:center;justify-content:center;font-size:14px;color:#fff}",
".gcell.hit{background:linear-gradient(135deg,var(--acc),var(--acc2))}",
".ghead{font-size:10px;color:var(--mut);font-weight:700}",
".ghead.today{color:var(--acc)}",
".gcell.today{outline:2px solid var(--acc);outline-offset:-2px}",
".empty{text-align:center;color:var(--mut);padding:34px 20px;font-size:14px;line-height:1.6}",
".empty .big{font-size:40px;display:block;margin-bottom:10px}",
".fab{position:fixed;right:20px;bottom:calc(env(safe-area-inset-bottom,0px) + 24px);width:62px;height:62px;border-radius:50%;border:none;background:linear-gradient(135deg,var(--acc),var(--acc2));color:#fff;font-size:30px;line-height:1;box-shadow:0 10px 28px rgba(0,0,0,.35);cursor:pointer;z-index:40}",
"#backdrop{position:fixed;inset:0;background:rgba(0,0,0,.5);opacity:0;pointer-events:none;transition:opacity .25s;z-index:50}",
"#backdrop.on{opacity:1;pointer-events:auto}",
"#sheet{position:fixed;left:0;right:0;bottom:0;max-width:520px;margin:0 auto;background:var(--sheet);border-radius:22px 22px 0 0;padding:18px 18px calc(env(safe-area-inset-bottom,0px) + 22px);transform:translateY(105%);transition:transform .28s cubic-bezier(.2,.9,.25,1);z-index:51;border-top:1px solid var(--line)}",
"#sheet.on{transform:translateY(0)}",
"#sheet h2{margin:2px 0 14px;font-size:20px}",
".field{margin-bottom:14px}",
".field label{display:block;font-size:12px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:var(--mut);margin-bottom:8px}",
".field input[type=text]{width:100%;font-size:17px;padding:14px;border-radius:14px;border:1px solid var(--line);background:var(--card);color:var(--tx);outline:none}",
".seg{display:flex;background:var(--card2);border-radius:14px;padding:4px}",
".seg button{flex:1;border:none;background:transparent;color:var(--mut);font-size:15px;font-weight:700;padding:12px;border-radius:10px;cursor:pointer}",
".seg button.sel{background:var(--card);color:var(--tx);box-shadow:0 2px 8px rgba(0,0,0,.18)}",
".cta{width:100%;border:none;border-radius:16px;padding:16px;font-size:17px;font-weight:800;background:linear-gradient(135deg,var(--acc),var(--acc2));color:#fff;cursor:pointer;margin-top:6px}",
".danger{width:100%;border:1px solid var(--line);border-radius:16px;padding:14px;font-size:15px;font-weight:700;background:transparent;color:#e5484d;cursor:pointer;margin-top:10px}",
".danger.armed{background:#e5484d;color:#fff;border-color:#e5484d}",
"#toast{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom,0px) + 100px);transform:translateX(-50%) translateY(20px);background:var(--tx);color:var(--bg);font-size:14px;font-weight:700;padding:12px 20px;border-radius:99px;opacity:0;pointer-events:none;transition:all .3s;z-index:70;white-space:nowrap}",
"#toast.on{opacity:1;transform:translateX(-50%) translateY(0)}"
].join("\n");

var APP = [
"/* Habit Tracker app. CFG is injected above: {vibe, tracking:[], starter} */",
"function $(id){ return document.getElementById(id); }",
"function esc(s){ var d=document.createElement('div'); d.textContent=String(s==null?'':s); return d.innerHTML; }",
"function onTap(el, fn){",
"  var sx=0, sy=0, down=false;",
"  el.addEventListener('pointerdown', function(e){ down=true; sx=e.clientX; sy=e.clientY; });",
"  el.addEventListener('pointerup', function(e){ if(!down) return; down=false; if(Math.abs(e.clientX-sx)<14 && Math.abs(e.clientY-sy)<14){ fn(e); } });",
"  el.addEventListener('pointercancel', function(){ down=false; });",
"}",
"var store = {",
"  read: function(){ try{ var r=localStorage.getItem('habittracker.v1'); return r?JSON.parse(r):null; }catch(e){ return null; } },",
"  write: function(s){ try{ localStorage.setItem('habittracker.v1', JSON.stringify(s)); }catch(e){} }",
"};",
"function pad(n){ return (n<10?'0':'')+n; }",
"function dstr(d){ return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()); }",
"function parseD(s){ var p=String(s).split('-'); return new Date(+p[0], (+p[1]||1)-1, (+p[2]||1)); }",
"function todayKey(){ return dstr(new Date()); }",
"function shiftDays(key, n){ var d=parseD(key); d.setDate(d.getDate()+n); return dstr(d); }",
"function weekKey(d){",
"  var t=new Date(d.getTime()); t.setHours(0,0,0,0);",
"  t.setDate(t.getDate()+3-((t.getDay()+6)%7));",
"  var y=t.getFullYear(), w1=new Date(y,0,4);",
"  var w=1+Math.round(((t.getTime()-w1.getTime())/86400000-3+((w1.getDay()+6)%7))/7);",
"  return y+'-W'+(w<10?'0':'')+w;",
"}",
"function dayLetter(d){ return ['S','M','T','W','T','F','S'][d.getDay()]; }",
"function thisWeekOffset(){ var wk=weekKey(new Date()); for(var off=0; off>=-6; off--){ if(weekKey(parseD(shiftDays(todayKey(),off)))===wk) return off; } return 0; }",
"var uid=1;",
"function mkHabit(name, freq, offsets){",
"  var log={}, t=todayKey();",
"  (offsets||[]).forEach(function(off){ log[shiftDays(t,off)]=true; });",
"  return { id:'h'+(uid++), name:name, freq:freq, log:log, created:t };",
"}",
"function seedHabits(kind){",
"  uid=1; var wkOff=thisWeekOffset();",
"  if(kind==='mindful') return [ mkHabit('Meditate 10 min','daily',[-1,-2,-3]), mkHabit('Read 20 pages','daily',[-1]), mkHabit('Journal','weekly',[wkOff]) ];",
"  if(kind==='productive') return [ mkHabit('Deep work 90 min','daily',[-1,-2]), mkHabit('Plan tomorrow','daily',[]), mkHabit('Inbox zero','weekly',[wkOff-7]) ];",
"  if(kind==='blank') return [];",
"  return [ mkHabit('Morning workout','daily',[-1,-2]), mkHabit('10k steps','daily',[-1]), mkHabit('Sunday long run','weekly',[wkOff-7]) ];",
"}",
"function dailyStreak(h){",
"  var s=0, d=new Date(), t=todayKey();",
"  if(!h.log[t]) d.setDate(d.getDate()-1);",
"  while(h.log[dstr(d)]){ s++; d.setDate(d.getDate()-1); }",
"  return s;",
"}",
"function weeklyStreak(h){",
"  var weeks={}, k;",
"  for(k in h.log){ if(h.log[k]) weeks[weekKey(parseD(k))]=true; }",
"  var s=0, d=new Date(), wk=weekKey(d);",
"  if(!weeks[wk]){ d.setDate(d.getDate()-7); wk=weekKey(d); }",
"  while(weeks[wk]){ s++; d.setDate(d.getDate()-7); wk=weekKey(d); }",
"  return s;",
"}",
"function streakOf(h){ return h.freq==='weekly' ? weeklyStreak(h) : dailyStreak(h); }",
"function isDoneToday(h){",
"  var t=todayKey();",
"  if(h.freq==='daily') return !!h.log[t];",
"  var wk=weekKey(new Date());",
"  for(var k in h.log){ if(h.log[k] && weekKey(parseD(k))===wk) return true; }",
"  return false;",
"}",
"function isDueToday(h){ return h.freq==='daily' ? !h.log[todayKey()] : !isDoneToday(h); }",
"function findHabit(id){ for(var i=0;i<state.habits.length;i++){ if(state.habits[i].id===id) return state.habits[i]; } return null; }",
"var state=store.read();",
"if(!state || !Array.isArray(state.habits)){ state={ habits: seedHabits(CFG.starter) }; store.write(state); }",
"function save(){ store.write(state); }",
"var showStreaks=CFG.tracking.indexOf('streaks')>=0;",
"var showGrid=CFG.tracking.indexOf('grid')>=0;",
"var showRing=CFG.tracking.indexOf('ring')>=0;",
"var toastT=null;",
"function toast(msg){ var t=$('toast'); t.textContent=msg; t.classList.add('on'); clearTimeout(toastT); toastT=setTimeout(function(){ t.classList.remove('on'); },2200); }",
"function burst(x,y){",
"  for(var i=0;i<10;i++){",
"    var s=document.createElement('span'); s.className='burst';",
"    var a=Math.random()*Math.PI*2, r=40+Math.random()*55;",
"    s.style.left=x+'px'; s.style.top=y+'px';",
"    s.style.setProperty('--dx', Math.cos(a)*r+'px');",
"    s.style.setProperty('--dy', Math.sin(a)*r+'px');",
"    document.body.appendChild(s);",
"    (function(el){ setTimeout(function(){ if(el.parentNode) el.parentNode.removeChild(el); }, 650); })(s);",
"  }",
"}",
"var pendingBurst=null;",
"function celebrate(btn,h){",
"  btn.classList.remove('pop'); void btn.offsetWidth; btn.classList.add('pop');",
"  if(pendingBurst){ burst(pendingBurst.x, pendingBurst.y); pendingBurst=null; }",
"  try{ if(navigator.vibrate) navigator.vibrate(12); }catch(e){}",
"  var st=streakOf(h);",
"  toast(st>1 ? '\\uD83D\\uDD25 '+st+'-day streak!' : 'Logged. Keep it going!');",
"}"
].join("\n");

APP += "\n" + [
"function toggleHabit(id, btnEl){",
"  var h=findHabit(id); if(!h) return;",
"  var t=todayKey();",
"  if(h.freq==='daily'){",
"    if(h.log[t]){ delete h.log[t]; } else { h.log[t]=true; celebrate(btnEl,h); }",
"  } else {",
"    var wk=weekKey(new Date());",
"    if(isDoneToday(h)){ for(var k in h.log){ if(h.log[k] && weekKey(parseD(k))===wk) delete h.log[k]; } }",
"    else { h.log[t]=true; celebrate(btnEl,h); }",
"  }",
"  renderAll();",
"}",
"function renderHead(){",
"  var d=new Date();",
"  var days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];",
"  var months=['January','February','March','April','May','June','July','August','September','October','November','December'];",
"  $('dateline').textContent=days[d.getDay()]+', '+months[d.getMonth()]+' '+d.getDate();",
"  var due=state.habits.filter(isDueToday);",
"  var done=state.habits.length-due.length;",
"  $('subline').textContent = state.habits.length===0 ? 'Build one good day at a time.' : (due.length===0 ? 'All done for today. \\uD83C\\uDF89' : done+' of '+state.habits.length+' done today');",
"  var rb=$('ringbox');",
"  if(!showRing){ rb.style.display='none'; return; }",
"  rb.style.display='block';",
"  var pct = state.habits.length===0 ? 0 : (due.length===0 ? 1 : done/state.habits.length);",
"  var C=251.33;",
"  $('ringfg').setAttribute('stroke-dasharray', (C*pct).toFixed(1)+' '+C);",
"  $('ringpct').textContent=Math.round(pct*100)+'%';",
"}",
"function renderList(){",
"  var el=$('list');",
"  var h='<div class=\"sec\">Habits</div>';",
"  if(!state.habits.length){ h+='<div class=\"empty\"><span class=\"big\">\\uD83C\\uDF31</span>No habits yet.<br>Tap + to plant your first one.</div>'; }",
"  state.habits.forEach(function(x){",
"    var done=isDoneToday(x), st=streakOf(x);",
"    h+='<div class=\"hcard\">'",
"    h+='<button class=\"check'+(done?' done':'')+'\" data-check=\"'+x.id+'\" aria-label=\"check off\">'+(done?'\\u2713':'')+'</button>';",
"    h+='<div class=\"hinfo\"><div class=\"hname\">'+esc(x.name)+'</div><div class=\"hmeta\">';",
"    h+='<span class=\"freq\">'+(x.freq==='weekly'?'Weekly':'Daily')+'</span>';",
"    if(showStreaks){ h+='<span class=\"streak'+(st?'':' zero')+'\">'+(st?'\\uD83D\\uDD25 '+st:'no streak yet')+'</span>'; }",
"    h+='</div></div>';",
"    h+='<button class=\"editbtn\" data-edit=\"'+x.id+'\" aria-label=\"edit\">\\u270E</button>';",
"    h+='</div>';",
"  });",
"  el.innerHTML=h;",
"  var i, checks=el.querySelectorAll('[data-check]');",
"  for(i=0;i<checks.length;i++)(function(b){ onTap(b,function(){ var r=b.getBoundingClientRect(); pendingBurst={x:r.left+r.width/2,y:r.top+r.height/2}; toggleHabit(b.getAttribute('data-check'),b); }); })(checks[i]);",
"  var edits=el.querySelectorAll('[data-edit]');",
"  for(i=0;i<edits.length;i++)(function(b){ onTap(b,function(){ openSheet(b.getAttribute('data-edit')); }); })(edits[i]);",
"}",
"function renderGrid(){",
"  var sec=$('gridsec');",
"  if(!showGrid || !state.habits.length){ sec.style.display='none'; sec.innerHTML=''; return; }",
"  sec.style.display='block';",
"  var days=[]; for(var i=6;i>=0;i--){ var d=new Date(); d.setDate(d.getDate()-i); days.push(d); }",
"  var h='<div class=\"sec\">This week</div><div class=\"grid\">';",
"  h+='<div class=\"grow\"><div class=\"gname\"></div><div class=\"gcells\">'+days.map(function(d,i){ return '<div class=\"gcell ghead'+(i===6?' today':'')+'\">'+dayLetter(d)+'</div>'; }).join('')+'</div></div>';",
"  state.habits.forEach(function(x){",
"    h+='<div class=\"grow\"><div class=\"gname\">'+esc(x.name)+'</div><div class=\"gcells\">'+days.map(function(d,i){",
"      var hit=!!x.log[dstr(d)];",
"      return '<div class=\"gcell'+(hit?' hit':'')+(i===6?' today':'')+'\">'+(hit?'\\u2713':'')+'</div>';",
"    }).join('')+'</div></div>';",
"  });",
"  h+='</div>'; sec.innerHTML=h;",
"}",
"function renderAll(){ renderHead(); renderList(); renderGrid(); save(); }",
"var editingId=null, sheetFreq='daily';",
"function paintSeg(){ $('seg-daily').className = sheetFreq==='daily' ? 'sel' : ''; $('seg-weekly').className = sheetFreq==='weekly' ? 'sel' : ''; }",
"function openSheet(id){",
"  editingId=id||null;",
"  var h=id?findHabit(id):null;",
"  $('sheet-title').textContent = h ? 'Edit habit' : 'New habit';",
"  $('fname').value = h ? h.name : '';",
"  sheetFreq = h ? h.freq : 'daily';",
"  paintSeg();",
"  var del=$('delbtn');",
"  del.style.display = h ? 'block' : 'none';",
"  del.className='danger'; del.textContent='Delete habit';",
"  $('backdrop').classList.add('on'); $('sheet').classList.add('on');",
"  setTimeout(function(){ try{ $('fname').focus(); }catch(e){} }, 320);",
"}",
"function closeSheet(){ $('backdrop').classList.remove('on'); $('sheet').classList.remove('on'); }",
"function saveSheet(){",
"  var name=$('fname').value.trim();",
"  if(!name){ toast('Give your habit a name'); return; }",
"  if(editingId){ var h=findHabit(editingId); if(h){ h.name=name.slice(0,60); h.freq=sheetFreq; } }",
"  else { state.habits.push({ id:'h'+(uid++), name:name.slice(0,60), freq:sheetFreq, log:{}, created:todayKey() }); }",
"  closeSheet(); renderAll(); toast(editingId?'Habit updated':'Habit added');",
"}",
"function deleteTap(){",
"  var b=$('delbtn');",
"  if(b.className.indexOf('armed')>=0){",
"    state.habits=state.habits.filter(function(x){ return x.id!==editingId; });",
"    closeSheet(); renderAll(); toast('Habit deleted');",
"  } else {",
"    b.className='danger armed'; b.textContent='Tap again to confirm delete';",
"    setTimeout(function(){ b.className='danger'; b.textContent='Delete habit'; }, 3000);",
"  }",
"}",
"function init(){",
"  state.habits.forEach(function(h){ var m=/^h(\\d+)$/.exec(h.id||''); if(m) uid=Math.max(uid, +m[1]+1); });",
"  renderAll();",
"  onTap($('fab'), function(){ openSheet(null); });",
"  onTap($('backdrop'), closeSheet);",
"  onTap($('savebtn'), saveSheet);",
"  onTap($('delbtn'), deleteTap);",
"  onTap($('seg-daily'), function(){ sheetFreq='daily'; paintSeg(); });",
"  onTap($('seg-weekly'), function(){ sheetFreq='weekly'; paintSeg(); });",
"  window.addEventListener('resize', function(){ renderGrid(); });",
"  window.addEventListener('orientationchange', function(){ setTimeout(renderGrid, 300); });",
"}",
"window.MOOR_DEBUG={ state:function(){ return state; }, streakOf:streakOf, isDoneToday:isDoneToday };",
"init();"
].join("\n");

var BODY = [
"<div class=\"wrap\">",
"  <div class=\"head\">",
"    <div><p class=\"date-line\" id=\"dateline\"></p><h1>Habits</h1><p class=\"sub\" id=\"subline\"></p></div>",
"    <div class=\"ringbox\" id=\"ringbox\"><svg viewBox=\"0 0 96 96\"><circle cx=\"48\" cy=\"48\" r=\"40\" fill=\"none\" stroke=\"var(--card2)\" stroke-width=\"10\"/><circle id=\"ringfg\" cx=\"48\" cy=\"48\" r=\"40\" fill=\"none\" stroke=\"var(--acc)\" stroke-width=\"10\" stroke-linecap=\"round\" stroke-dasharray=\"0 251.33\"/></svg><div class=\"ring-lab\"><b id=\"ringpct\">0%</b><span>today</span></div></div>",
"  </div>",
"  <div id=\"gridsec\"></div>",
"  <div id=\"list\"></div>",
"</div>",
"<button class=\"fab\" id=\"fab\" aria-label=\"add habit\">+</button>",
"<div id=\"backdrop\"></div>",
"<div id=\"sheet\">",
"  <h2 id=\"sheet-title\">New habit</h2>",
"  <div class=\"field\"><label>Name</label><input type=\"text\" id=\"fname\" placeholder=\"e.g. Morning run\" maxlength=\"60\" autocomplete=\"off\"></div>",
"  <div class=\"field\"><label>Repeat</label><div class=\"seg\"><button id=\"seg-daily\">Daily</button><button id=\"seg-weekly\">Weekly</button></div></div>",
"  <button class=\"cta\" id=\"savebtn\">Save habit</button>",
"  <button class=\"danger\" id=\"delbtn\" style=\"display:none\">Delete habit</button>",
"</div>",
"<div id=\"toast\"></div>"
].join("\n");

var VIBES = ['midnight', 'paper', 'forest'];
var STARTERS = ['fitness', 'mindful', 'productive', 'blank'];
var TRACKS = ['streaks', 'grid', 'ring'];
var THEME = { midnight: '#0a0c10', paper: '#f5efe3', forest: '#0c1411' };

function normConfig(c) {
  c = (c && typeof c === 'object' && !Array.isArray(c)) ? c : {};
  var vibe = VIBES.indexOf(c.vibe) >= 0 ? c.vibe : 'midnight';
  var starter = STARTERS.indexOf(c.starter) >= 0 ? c.starter : 'fitness';
  var tr = Array.isArray(c.tracking)
    ? c.tracking.filter(function (t) { return TRACKS.indexOf(t) >= 0; })
    : ['streaks', 'grid', 'ring'];
  return { vibe: vibe, tracking: tr, starter: starter };
}

function build(config) {
  var cfg = normConfig(config);
  var html = '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' +
    '<meta name="theme-color" content="' + THEME[cfg.vibe] + '">\n' +
    '<title>Habit Tracker</title>\n<style>\n' + CSS + '\n</style>\n</head>\n' +
    '<body data-vibe="' + cfg.vibe + '">\n' + BODY + '\n' +
    '<script>\nvar CFG=' + JSON.stringify(cfg) + ';\n' + APP + '\n</scr' + 'ipt>\n</body>\n</html>';
  return html;
}

window.MoorKit = { build: build };
})();
