import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {T,carrot} from '../../vita-verde/assets.mjs';import {settings,SHOTS,shotAt,storyState,buildManifest} from '../../vita-verde/timeline.mjs';import {buildWorld} from '../../vita-verde/worlds.mjs';import {direct,laneMotion,reach} from '../../vita-verde/director.mjs';import {pcm,wav} from '../../vita-verde/sound.mjs';
const config=settings(),camera=new T.PerspectiveCamera(44,16/9,.008,140),worlds=new Map();function world(kind){if(!worlds.has(kind))worlds.set(kind,buildWorld(kind,config));return worlds.get(kind);}
function snapshot(w,t){direct(w,camera,t,config);const a=[];w.scene.traverseVisible(o=>{if(o.isMesh)a.push([o.uuid,...o.matrixWorld.elements.map(v=>Math.round(v*1e7)/1e7)]);});return {a,view:camera.matrixWorld.elements.map(v=>Math.round(v*1e7)/1e7)};}
test('All 2160 frames belong to exactly one of the 20 contiguous shots',()=>{assert.equal(SHOTS.length,20);assert.equal(SHOTS[0].world,'farm');assert.equal(SHOTS[0].start,0);for(let i=1;i<20;i++)assert.equal(SHOTS[i-1].end,SHOTS[i].start);assert.equal(SHOTS.at(-1).end,90);for(let f=0;f<2160;f++){const t=f/24;assert.equal(SHOTS.filter(s=>t>=s.start&&t<s.end).length,1);assert.ok(shotAt(t));}});
test('The hero stays in the collection box during the grocery cutaway; trash is only a thought',()=>{for(let t=37;t<44;t+=.25){const s=storyState(t);assert.equal(s.owner,'collection-box');assert.equal(s.heroAtStore,false);assert.equal(s.bubble,false);}for(let t=47;t<52;t+=.25)assert.equal(storyState(t).bubble,true);assert.equal(storyState(52).bubble,false);assert.equal(storyState(84).owner,'plate');});
test('Seed changes do not change hero geometry or identity',()=>{const a=carrot({hero:true,seed:1}),b=carrot({hero:true,seed:999});assert.equal(a.userData.identity,b.userData.identity);assert.deepEqual([...a.userData.body.geometry.attributes.position.array],[...b.userData.body.geometry.attributes.position.array]);assert.equal(a.userData.bend,1.25);});
test('The split follows connected belt centerlines; imperfect is screen-left',()=>{for(const side of [-1,1])for(const boundary of [2.44,3.90]){const a=new T.Vector3(...laneMotion(boundary-.00001,side)),b=new T.Vector3(...laneMotion(boundary+.00001,side));assert.ok(a.distanceTo(b)<.0001);}const w=world('factory');direct(w,camera,29.5,config);const left=new T.Vector3(...laneMotion(4.5,-1)).project(camera),right=new T.Vector3(...laneMotion(4.5,1)).project(camera);assert.ok(left.x<right.x);assert.ok(laneMotion(4.5,-1)[0]<0);});
test('Arbitrary scrubbing returns the identical visible scene and camera',()=>{for(const shot of SHOTS){const w=world(shot.world),t=(shot.start+shot.end)/2,a=snapshot(w,t);snapshot(w,shot.start+.05);snapshot(w,shot.end-.05);const b=snapshot(w,t);assert.deepEqual(b,a,shot.title);}});
test('Every shot has a finite camera; hero-focused shots contain the hero',()=>{const close=[2,6,8,11,12,13,15,19,20];for(const shot of SHOTS){const w=world(shot.world);for(const u of [.1,.5,.9]){direct(w,camera,shot.start+(shot.end-shot.start)*u,config);assert.ok(camera.matrixWorld.elements.every(Number.isFinite),shot.title);assert.ok(camera.near>0&&camera.far>camera.near);if(close.includes(shot.id)){const point=w.hero.localToWorld(new T.Vector3(0,.20,0)).project(camera);assert.ok(Math.abs(point.x)<1.1&&Math.abs(point.y)<1.1&&point.z<1,`${shot.id} at ${u}: ${point.toArray()}`);}}}});
test('Belt spacing keeps the hero clear of background carrots',()=>{const w=world('factory');for(let t=17;t<33;t+=.125){direct(w,camera,t,config);for(const v of w.beltProduce)if(v.visible)assert.ok(v.position.distanceTo(w.hero.position)>=.569);}});
test('Project JSON round-trips seed, format, store and house; malformed enums are bounded',()=>{const input={seed:'VV1-CHANGES',format:'portrait',store:'hall',house:'brick',quality:'balanced',grain:.4,sound:false},p=buildManifest(input);assert.deepEqual(settings(JSON.parse(JSON.stringify(p)).settings),settings(input));const bad=settings({seed:'../../<script>',grain:500,format:'square',quality:'infinite'});assert.equal(bad.grain,1);assert.equal(bad.format,'wide');assert.equal(bad.quality,'high');assert.ok(!bad.seed.includes('/'));});
test('Seeded store variants change layout while keeping three happy front carrots',()=>{const a=buildWorld('store',settings({seed:'ALPHA'})),b=buildWorld('store',settings({seed:'BETA'}));assert.notEqual(a.aisle,b.aisle);for(const w of [a,b]){assert.equal(w.happy.length,3);assert.equal(w.hero.visible,false);for(const v of w.happy)assert.ok(Math.abs(v.userData.bend)<.2);}});
test('Procedural score is deterministic, finite and exportable as a valid PCM WAV',()=>{const a=pcm(47,1),b=pcm(47,1);assert.deepEqual(a,b);assert.ok(a.every(v=>Number.isFinite(v)&&Math.abs(v)<=1));assert.ok(a.some(v=>Math.abs(v)>.001));const bytes=wav(0,.1),view=new DataView(bytes);assert.equal(view.getUint32(24,true),48000);assert.equal(view.getUint16(22,true),1);assert.equal(bytes.byteLength,44+4800*2);});
test('Studio jobs use 90-second narratives and correct render dimensions',()=>{const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');const source=html.slice(html.indexOf('const STUDIOS ='),html.indexOf('/* ================= IDEA → STUDIO ROUTING'));const context=vm.createContext({});vm.runInContext(source+';globalThis.STUDIOS=STUDIOS;globalThis.INTENTS=INTENTS;globalThis.renderUrl=renderUrl;',context);assert.ok(context.STUDIOS['vita-verde']);assert.equal(context.INTENTS['narrative-film'].seconds,90);const u=new URL(context.renderUrl({studio:'vita-verde',seed:'VV1-TEST',id:'v1',kind:'video',w:1080,h:1920,fps:30,seconds:10800},'final'));assert.equal(u.searchParams.get('seconds'),'90');assert.equal(u.searchParams.get('fps'),'24');assert.equal(u.searchParams.get('w'),'1080');});
test('The delivery wrists stay in contact with the box throughout lowering',()=>{const w=world('house');for(let t=72;t<76.4;t+=.05){direct(w,camera,t,config);for(let i=0;i<2;i++){const a=w.farmer.userData.arms[i].hand.getWorldPosition(new T.Vector3()),b=w.hands[1-i].getWorldPosition(new T.Vector3());assert.ok(a.distanceTo(b)<.001,`contact drift at ${t}`);}}});
test('The conveyor-to-fall position is continuous',()=>{const w=world('factory');direct(w,camera,32.99999,config);const a=w.hero.position.clone();direct(w,camera,33,config);assert.ok(a.distanceTo(w.hero.position)<.0001);});
test('Portrait framing retains the hero at important story moments',()=>{const pc={...config,format:'portrait'},cam=new T.PerspectiveCamera(44,9/16,.008,140);for(const t of [6.5,24.5,34.6,45.5,49,55,62,64.5,84,88.5]){const w=world(shotAt(t).world);direct(w,cam,t,pc);const p=w.hero.localToWorld(new T.Vector3(0,.2,0)).project(cam);assert.ok(Math.abs(p.x)<1&&Math.abs(p.y)<1,`${t}: ${p.toArray()}`);}});
test('Portrait sorting cameras remain inside the factory back wall',()=>{const pc={...config,format:'portrait'},cam=new T.PerspectiveCamera(44,9/16,.008,140),w=world('factory');for(const id of [5,7]){const s=SHOTS[id-1];for(let t=s.start;t<s.end;t+=.25){direct(w,cam,t,pc);assert.ok(cam.position.z<5.7,`camera behind wall at ${t}`);}}});
test('Steam stays centimetres wide and cannot envelop the dinner camera',()=>{const w=world('dinner');for(let t=81;t<90;t+=.1){direct(w,camera,t,config);for(const puff of w.steam){assert.ok(puff.scale.x<=.031&&puff.scale.y<=.051&&puff.scale.z<=.026);}}});
